/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AccessChangePasswordRequest,
    AccessChangePasswordRequestFromJSON,
    AccessChangePasswordRequestToJSON,
} from '../models/AccessChangePasswordRequest';
import {
    type AccessChangePasswordResponse,
    AccessChangePasswordResponseFromJSON,
    AccessChangePasswordResponseToJSON,
} from '../models/AccessChangePasswordResponse';
import {
    type AccessGetAccessResponse,
    AccessGetAccessResponseFromJSON,
    AccessGetAccessResponseToJSON,
} from '../models/AccessGetAccessResponse';
import {
    type AccessPermissionsResponse,
    AccessPermissionsResponseFromJSON,
    AccessPermissionsResponseToJSON,
} from '../models/AccessPermissionsResponse';
import {
    type AccessVerifyVncTicketRequest,
    AccessVerifyVncTicketRequestFromJSON,
    AccessVerifyVncTicketRequestToJSON,
} from '../models/AccessVerifyVncTicketRequest';
import {
    type AccessVerifyVncTicketResponse,
    AccessVerifyVncTicketResponseFromJSON,
    AccessVerifyVncTicketResponseToJSON,
} from '../models/AccessVerifyVncTicketResponse';
import {
    type PveError,
    PveErrorFromJSON,
    PveErrorToJSON,
} from '../models/PveError';

export interface AccessApiChangePasswordRequest {
    accessChangePasswordRequest: AccessChangePasswordRequest;
}

export interface AccessApiPermissionsRequest {
    path?: string;
    userid?: string;
}

export interface AccessApiVerifyVncTicketRequest {
    accessVerifyVncTicketRequest: AccessVerifyVncTicketRequest;
}

/**
 * 
 */
export class AccessApi extends runtime.BaseAPI {

    /**
     * Creates request options for changePassword without sending the request
     */
    async changePasswordRequestOpts(requestParameters: AccessApiChangePasswordRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accessChangePasswordRequest'] == null) {
            throw new runtime.RequiredError(
                'accessChangePasswordRequest',
                'Required parameter "accessChangePasswordRequest" was null or undefined when calling changePassword().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/access/password`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AccessChangePasswordRequestToJSON(requestParameters['accessChangePasswordRequest']),
        };
    }

    /**
     * Change user password.  Permissions: Each user is allowed to change their own password. A user can change the password of another user if they have \'Realm.AllocateUser\' (on the realm of user <userid>) and \'User.Modify\' permission on /access/groups/<group> on a group where user <userid> is member of. For the PAM realm, a password change does not take  effect cluster-wide, but only applies to the local node.
     * Change user password
     */
    async changePasswordRaw(requestParameters: AccessApiChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessChangePasswordResponse>> {
        const requestOptions = await this.changePasswordRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessChangePasswordResponseFromJSON(jsonValue));
    }

    /**
     * Change user password.  Permissions: Each user is allowed to change their own password. A user can change the password of another user if they have \'Realm.AllocateUser\' (on the realm of user <userid>) and \'User.Modify\' permission on /access/groups/<group> on a group where user <userid> is member of. For the PAM realm, a password change does not take  effect cluster-wide, but only applies to the local node.
     * Change user password
     */
    async changePassword(requestParameters: AccessApiChangePasswordRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessChangePasswordResponse> {
        const response = await this.changePasswordRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getAccess without sending the request
     */
    async getAccessRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/access`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Directory index.
     * Directory index
     */
    async getAccessRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessGetAccessResponse>> {
        const requestOptions = await this.getAccessRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessGetAccessResponseFromJSON(jsonValue));
    }

    /**
     * Directory index.
     * Directory index
     */
    async getAccess(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessGetAccessResponse> {
        const response = await this.getAccessRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for permissions without sending the request
     */
    async permissionsRequestOpts(requestParameters: AccessApiPermissionsRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['path'] != null) {
            queryParameters['path'] = requestParameters['path'];
        }

        if (requestParameters['userid'] != null) {
            queryParameters['userid'] = requestParameters['userid'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/access/permissions`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Retrieve effective permissions of given user/token.  Permissions: Each user/token is allowed to dump their own permissions (or that of owned tokens). A user can dump the permissions of another user or their tokens if they have \'Sys.Audit\' permission on /access.
     * Retrieve effective permissions of given user/token
     */
    async permissionsRaw(requestParameters: AccessApiPermissionsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessPermissionsResponse>> {
        const requestOptions = await this.permissionsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessPermissionsResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve effective permissions of given user/token.  Permissions: Each user/token is allowed to dump their own permissions (or that of owned tokens). A user can dump the permissions of another user or their tokens if they have \'Sys.Audit\' permission on /access.
     * Retrieve effective permissions of given user/token
     */
    async permissions(requestParameters: AccessApiPermissionsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessPermissionsResponse> {
        const response = await this.permissionsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for verifyVncTicket without sending the request
     */
    async verifyVncTicketRequestOpts(requestParameters: AccessApiVerifyVncTicketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['accessVerifyVncTicketRequest'] == null) {
            throw new runtime.RequiredError(
                'accessVerifyVncTicketRequest',
                'Required parameter "accessVerifyVncTicketRequest" was null or undefined when calling verifyVncTicket().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/access/vncticket`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AccessVerifyVncTicketRequestToJSON(requestParameters['accessVerifyVncTicketRequest']),
        };
    }

    /**
     * verify VNC authentication ticket.  Permissions: You need to pass valid credientials.
     * verify VNC authentication ticket
     */
    async verifyVncTicketRaw(requestParameters: AccessApiVerifyVncTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AccessVerifyVncTicketResponse>> {
        const requestOptions = await this.verifyVncTicketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AccessVerifyVncTicketResponseFromJSON(jsonValue));
    }

    /**
     * verify VNC authentication ticket.  Permissions: You need to pass valid credientials.
     * verify VNC authentication ticket
     */
    async verifyVncTicket(requestParameters: AccessApiVerifyVncTicketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AccessVerifyVncTicketResponse> {
        const response = await this.verifyVncTicketRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
