/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type ClusterBackupCreateJobRequest,
    ClusterBackupCreateJobRequestFromJSON,
    ClusterBackupCreateJobRequestToJSON,
} from '../models/ClusterBackupCreateJobRequest';
import {
    type ClusterBackupCreateJobResponse,
    ClusterBackupCreateJobResponseFromJSON,
    ClusterBackupCreateJobResponseToJSON,
} from '../models/ClusterBackupCreateJobResponse';
import {
    type ClusterBackupDeleteJobResponse,
    ClusterBackupDeleteJobResponseFromJSON,
    ClusterBackupDeleteJobResponseToJSON,
} from '../models/ClusterBackupDeleteJobResponse';
import {
    type ClusterBackupGetBackupResponse,
    ClusterBackupGetBackupResponseFromJSON,
    ClusterBackupGetBackupResponseToJSON,
} from '../models/ClusterBackupGetBackupResponse';
import {
    type ClusterBackupGetVolumeBackupIncludedResponse,
    ClusterBackupGetVolumeBackupIncludedResponseFromJSON,
    ClusterBackupGetVolumeBackupIncludedResponseToJSON,
} from '../models/ClusterBackupGetVolumeBackupIncludedResponse';
import {
    type ClusterBackupReadJobResponse,
    ClusterBackupReadJobResponseFromJSON,
    ClusterBackupReadJobResponseToJSON,
} from '../models/ClusterBackupReadJobResponse';
import {
    type ClusterBackupUpdateJobRequest,
    ClusterBackupUpdateJobRequestFromJSON,
    ClusterBackupUpdateJobRequestToJSON,
} from '../models/ClusterBackupUpdateJobRequest';
import {
    type ClusterBackupUpdateJobResponse,
    ClusterBackupUpdateJobResponseFromJSON,
    ClusterBackupUpdateJobResponseToJSON,
} from '../models/ClusterBackupUpdateJobResponse';
import {
    type PveError,
    PveErrorFromJSON,
    PveErrorToJSON,
} from '../models/PveError';

export interface ClusterBackupApiCreateJobRequest {
    clusterBackupCreateJobRequest?: ClusterBackupCreateJobRequest;
}

export interface ClusterBackupApiDeleteJobRequest {
    id: string;
}

export interface ClusterBackupApiGetVolumeBackupIncludedRequest {
    id: string;
}

export interface ClusterBackupApiReadJobRequest {
    id: string;
}

export interface ClusterBackupApiUpdateJobRequest {
    id: string;
    clusterBackupUpdateJobRequest?: ClusterBackupUpdateJobRequest;
}

/**
 * 
 */
export class ClusterBackupApi extends runtime.BaseAPI {

    /**
     * Creates request options for createJob without sending the request
     */
    async createJobRequestOpts(requestParameters: ClusterBackupApiCreateJobRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/cluster/backup`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ClusterBackupCreateJobRequestToJSON(requestParameters['clusterBackupCreateJobRequest']),
        };
    }

    /**
     * Create new vzdump backup job.  Permissions: The \'tmpdir\', \'dumpdir\' and \'script\' parameters are additionally restricted to the \'root@pam\' user.
     * Create new vzdump backup job
     */
    async createJobRaw(requestParameters: ClusterBackupApiCreateJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClusterBackupCreateJobResponse>> {
        const requestOptions = await this.createJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClusterBackupCreateJobResponseFromJSON(jsonValue));
    }

    /**
     * Create new vzdump backup job.  Permissions: The \'tmpdir\', \'dumpdir\' and \'script\' parameters are additionally restricted to the \'root@pam\' user.
     * Create new vzdump backup job
     */
    async createJob(requestParameters: ClusterBackupApiCreateJobRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClusterBackupCreateJobResponse> {
        const response = await this.createJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteJob without sending the request
     */
    async deleteJobRequestOpts(requestParameters: ClusterBackupApiDeleteJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/cluster/backup/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete vzdump backup job definition.
     * Delete vzdump backup job definition
     */
    async deleteJobRaw(requestParameters: ClusterBackupApiDeleteJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClusterBackupDeleteJobResponse>> {
        const requestOptions = await this.deleteJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClusterBackupDeleteJobResponseFromJSON(jsonValue));
    }

    /**
     * Delete vzdump backup job definition.
     * Delete vzdump backup job definition
     */
    async deleteJob(requestParameters: ClusterBackupApiDeleteJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClusterBackupDeleteJobResponse> {
        const response = await this.deleteJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getBackup without sending the request
     */
    async getBackupRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/cluster/backup`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List vzdump backup schedule.
     * List vzdump backup schedule
     */
    async getBackupRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClusterBackupGetBackupResponse>> {
        const requestOptions = await this.getBackupRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClusterBackupGetBackupResponseFromJSON(jsonValue));
    }

    /**
     * List vzdump backup schedule.
     * List vzdump backup schedule
     */
    async getBackup(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClusterBackupGetBackupResponse> {
        const response = await this.getBackupRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getVolumeBackupIncluded without sending the request
     */
    async getVolumeBackupIncludedRequestOpts(requestParameters: ClusterBackupApiGetVolumeBackupIncludedRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getVolumeBackupIncluded().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/cluster/backup/{id}/included_volumes`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns included guests and the backup status of their disks. Optimized to be used in ExtJS tree views.
     * Returns included guests and the backup status of their disks
     */
    async getVolumeBackupIncludedRaw(requestParameters: ClusterBackupApiGetVolumeBackupIncludedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClusterBackupGetVolumeBackupIncludedResponse>> {
        const requestOptions = await this.getVolumeBackupIncludedRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClusterBackupGetVolumeBackupIncludedResponseFromJSON(jsonValue));
    }

    /**
     * Returns included guests and the backup status of their disks. Optimized to be used in ExtJS tree views.
     * Returns included guests and the backup status of their disks
     */
    async getVolumeBackupIncluded(requestParameters: ClusterBackupApiGetVolumeBackupIncludedRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClusterBackupGetVolumeBackupIncludedResponse> {
        const response = await this.getVolumeBackupIncludedRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for readJob without sending the request
     */
    async readJobRequestOpts(requestParameters: ClusterBackupApiReadJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling readJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/cluster/backup/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read vzdump backup job definition.
     * Read vzdump backup job definition
     */
    async readJobRaw(requestParameters: ClusterBackupApiReadJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClusterBackupReadJobResponse>> {
        const requestOptions = await this.readJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClusterBackupReadJobResponseFromJSON(jsonValue));
    }

    /**
     * Read vzdump backup job definition.
     * Read vzdump backup job definition
     */
    async readJob(requestParameters: ClusterBackupApiReadJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClusterBackupReadJobResponse> {
        const response = await this.readJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateJob without sending the request
     */
    async updateJobRequestOpts(requestParameters: ClusterBackupApiUpdateJobRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling updateJob().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/cluster/backup/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: ClusterBackupUpdateJobRequestToJSON(requestParameters['clusterBackupUpdateJobRequest']),
        };
    }

    /**
     * Update vzdump backup job definition.  Permissions: The \'tmpdir\', \'dumpdir\' and \'script\' parameters are additionally restricted to the \'root@pam\' user.
     * Update vzdump backup job definition
     */
    async updateJobRaw(requestParameters: ClusterBackupApiUpdateJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ClusterBackupUpdateJobResponse>> {
        const requestOptions = await this.updateJobRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ClusterBackupUpdateJobResponseFromJSON(jsonValue));
    }

    /**
     * Update vzdump backup job definition.  Permissions: The \'tmpdir\', \'dumpdir\' and \'script\' parameters are additionally restricted to the \'root@pam\' user.
     * Update vzdump backup job definition
     */
    async updateJob(requestParameters: ClusterBackupApiUpdateJobRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ClusterBackupUpdateJobResponse> {
        const response = await this.updateJobRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
