/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NodesExecuteRequest,
    NodesExecuteRequestFromJSON,
    NodesExecuteRequestToJSON,
} from '../models/NodesExecuteRequest';
import {
    type NodesExecuteResponse,
    NodesExecuteResponseFromJSON,
    NodesExecuteResponseToJSON,
} from '../models/NodesExecuteResponse';
import {
    type NodesGetNodesResponse,
    NodesGetNodesResponseFromJSON,
    NodesGetNodesResponseToJSON,
} from '../models/NodesGetNodesResponse';
import {
    type NodesIndexGetNodesResponse,
    NodesIndexGetNodesResponseFromJSON,
    NodesIndexGetNodesResponseToJSON,
} from '../models/NodesIndexGetNodesResponse';
import {
    type NodesJournalResponse,
    NodesJournalResponseFromJSON,
    NodesJournalResponseToJSON,
} from '../models/NodesJournalResponse';
import {
    type NodesMigrateallRequest,
    NodesMigrateallRequestFromJSON,
    NodesMigrateallRequestToJSON,
} from '../models/NodesMigrateallRequest';
import {
    type NodesMigrateallResponse,
    NodesMigrateallResponseFromJSON,
    NodesMigrateallResponseToJSON,
} from '../models/NodesMigrateallResponse';
import {
    type NodesNetstatResponse,
    NodesNetstatResponseFromJSON,
    NodesNetstatResponseToJSON,
} from '../models/NodesNetstatResponse';
import {
    type NodesQueryOciRepoTagsResponse,
    NodesQueryOciRepoTagsResponseFromJSON,
    NodesQueryOciRepoTagsResponseToJSON,
} from '../models/NodesQueryOciRepoTagsResponse';
import {
    type NodesQueryUrlMetadataResponse,
    NodesQueryUrlMetadataResponseFromJSON,
    NodesQueryUrlMetadataResponseToJSON,
} from '../models/NodesQueryUrlMetadataResponse';
import {
    type NodesReportResponse,
    NodesReportResponseFromJSON,
    NodesReportResponseToJSON,
} from '../models/NodesReportResponse';
import {
    type NodesRrdResponse,
    NodesRrdResponseFromJSON,
    NodesRrdResponseToJSON,
} from '../models/NodesRrdResponse';
import {
    type NodesRrddataResponse,
    NodesRrddataResponseFromJSON,
    NodesRrddataResponseToJSON,
} from '../models/NodesRrddataResponse';
import {
    type NodesSpiceshellRequest,
    NodesSpiceshellRequestFromJSON,
    NodesSpiceshellRequestToJSON,
} from '../models/NodesSpiceshellRequest';
import {
    type NodesSpiceshellResponse,
    NodesSpiceshellResponseFromJSON,
    NodesSpiceshellResponseToJSON,
} from '../models/NodesSpiceshellResponse';
import {
    type NodesStartallRequest,
    NodesStartallRequestFromJSON,
    NodesStartallRequestToJSON,
} from '../models/NodesStartallRequest';
import {
    type NodesStartallResponse,
    NodesStartallResponseFromJSON,
    NodesStartallResponseToJSON,
} from '../models/NodesStartallResponse';
import {
    type NodesStopallRequest,
    NodesStopallRequestFromJSON,
    NodesStopallRequestToJSON,
} from '../models/NodesStopallRequest';
import {
    type NodesStopallResponse,
    NodesStopallResponseFromJSON,
    NodesStopallResponseToJSON,
} from '../models/NodesStopallResponse';
import {
    type NodesSuspendallRequest,
    NodesSuspendallRequestFromJSON,
    NodesSuspendallRequestToJSON,
} from '../models/NodesSuspendallRequest';
import {
    type NodesSuspendallResponse,
    NodesSuspendallResponseFromJSON,
    NodesSuspendallResponseToJSON,
} from '../models/NodesSuspendallResponse';
import {
    type NodesSyslogResponse,
    NodesSyslogResponseFromJSON,
    NodesSyslogResponseToJSON,
} from '../models/NodesSyslogResponse';
import {
    type NodesTermproxyRequest,
    NodesTermproxyRequestFromJSON,
    NodesTermproxyRequestToJSON,
} from '../models/NodesTermproxyRequest';
import {
    type NodesTermproxyResponse,
    NodesTermproxyResponseFromJSON,
    NodesTermproxyResponseToJSON,
} from '../models/NodesTermproxyResponse';
import {
    type NodesVersionResponse,
    NodesVersionResponseFromJSON,
    NodesVersionResponseToJSON,
} from '../models/NodesVersionResponse';
import {
    type NodesVncshellRequest,
    NodesVncshellRequestFromJSON,
    NodesVncshellRequestToJSON,
} from '../models/NodesVncshellRequest';
import {
    type NodesVncshellResponse,
    NodesVncshellResponseFromJSON,
    NodesVncshellResponseToJSON,
} from '../models/NodesVncshellResponse';
import {
    type NodesVncwebsocketResponse,
    NodesVncwebsocketResponseFromJSON,
    NodesVncwebsocketResponseToJSON,
} from '../models/NodesVncwebsocketResponse';
import {
    type NodesWakeonlanResponse,
    NodesWakeonlanResponseFromJSON,
    NodesWakeonlanResponseToJSON,
} from '../models/NodesWakeonlanResponse';
import {
    type PveBoolean,
    PveBooleanFromJSON,
    PveBooleanToJSON,
} from '../models/PveBoolean';
import {
    type PveCfEnum,
    PveCfEnumFromJSON,
    PveCfEnumToJSON,
} from '../models/PveCfEnum';
import {
    type PveError,
    PveErrorFromJSON,
    PveErrorToJSON,
} from '../models/PveError';
import {
    type PveNodesTimeframeEnum,
    PveNodesTimeframeEnumFromJSON,
    PveNodesTimeframeEnumToJSON,
} from '../models/PveNodesTimeframeEnum';

export interface NodesApiExecuteRequest {
    node: string;
    nodesExecuteRequest: NodesExecuteRequest;
}

export interface NodesApiIndexGetNodesRequest {
    node: string;
}

export interface NodesApiJournalRequest {
    node: string;
    endcursor?: string;
    lastentries?: number;
    since?: number;
    startcursor?: string;
    until?: number;
}

export interface NodesApiMigrateallRequest {
    node: string;
    nodesMigrateallRequest: NodesMigrateallRequest;
}

export interface NodesApiNetstatRequest {
    node: string;
}

export interface NodesApiQueryOciRepoTagsRequest {
    node: string;
    reference: string;
}

export interface NodesApiQueryUrlMetadataRequest {
    node: string;
    url: string;
    verifyCertificates?: PveBoolean;
}

export interface NodesApiReportRequest {
    node: string;
}

export interface NodesApiRrdRequest {
    ds: string;
    node: string;
    timeframe: PveNodesTimeframeEnum;
    cf?: PveCfEnum;
}

export interface NodesApiRrddataRequest {
    node: string;
    timeframe: PveNodesTimeframeEnum;
    cf?: PveCfEnum;
}

export interface NodesApiSpiceshellRequest {
    node: string;
    nodesSpiceshellRequest?: NodesSpiceshellRequest;
}

export interface NodesApiStartallRequest {
    node: string;
    nodesStartallRequest?: NodesStartallRequest;
}

export interface NodesApiStopallRequest {
    node: string;
    nodesStopallRequest?: NodesStopallRequest;
}

export interface NodesApiSuspendallRequest {
    node: string;
    nodesSuspendallRequest?: NodesSuspendallRequest;
}

export interface NodesApiSyslogRequest {
    node: string;
    limit?: number;
    service?: string;
    since?: string;
    start?: number;
    until?: string;
}

export interface NodesApiTermproxyRequest {
    node: string;
    nodesTermproxyRequest?: NodesTermproxyRequest;
}

export interface NodesApiVersionRequest {
    node: string;
}

export interface NodesApiVncshellRequest {
    node: string;
    nodesVncshellRequest?: NodesVncshellRequest;
}

export interface NodesApiVncwebsocketRequest {
    node: string;
    port: number;
    vncticket: string;
}

export interface NodesApiWakeonlanRequest {
    node: string;
}

/**
 * 
 */
export class NodesApi extends runtime.BaseAPI {

    /**
     * Creates request options for execute without sending the request
     */
    async executeRequestOpts(requestParameters: NodesApiExecuteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling execute().'
            );
        }

        if (requestParameters['nodesExecuteRequest'] == null) {
            throw new runtime.RequiredError(
                'nodesExecuteRequest',
                'Required parameter "nodesExecuteRequest" was null or undefined when calling execute().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/execute`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesExecuteRequestToJSON(requestParameters['nodesExecuteRequest']),
        };
    }

    /**
     * Execute multiple commands in order, root only.
     * Execute multiple commands in order, root only
     */
    async executeRaw(requestParameters: NodesApiExecuteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesExecuteResponse>> {
        const requestOptions = await this.executeRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesExecuteResponseFromJSON(jsonValue));
    }

    /**
     * Execute multiple commands in order, root only.
     * Execute multiple commands in order, root only
     */
    async execute(requestParameters: NodesApiExecuteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesExecuteResponse> {
        const response = await this.executeRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getNodes without sending the request
     */
    async getNodesRequestOpts(): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Cluster node index.
     * Cluster node index
     */
    async getNodesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesGetNodesResponse>> {
        const requestOptions = await this.getNodesRequestOpts();
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesGetNodesResponseFromJSON(jsonValue));
    }

    /**
     * Cluster node index.
     * Cluster node index
     */
    async getNodes(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesGetNodesResponse> {
        const response = await this.getNodesRaw(initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for indexGetNodes without sending the request
     */
    async indexGetNodesRequestOpts(requestParameters: NodesApiIndexGetNodesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling indexGetNodes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Node index.
     * Node index
     */
    async indexGetNodesRaw(requestParameters: NodesApiIndexGetNodesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesIndexGetNodesResponse>> {
        const requestOptions = await this.indexGetNodesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesIndexGetNodesResponseFromJSON(jsonValue));
    }

    /**
     * Node index.
     * Node index
     */
    async indexGetNodes(requestParameters: NodesApiIndexGetNodesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesIndexGetNodesResponse> {
        const response = await this.indexGetNodesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for journal without sending the request
     */
    async journalRequestOpts(requestParameters: NodesApiJournalRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling journal().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['endcursor'] != null) {
            queryParameters['endcursor'] = requestParameters['endcursor'];
        }

        if (requestParameters['lastentries'] != null) {
            queryParameters['lastentries'] = requestParameters['lastentries'];
        }

        if (requestParameters['since'] != null) {
            queryParameters['since'] = requestParameters['since'];
        }

        if (requestParameters['startcursor'] != null) {
            queryParameters['startcursor'] = requestParameters['startcursor'];
        }

        if (requestParameters['until'] != null) {
            queryParameters['until'] = requestParameters['until'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/journal`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read Journal
     * Read Journal
     */
    async journalRaw(requestParameters: NodesApiJournalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesJournalResponse>> {
        const requestOptions = await this.journalRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesJournalResponseFromJSON(jsonValue));
    }

    /**
     * Read Journal
     * Read Journal
     */
    async journal(requestParameters: NodesApiJournalRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesJournalResponse> {
        const response = await this.journalRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for migrateall without sending the request
     */
    async migrateallRequestOpts(requestParameters: NodesApiMigrateallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling migrateall().'
            );
        }

        if (requestParameters['nodesMigrateallRequest'] == null) {
            throw new runtime.RequiredError(
                'nodesMigrateallRequest',
                'Required parameter "nodesMigrateallRequest" was null or undefined when calling migrateall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/migrateall`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesMigrateallRequestToJSON(requestParameters['nodesMigrateallRequest']),
        };
    }

    /**
     * Migrate all VMs and Containers.  Permissions: The \'VM.Migrate\' permission is required on \'/\' or on \'/vms/<ID>\' for each ID passed via the \'vms\' parameter.
     * Migrate all VMs and Containers
     */
    async migrateallRaw(requestParameters: NodesApiMigrateallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesMigrateallResponse>> {
        const requestOptions = await this.migrateallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesMigrateallResponseFromJSON(jsonValue));
    }

    /**
     * Migrate all VMs and Containers.  Permissions: The \'VM.Migrate\' permission is required on \'/\' or on \'/vms/<ID>\' for each ID passed via the \'vms\' parameter.
     * Migrate all VMs and Containers
     */
    async migrateall(requestParameters: NodesApiMigrateallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesMigrateallResponse> {
        const response = await this.migrateallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for netstat without sending the request
     */
    async netstatRequestOpts(requestParameters: NodesApiNetstatRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling netstat().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/netstat`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read tap/vm network device interface counters
     * Read tap/vm network device interface counters
     */
    async netstatRaw(requestParameters: NodesApiNetstatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesNetstatResponse>> {
        const requestOptions = await this.netstatRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesNetstatResponseFromJSON(jsonValue));
    }

    /**
     * Read tap/vm network device interface counters
     * Read tap/vm network device interface counters
     */
    async netstat(requestParameters: NodesApiNetstatRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesNetstatResponse> {
        const response = await this.netstatRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for queryOciRepoTags without sending the request
     */
    async queryOciRepoTagsRequestOpts(requestParameters: NodesApiQueryOciRepoTagsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling queryOciRepoTags().'
            );
        }

        if (requestParameters['reference'] == null) {
            throw new runtime.RequiredError(
                'reference',
                'Required parameter "reference" was null or undefined when calling queryOciRepoTags().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['reference'] != null) {
            queryParameters['reference'] = requestParameters['reference'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/query-oci-repo-tags`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List all tags for an OCI repository reference.
     * List all tags for an OCI repository reference
     */
    async queryOciRepoTagsRaw(requestParameters: NodesApiQueryOciRepoTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesQueryOciRepoTagsResponse>> {
        const requestOptions = await this.queryOciRepoTagsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesQueryOciRepoTagsResponseFromJSON(jsonValue));
    }

    /**
     * List all tags for an OCI repository reference.
     * List all tags for an OCI repository reference
     */
    async queryOciRepoTags(requestParameters: NodesApiQueryOciRepoTagsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesQueryOciRepoTagsResponse> {
        const response = await this.queryOciRepoTagsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for queryUrlMetadata without sending the request
     */
    async queryUrlMetadataRequestOpts(requestParameters: NodesApiQueryUrlMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling queryUrlMetadata().'
            );
        }

        if (requestParameters['url'] == null) {
            throw new runtime.RequiredError(
                'url',
                'Required parameter "url" was null or undefined when calling queryUrlMetadata().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['url'] != null) {
            queryParameters['url'] = requestParameters['url'];
        }

        if (requestParameters['verifyCertificates'] != null) {
            queryParameters['verify-certificates'] = requestParameters['verifyCertificates'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/query-url-metadata`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Query metadata of an URL: file size, file name and mime type.
     * Query metadata of an URL: file size, file name and mime type
     */
    async queryUrlMetadataRaw(requestParameters: NodesApiQueryUrlMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesQueryUrlMetadataResponse>> {
        const requestOptions = await this.queryUrlMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesQueryUrlMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Query metadata of an URL: file size, file name and mime type.
     * Query metadata of an URL: file size, file name and mime type
     */
    async queryUrlMetadata(requestParameters: NodesApiQueryUrlMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesQueryUrlMetadataResponse> {
        const response = await this.queryUrlMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for report without sending the request
     */
    async reportRequestOpts(requestParameters: NodesApiReportRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling report().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/report`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Gather various systems information about a node
     * Gather various systems information about a node
     */
    async reportRaw(requestParameters: NodesApiReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesReportResponse>> {
        const requestOptions = await this.reportRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesReportResponseFromJSON(jsonValue));
    }

    /**
     * Gather various systems information about a node
     * Gather various systems information about a node
     */
    async report(requestParameters: NodesApiReportRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesReportResponse> {
        const response = await this.reportRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rrd without sending the request
     */
    async rrdRequestOpts(requestParameters: NodesApiRrdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ds'] == null) {
            throw new runtime.RequiredError(
                'ds',
                'Required parameter "ds" was null or undefined when calling rrd().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling rrd().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling rrd().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cf'] != null) {
            queryParameters['cf'] = requestParameters['cf'];
        }

        if (requestParameters['ds'] != null) {
            queryParameters['ds'] = requestParameters['ds'];
        }

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/rrd`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read node RRD statistics (returns PNG)
     * Read node RRD statistics (returns PNG)
     */
    async rrdRaw(requestParameters: NodesApiRrdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesRrdResponse>> {
        const requestOptions = await this.rrdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesRrdResponseFromJSON(jsonValue));
    }

    /**
     * Read node RRD statistics (returns PNG)
     * Read node RRD statistics (returns PNG)
     */
    async rrd(requestParameters: NodesApiRrdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesRrdResponse> {
        const response = await this.rrdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rrddata without sending the request
     */
    async rrddataRequestOpts(requestParameters: NodesApiRrddataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling rrddata().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling rrddata().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cf'] != null) {
            queryParameters['cf'] = requestParameters['cf'];
        }

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/rrddata`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read node RRD statistics
     * Read node RRD statistics
     */
    async rrddataRaw(requestParameters: NodesApiRrddataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesRrddataResponse>> {
        const requestOptions = await this.rrddataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesRrddataResponseFromJSON(jsonValue));
    }

    /**
     * Read node RRD statistics
     * Read node RRD statistics
     */
    async rrddata(requestParameters: NodesApiRrddataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesRrddataResponse> {
        const response = await this.rrddataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for spiceshell without sending the request
     */
    async spiceshellRequestOpts(requestParameters: NodesApiSpiceshellRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling spiceshell().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/spiceshell`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesSpiceshellRequestToJSON(requestParameters['nodesSpiceshellRequest']),
        };
    }

    /**
     * Creates a SPICE shell.
     * Creates a SPICE shell
     */
    async spiceshellRaw(requestParameters: NodesApiSpiceshellRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesSpiceshellResponse>> {
        const requestOptions = await this.spiceshellRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesSpiceshellResponseFromJSON(jsonValue));
    }

    /**
     * Creates a SPICE shell.
     * Creates a SPICE shell
     */
    async spiceshell(requestParameters: NodesApiSpiceshellRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesSpiceshellResponse> {
        const response = await this.spiceshellRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for startall without sending the request
     */
    async startallRequestOpts(requestParameters: NodesApiStartallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling startall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/startall`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesStartallRequestToJSON(requestParameters['nodesStartallRequest']),
        };
    }

    /**
     * Start all VMs and containers located on this node (by default only those with onboot=1).  Permissions: The \'VM.PowerMgmt\' permission is required on \'/\' or on \'/vms/<ID>\' for each ID passed via the \'vms\' parameter.
     * Start all VMs and containers located on this node (by default only those with onboot=1)
     */
    async startallRaw(requestParameters: NodesApiStartallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStartallResponse>> {
        const requestOptions = await this.startallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStartallResponseFromJSON(jsonValue));
    }

    /**
     * Start all VMs and containers located on this node (by default only those with onboot=1).  Permissions: The \'VM.PowerMgmt\' permission is required on \'/\' or on \'/vms/<ID>\' for each ID passed via the \'vms\' parameter.
     * Start all VMs and containers located on this node (by default only those with onboot=1)
     */
    async startall(requestParameters: NodesApiStartallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStartallResponse> {
        const response = await this.startallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for stopall without sending the request
     */
    async stopallRequestOpts(requestParameters: NodesApiStopallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling stopall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/stopall`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesStopallRequestToJSON(requestParameters['nodesStopallRequest']),
        };
    }

    /**
     * Stop all VMs and Containers.  Permissions: The \'VM.PowerMgmt\' permission is required on \'/\' or on \'/vms/<ID>\' for each ID passed via the \'vms\' parameter.
     * Stop all VMs and Containers
     */
    async stopallRaw(requestParameters: NodesApiStopallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStopallResponse>> {
        const requestOptions = await this.stopallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStopallResponseFromJSON(jsonValue));
    }

    /**
     * Stop all VMs and Containers.  Permissions: The \'VM.PowerMgmt\' permission is required on \'/\' or on \'/vms/<ID>\' for each ID passed via the \'vms\' parameter.
     * Stop all VMs and Containers
     */
    async stopall(requestParameters: NodesApiStopallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStopallResponse> {
        const response = await this.stopallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for suspendall without sending the request
     */
    async suspendallRequestOpts(requestParameters: NodesApiSuspendallRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling suspendall().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/suspendall`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesSuspendallRequestToJSON(requestParameters['nodesSuspendallRequest']),
        };
    }

    /**
     * Suspend all VMs.  Permissions: The \'VM.PowerMgmt\' permission is required on \'/\' or on \'/vms/<ID>\' for each ID passed via the \'vms\' parameter. Additionally, you need \'VM.Config.Disk\' on the \'/vms/{vmid}\' path and \'Datastore.AllocateSpace\' for the configured state-storage(s)
     * Suspend all VMs
     */
    async suspendallRaw(requestParameters: NodesApiSuspendallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesSuspendallResponse>> {
        const requestOptions = await this.suspendallRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesSuspendallResponseFromJSON(jsonValue));
    }

    /**
     * Suspend all VMs.  Permissions: The \'VM.PowerMgmt\' permission is required on \'/\' or on \'/vms/<ID>\' for each ID passed via the \'vms\' parameter. Additionally, you need \'VM.Config.Disk\' on the \'/vms/{vmid}\' path and \'Datastore.AllocateSpace\' for the configured state-storage(s)
     * Suspend all VMs
     */
    async suspendall(requestParameters: NodesApiSuspendallRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesSuspendallResponse> {
        const response = await this.suspendallRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for syslog without sending the request
     */
    async syslogRequestOpts(requestParameters: NodesApiSyslogRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling syslog().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['service'] != null) {
            queryParameters['service'] = requestParameters['service'];
        }

        if (requestParameters['since'] != null) {
            queryParameters['since'] = requestParameters['since'];
        }

        if (requestParameters['start'] != null) {
            queryParameters['start'] = requestParameters['start'];
        }

        if (requestParameters['until'] != null) {
            queryParameters['until'] = requestParameters['until'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/syslog`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read system log
     * Read system log
     */
    async syslogRaw(requestParameters: NodesApiSyslogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesSyslogResponse>> {
        const requestOptions = await this.syslogRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesSyslogResponseFromJSON(jsonValue));
    }

    /**
     * Read system log
     * Read system log
     */
    async syslog(requestParameters: NodesApiSyslogRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesSyslogResponse> {
        const response = await this.syslogRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for termproxy without sending the request
     */
    async termproxyRequestOpts(requestParameters: NodesApiTermproxyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling termproxy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/termproxy`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesTermproxyRequestToJSON(requestParameters['nodesTermproxyRequest']),
        };
    }

    /**
     * Creates a VNC Shell proxy.
     * Creates a VNC Shell proxy
     */
    async termproxyRaw(requestParameters: NodesApiTermproxyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesTermproxyResponse>> {
        const requestOptions = await this.termproxyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesTermproxyResponseFromJSON(jsonValue));
    }

    /**
     * Creates a VNC Shell proxy.
     * Creates a VNC Shell proxy
     */
    async termproxy(requestParameters: NodesApiTermproxyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesTermproxyResponse> {
        const response = await this.termproxyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for version without sending the request
     */
    async versionRequestOpts(requestParameters: NodesApiVersionRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling version().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/version`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * API version details
     * API version details
     */
    async versionRaw(requestParameters: NodesApiVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesVersionResponse>> {
        const requestOptions = await this.versionRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesVersionResponseFromJSON(jsonValue));
    }

    /**
     * API version details
     * API version details
     */
    async version(requestParameters: NodesApiVersionRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesVersionResponse> {
        const response = await this.versionRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for vncshell without sending the request
     */
    async vncshellRequestOpts(requestParameters: NodesApiVncshellRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling vncshell().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/vncshell`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesVncshellRequestToJSON(requestParameters['nodesVncshellRequest']),
        };
    }

    /**
     * Creates a VNC Shell proxy.
     * Creates a VNC Shell proxy
     */
    async vncshellRaw(requestParameters: NodesApiVncshellRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesVncshellResponse>> {
        const requestOptions = await this.vncshellRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesVncshellResponseFromJSON(jsonValue));
    }

    /**
     * Creates a VNC Shell proxy.
     * Creates a VNC Shell proxy
     */
    async vncshell(requestParameters: NodesApiVncshellRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesVncshellResponse> {
        const response = await this.vncshellRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for vncwebsocket without sending the request
     */
    async vncwebsocketRequestOpts(requestParameters: NodesApiVncwebsocketRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling vncwebsocket().'
            );
        }

        if (requestParameters['port'] == null) {
            throw new runtime.RequiredError(
                'port',
                'Required parameter "port" was null or undefined when calling vncwebsocket().'
            );
        }

        if (requestParameters['vncticket'] == null) {
            throw new runtime.RequiredError(
                'vncticket',
                'Required parameter "vncticket" was null or undefined when calling vncwebsocket().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['port'] != null) {
            queryParameters['port'] = requestParameters['port'];
        }

        if (requestParameters['vncticket'] != null) {
            queryParameters['vncticket'] = requestParameters['vncticket'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/vncwebsocket`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Opens a websocket for VNC traffic.  Permissions: You also need to pass a valid ticket (vncticket).  Wire-level note: this endpoint answers HTTP 101 Upgrade, not a JSON body. The 200 schema below is the apidoc-declared shape for tooling, but real clients perform a WebSocket upgrade and exchange framed messages on the resulting socket. See the `x-pve-websocket` extension for the framing and the list of sibling endpoints that issue tickets.
     * Opens a websocket for VNC traffic
     */
    async vncwebsocketRaw(requestParameters: NodesApiVncwebsocketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesVncwebsocketResponse>> {
        const requestOptions = await this.vncwebsocketRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesVncwebsocketResponseFromJSON(jsonValue));
    }

    /**
     * Opens a websocket for VNC traffic.  Permissions: You also need to pass a valid ticket (vncticket).  Wire-level note: this endpoint answers HTTP 101 Upgrade, not a JSON body. The 200 schema below is the apidoc-declared shape for tooling, but real clients perform a WebSocket upgrade and exchange framed messages on the resulting socket. See the `x-pve-websocket` extension for the framing and the list of sibling endpoints that issue tickets.
     * Opens a websocket for VNC traffic
     */
    async vncwebsocket(requestParameters: NodesApiVncwebsocketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesVncwebsocketResponse> {
        const response = await this.vncwebsocketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for wakeonlan without sending the request
     */
    async wakeonlanRequestOpts(requestParameters: NodesApiWakeonlanRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling wakeonlan().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/wakeonlan`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Try to wake a node via \'wake on LAN\' network packet.
     * Try to wake a node via \'wake on LAN\' network packet
     */
    async wakeonlanRaw(requestParameters: NodesApiWakeonlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesWakeonlanResponse>> {
        const requestOptions = await this.wakeonlanRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesWakeonlanResponseFromJSON(jsonValue));
    }

    /**
     * Try to wake a node via \'wake on LAN\' network packet.
     * Try to wake a node via \'wake on LAN\' network packet
     */
    async wakeonlan(requestParameters: NodesApiWakeonlanRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesWakeonlanResponse> {
        const response = await this.wakeonlanRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
