/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type NodesStorageCopyRequest,
    NodesStorageCopyRequestFromJSON,
    NodesStorageCopyRequestToJSON,
} from '../models/NodesStorageCopyRequest';
import {
    type NodesStorageCopyResponse,
    NodesStorageCopyResponseFromJSON,
    NodesStorageCopyResponseToJSON,
} from '../models/NodesStorageCopyResponse';
import {
    type NodesStorageCreateContentRequest,
    NodesStorageCreateContentRequestFromJSON,
    NodesStorageCreateContentRequestToJSON,
} from '../models/NodesStorageCreateContentRequest';
import {
    type NodesStorageCreateContentResponse,
    NodesStorageCreateContentResponseFromJSON,
    NodesStorageCreateContentResponseToJSON,
} from '../models/NodesStorageCreateContentResponse';
import {
    type NodesStorageDeleteContentResponse,
    NodesStorageDeleteContentResponseFromJSON,
    NodesStorageDeleteContentResponseToJSON,
} from '../models/NodesStorageDeleteContentResponse';
import {
    type NodesStorageDeletePrunebackupsResponse,
    NodesStorageDeletePrunebackupsResponseFromJSON,
    NodesStorageDeletePrunebackupsResponseToJSON,
} from '../models/NodesStorageDeletePrunebackupsResponse';
import {
    type NodesStorageDiridxResponse,
    NodesStorageDiridxResponseFromJSON,
    NodesStorageDiridxResponseToJSON,
} from '../models/NodesStorageDiridxResponse';
import {
    type NodesStorageDownloadResponse,
    NodesStorageDownloadResponseFromJSON,
    NodesStorageDownloadResponseToJSON,
} from '../models/NodesStorageDownloadResponse';
import {
    type NodesStorageDownloadUrlRequest,
    NodesStorageDownloadUrlRequestFromJSON,
    NodesStorageDownloadUrlRequestToJSON,
} from '../models/NodesStorageDownloadUrlRequest';
import {
    type NodesStorageDownloadUrlResponse,
    NodesStorageDownloadUrlResponseFromJSON,
    NodesStorageDownloadUrlResponseToJSON,
} from '../models/NodesStorageDownloadUrlResponse';
import {
    type NodesStorageDryrunResponse,
    NodesStorageDryrunResponseFromJSON,
    NodesStorageDryrunResponseToJSON,
} from '../models/NodesStorageDryrunResponse';
import {
    type NodesStorageGetContentResponse,
    NodesStorageGetContentResponseFromJSON,
    NodesStorageGetContentResponseToJSON,
} from '../models/NodesStorageGetContentResponse';
import {
    type NodesStorageGetImportMetadataResponse,
    NodesStorageGetImportMetadataResponseFromJSON,
    NodesStorageGetImportMetadataResponseToJSON,
} from '../models/NodesStorageGetImportMetadataResponse';
import {
    type NodesStorageGetListResponse,
    NodesStorageGetListResponseFromJSON,
    NodesStorageGetListResponseToJSON,
} from '../models/NodesStorageGetListResponse';
import {
    type NodesStorageGetStorageResponse,
    NodesStorageGetStorageResponseFromJSON,
    NodesStorageGetStorageResponseToJSON,
} from '../models/NodesStorageGetStorageResponse';
import {
    type NodesStorageInfoResponse,
    NodesStorageInfoResponseFromJSON,
    NodesStorageInfoResponseToJSON,
} from '../models/NodesStorageInfoResponse';
import {
    type NodesStorageOciRegistryPullRequest,
    NodesStorageOciRegistryPullRequestFromJSON,
    NodesStorageOciRegistryPullRequestToJSON,
} from '../models/NodesStorageOciRegistryPullRequest';
import {
    type NodesStorageOciRegistryPullResponse,
    NodesStorageOciRegistryPullResponseFromJSON,
    NodesStorageOciRegistryPullResponseToJSON,
} from '../models/NodesStorageOciRegistryPullResponse';
import {
    type NodesStorageReadStatusResponse,
    NodesStorageReadStatusResponseFromJSON,
    NodesStorageReadStatusResponseToJSON,
} from '../models/NodesStorageReadStatusResponse';
import {
    type NodesStorageRrdResponse,
    NodesStorageRrdResponseFromJSON,
    NodesStorageRrdResponseToJSON,
} from '../models/NodesStorageRrdResponse';
import {
    type NodesStorageRrddataResponse,
    NodesStorageRrddataResponseFromJSON,
    NodesStorageRrddataResponseToJSON,
} from '../models/NodesStorageRrddataResponse';
import {
    type NodesStorageUpdateattributesRequest,
    NodesStorageUpdateattributesRequestFromJSON,
    NodesStorageUpdateattributesRequestToJSON,
} from '../models/NodesStorageUpdateattributesRequest';
import {
    type NodesStorageUpdateattributesResponse,
    NodesStorageUpdateattributesResponseFromJSON,
    NodesStorageUpdateattributesResponseToJSON,
} from '../models/NodesStorageUpdateattributesResponse';
import {
    type NodesStorageUploadRequest,
    NodesStorageUploadRequestFromJSON,
    NodesStorageUploadRequestToJSON,
} from '../models/NodesStorageUploadRequest';
import {
    type NodesStorageUploadResponse,
    NodesStorageUploadResponseFromJSON,
    NodesStorageUploadResponseToJSON,
} from '../models/NodesStorageUploadResponse';
import {
    type PveBoolean,
    PveBooleanFromJSON,
    PveBooleanToJSON,
} from '../models/PveBoolean';
import {
    type PveCfEnum,
    PveCfEnumFromJSON,
    PveCfEnumToJSON,
} from '../models/PveCfEnum';
import {
    type PveClusterBackupInfoTypeEnum,
    PveClusterBackupInfoTypeEnumFromJSON,
    PveClusterBackupInfoTypeEnumToJSON,
} from '../models/PveClusterBackupInfoTypeEnum';
import {
    type PveError,
    PveErrorFromJSON,
    PveErrorToJSON,
} from '../models/PveError';
import {
    type PveTimeframeEnum,
    PveTimeframeEnumFromJSON,
    PveTimeframeEnumToJSON,
} from '../models/PveTimeframeEnum';

export interface NodesStorageApiCopyRequest {
    node: string;
    storage: string;
    volume: string;
    nodesStorageCopyRequest: NodesStorageCopyRequest;
}

export interface NodesStorageApiCreateContentRequest {
    node: string;
    storage: string;
    nodesStorageCreateContentRequest: NodesStorageCreateContentRequest;
}

export interface NodesStorageApiDeleteContentRequest {
    node: string;
    storage: string;
    volume: string;
    delay?: number;
}

export interface NodesStorageApiDeletePrunebackupsRequest {
    node: string;
    storage: string;
    pruneBackups?: string;
    type?: PveClusterBackupInfoTypeEnum;
    vmid?: number;
}

export interface NodesStorageApiDiridxRequest {
    node: string;
    storage: string;
}

export interface NodesStorageApiDownloadRequest {
    filepath: string;
    node: string;
    storage: string;
    volume: string;
    tar?: PveBoolean;
}

export interface NodesStorageApiDownloadUrlRequest {
    node: string;
    storage: string;
    nodesStorageDownloadUrlRequest: NodesStorageDownloadUrlRequest;
}

export interface NodesStorageApiDryrunRequest {
    node: string;
    storage: string;
    pruneBackups?: string;
    type?: PveClusterBackupInfoTypeEnum;
    vmid?: number;
}

export interface NodesStorageApiGetContentRequest {
    node: string;
    storage: string;
    content?: string;
    vmid?: number;
}

export interface NodesStorageApiGetImportMetadataRequest {
    node: string;
    storage: string;
    volume: string;
}

export interface NodesStorageApiGetListRequest {
    filepath: string;
    node: string;
    storage: string;
    volume: string;
}

export interface NodesStorageApiGetStorageRequest {
    node: string;
    content?: string;
    enabled?: PveBoolean;
    format?: PveBoolean;
    storage?: string;
    target?: string;
}

export interface NodesStorageApiInfoRequest {
    node: string;
    storage: string;
    volume: string;
}

export interface NodesStorageApiOciRegistryPullRequest {
    node: string;
    storage: string;
    nodesStorageOciRegistryPullRequest: NodesStorageOciRegistryPullRequest;
}

export interface NodesStorageApiReadStatusRequest {
    node: string;
    storage: string;
}

export interface NodesStorageApiRrdRequest {
    ds: string;
    node: string;
    storage: string;
    timeframe: PveTimeframeEnum;
    cf?: PveCfEnum;
}

export interface NodesStorageApiRrddataRequest {
    node: string;
    storage: string;
    timeframe: PveTimeframeEnum;
    cf?: PveCfEnum;
}

export interface NodesStorageApiUpdateattributesRequest {
    node: string;
    storage: string;
    volume: string;
    nodesStorageUpdateattributesRequest?: NodesStorageUpdateattributesRequest;
}

export interface NodesStorageApiUploadRequest {
    node: string;
    storage: string;
    nodesStorageUploadRequest: NodesStorageUploadRequest;
}

/**
 * 
 */
export class NodesStorageApi extends runtime.BaseAPI {

    /**
     * Creates request options for copy without sending the request
     */
    async copyRequestOpts(requestParameters: NodesStorageApiCopyRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling copy().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling copy().'
            );
        }

        if (requestParameters['volume'] == null) {
            throw new runtime.RequiredError(
                'volume',
                'Required parameter "volume" was null or undefined when calling copy().'
            );
        }

        if (requestParameters['nodesStorageCopyRequest'] == null) {
            throw new runtime.RequiredError(
                'nodesStorageCopyRequest',
                'Required parameter "nodesStorageCopyRequest" was null or undefined when calling copy().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/content/{volume}`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));
        urlPath = urlPath.replace('{volume}', encodeURIComponent(String(requestParameters['volume'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesStorageCopyRequestToJSON(requestParameters['nodesStorageCopyRequest']),
        };
    }

    /**
     * Copy a volume. This is experimental code - do not use.
     * Copy a volume
     */
    async copyRaw(requestParameters: NodesStorageApiCopyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageCopyResponse>> {
        const requestOptions = await this.copyRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageCopyResponseFromJSON(jsonValue));
    }

    /**
     * Copy a volume. This is experimental code - do not use.
     * Copy a volume
     */
    async copy(requestParameters: NodesStorageApiCopyRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageCopyResponse> {
        const response = await this.copyRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for createContent without sending the request
     */
    async createContentRequestOpts(requestParameters: NodesStorageApiCreateContentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling createContent().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling createContent().'
            );
        }

        if (requestParameters['nodesStorageCreateContentRequest'] == null) {
            throw new runtime.RequiredError(
                'nodesStorageCreateContentRequest',
                'Required parameter "nodesStorageCreateContentRequest" was null or undefined when calling createContent().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/content`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesStorageCreateContentRequestToJSON(requestParameters['nodesStorageCreateContentRequest']),
        };
    }

    /**
     * Allocate disk images.
     * Allocate disk images
     */
    async createContentRaw(requestParameters: NodesStorageApiCreateContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageCreateContentResponse>> {
        const requestOptions = await this.createContentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageCreateContentResponseFromJSON(jsonValue));
    }

    /**
     * Allocate disk images.
     * Allocate disk images
     */
    async createContent(requestParameters: NodesStorageApiCreateContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageCreateContentResponse> {
        const response = await this.createContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteContent without sending the request
     */
    async deleteContentRequestOpts(requestParameters: NodesStorageApiDeleteContentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling deleteContent().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling deleteContent().'
            );
        }

        if (requestParameters['volume'] == null) {
            throw new runtime.RequiredError(
                'volume',
                'Required parameter "volume" was null or undefined when calling deleteContent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['delay'] != null) {
            queryParameters['delay'] = requestParameters['delay'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/content/{volume}`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));
        urlPath = urlPath.replace('{volume}', encodeURIComponent(String(requestParameters['volume'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Delete volume  Permissions: You need \'Datastore.Allocate\' privilege on the storage (or \'Datastore.AllocateSpace\' for backup volumes if you have VM.Backup privilege on the VM).
     * Delete volume
     */
    async deleteContentRaw(requestParameters: NodesStorageApiDeleteContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageDeleteContentResponse>> {
        const requestOptions = await this.deleteContentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageDeleteContentResponseFromJSON(jsonValue));
    }

    /**
     * Delete volume  Permissions: You need \'Datastore.Allocate\' privilege on the storage (or \'Datastore.AllocateSpace\' for backup volumes if you have VM.Backup privilege on the VM).
     * Delete volume
     */
    async deleteContent(requestParameters: NodesStorageApiDeleteContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageDeleteContentResponse> {
        const response = await this.deleteContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deletePrunebackups without sending the request
     */
    async deletePrunebackupsRequestOpts(requestParameters: NodesStorageApiDeletePrunebackupsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling deletePrunebackups().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling deletePrunebackups().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pruneBackups'] != null) {
            queryParameters['prune-backups'] = requestParameters['pruneBackups'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['vmid'] != null) {
            queryParameters['vmid'] = requestParameters['vmid'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/prunebackups`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Prune backups. Only those using the standard naming scheme are considered.  Permissions: You need the \'Datastore.Allocate\' privilege on the storage (or if a VM ID is specified, \'Datastore.AllocateSpace\' and \'VM.Backup\' for the VM).
     * Prune backups
     */
    async deletePrunebackupsRaw(requestParameters: NodesStorageApiDeletePrunebackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageDeletePrunebackupsResponse>> {
        const requestOptions = await this.deletePrunebackupsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageDeletePrunebackupsResponseFromJSON(jsonValue));
    }

    /**
     * Prune backups. Only those using the standard naming scheme are considered.  Permissions: You need the \'Datastore.Allocate\' privilege on the storage (or if a VM ID is specified, \'Datastore.AllocateSpace\' and \'VM.Backup\' for the VM).
     * Prune backups
     */
    async deletePrunebackups(requestParameters: NodesStorageApiDeletePrunebackupsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageDeletePrunebackupsResponse> {
        const response = await this.deletePrunebackupsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for diridx without sending the request
     */
    async diridxRequestOpts(requestParameters: NodesStorageApiDiridxRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling diridx().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling diridx().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * 
     * diridx
     */
    async diridxRaw(requestParameters: NodesStorageApiDiridxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageDiridxResponse>> {
        const requestOptions = await this.diridxRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageDiridxResponseFromJSON(jsonValue));
    }

    /**
     * 
     * diridx
     */
    async diridx(requestParameters: NodesStorageApiDiridxRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageDiridxResponse> {
        const response = await this.diridxRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for download without sending the request
     */
    async downloadRequestOpts(requestParameters: NodesStorageApiDownloadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['filepath'] == null) {
            throw new runtime.RequiredError(
                'filepath',
                'Required parameter "filepath" was null or undefined when calling download().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling download().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling download().'
            );
        }

        if (requestParameters['volume'] == null) {
            throw new runtime.RequiredError(
                'volume',
                'Required parameter "volume" was null or undefined when calling download().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['filepath'] != null) {
            queryParameters['filepath'] = requestParameters['filepath'];
        }

        if (requestParameters['tar'] != null) {
            queryParameters['tar'] = requestParameters['tar'];
        }

        if (requestParameters['volume'] != null) {
            queryParameters['volume'] = requestParameters['volume'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/file-restore/download`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Extract a file or directory (as zip archive) from a PBS backup.  Permissions: You need read access for the volume.
     * Extract a file or directory (as zip archive) from a PBS backup
     */
    async downloadRaw(requestParameters: NodesStorageApiDownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageDownloadResponse>> {
        const requestOptions = await this.downloadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageDownloadResponseFromJSON(jsonValue));
    }

    /**
     * Extract a file or directory (as zip archive) from a PBS backup.  Permissions: You need read access for the volume.
     * Extract a file or directory (as zip archive) from a PBS backup
     */
    async download(requestParameters: NodesStorageApiDownloadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageDownloadResponse> {
        const response = await this.downloadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for downloadUrl without sending the request
     */
    async downloadUrlRequestOpts(requestParameters: NodesStorageApiDownloadUrlRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling downloadUrl().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling downloadUrl().'
            );
        }

        if (requestParameters['nodesStorageDownloadUrlRequest'] == null) {
            throw new runtime.RequiredError(
                'nodesStorageDownloadUrlRequest',
                'Required parameter "nodesStorageDownloadUrlRequest" was null or undefined when calling downloadUrl().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/download-url`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesStorageDownloadUrlRequestToJSON(requestParameters['nodesStorageDownloadUrlRequest']),
        };
    }

    /**
     * Download templates, ISO images, OVAs and VM images by using an URL.  Permissions: Requires allocation access on the storage and as this allows one to probe the (local!) host network indirectly it also requires one of Sys.Modify on / (for backwards compatibility) or the newer Sys.AccessNetwork privilege on the node.
     * Download templates, ISO images, OVAs and VM images by using an URL
     */
    async downloadUrlRaw(requestParameters: NodesStorageApiDownloadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageDownloadUrlResponse>> {
        const requestOptions = await this.downloadUrlRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageDownloadUrlResponseFromJSON(jsonValue));
    }

    /**
     * Download templates, ISO images, OVAs and VM images by using an URL.  Permissions: Requires allocation access on the storage and as this allows one to probe the (local!) host network indirectly it also requires one of Sys.Modify on / (for backwards compatibility) or the newer Sys.AccessNetwork privilege on the node.
     * Download templates, ISO images, OVAs and VM images by using an URL
     */
    async downloadUrl(requestParameters: NodesStorageApiDownloadUrlRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageDownloadUrlResponse> {
        const response = await this.downloadUrlRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for dryrun without sending the request
     */
    async dryrunRequestOpts(requestParameters: NodesStorageApiDryrunRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling dryrun().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling dryrun().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['pruneBackups'] != null) {
            queryParameters['prune-backups'] = requestParameters['pruneBackups'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        if (requestParameters['vmid'] != null) {
            queryParameters['vmid'] = requestParameters['vmid'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/prunebackups`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get prune information for backups. NOTE: this is only a preview and might not be what a subsequent prune call does if backups are removed/added in the meantime.
     * Get prune information for backups
     */
    async dryrunRaw(requestParameters: NodesStorageApiDryrunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageDryrunResponse>> {
        const requestOptions = await this.dryrunRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageDryrunResponseFromJSON(jsonValue));
    }

    /**
     * Get prune information for backups. NOTE: this is only a preview and might not be what a subsequent prune call does if backups are removed/added in the meantime.
     * Get prune information for backups
     */
    async dryrun(requestParameters: NodesStorageApiDryrunRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageDryrunResponse> {
        const response = await this.dryrunRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getContent without sending the request
     */
    async getContentRequestOpts(requestParameters: NodesStorageApiGetContentRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getContent().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling getContent().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['content'] != null) {
            queryParameters['content'] = requestParameters['content'];
        }

        if (requestParameters['vmid'] != null) {
            queryParameters['vmid'] = requestParameters['vmid'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/content`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List storage content.
     * List storage content
     */
    async getContentRaw(requestParameters: NodesStorageApiGetContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageGetContentResponse>> {
        const requestOptions = await this.getContentRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageGetContentResponseFromJSON(jsonValue));
    }

    /**
     * List storage content.
     * List storage content
     */
    async getContent(requestParameters: NodesStorageApiGetContentRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageGetContentResponse> {
        const response = await this.getContentRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getImportMetadata without sending the request
     */
    async getImportMetadataRequestOpts(requestParameters: NodesStorageApiGetImportMetadataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getImportMetadata().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling getImportMetadata().'
            );
        }

        if (requestParameters['volume'] == null) {
            throw new runtime.RequiredError(
                'volume',
                'Required parameter "volume" was null or undefined when calling getImportMetadata().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['volume'] != null) {
            queryParameters['volume'] = requestParameters['volume'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/import-metadata`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get the base parameters for creating a guest which imports data from a foreign importable guest, like an ESXi VM  Permissions: You need read access for the volume.
     * Get the base parameters for creating a guest which imports data from a foreign importable guest, like an ESXi VM
     */
    async getImportMetadataRaw(requestParameters: NodesStorageApiGetImportMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageGetImportMetadataResponse>> {
        const requestOptions = await this.getImportMetadataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageGetImportMetadataResponseFromJSON(jsonValue));
    }

    /**
     * Get the base parameters for creating a guest which imports data from a foreign importable guest, like an ESXi VM  Permissions: You need read access for the volume.
     * Get the base parameters for creating a guest which imports data from a foreign importable guest, like an ESXi VM
     */
    async getImportMetadata(requestParameters: NodesStorageApiGetImportMetadataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageGetImportMetadataResponse> {
        const response = await this.getImportMetadataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getList without sending the request
     */
    async getListRequestOpts(requestParameters: NodesStorageApiGetListRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['filepath'] == null) {
            throw new runtime.RequiredError(
                'filepath',
                'Required parameter "filepath" was null or undefined when calling getList().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getList().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling getList().'
            );
        }

        if (requestParameters['volume'] == null) {
            throw new runtime.RequiredError(
                'volume',
                'Required parameter "volume" was null or undefined when calling getList().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['filepath'] != null) {
            queryParameters['filepath'] = requestParameters['filepath'];
        }

        if (requestParameters['volume'] != null) {
            queryParameters['volume'] = requestParameters['volume'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/file-restore/list`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * List files and directories for single file restore under the given path.  Permissions: You need read access for the volume.
     * List files and directories for single file restore under the given path
     */
    async getListRaw(requestParameters: NodesStorageApiGetListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageGetListResponse>> {
        const requestOptions = await this.getListRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageGetListResponseFromJSON(jsonValue));
    }

    /**
     * List files and directories for single file restore under the given path.  Permissions: You need read access for the volume.
     * List files and directories for single file restore under the given path
     */
    async getList(requestParameters: NodesStorageApiGetListRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageGetListResponse> {
        const response = await this.getListRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getStorage without sending the request
     */
    async getStorageRequestOpts(requestParameters: NodesStorageApiGetStorageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling getStorage().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['content'] != null) {
            queryParameters['content'] = requestParameters['content'];
        }

        if (requestParameters['enabled'] != null) {
            queryParameters['enabled'] = requestParameters['enabled'];
        }

        if (requestParameters['format'] != null) {
            queryParameters['format'] = requestParameters['format'];
        }

        if (requestParameters['storage'] != null) {
            queryParameters['storage'] = requestParameters['storage'];
        }

        if (requestParameters['target'] != null) {
            queryParameters['target'] = requestParameters['target'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get status for all datastores.  Permissions: Only list entries where you have \'Datastore.Audit\' or \'Datastore.AllocateSpace\' permissions on \'/storage/<storage>\'
     * Get status for all datastores
     */
    async getStorageRaw(requestParameters: NodesStorageApiGetStorageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageGetStorageResponse>> {
        const requestOptions = await this.getStorageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageGetStorageResponseFromJSON(jsonValue));
    }

    /**
     * Get status for all datastores.  Permissions: Only list entries where you have \'Datastore.Audit\' or \'Datastore.AllocateSpace\' permissions on \'/storage/<storage>\'
     * Get status for all datastores
     */
    async getStorage(requestParameters: NodesStorageApiGetStorageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageGetStorageResponse> {
        const response = await this.getStorageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for info without sending the request
     */
    async infoRequestOpts(requestParameters: NodesStorageApiInfoRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling info().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling info().'
            );
        }

        if (requestParameters['volume'] == null) {
            throw new runtime.RequiredError(
                'volume',
                'Required parameter "volume" was null or undefined when calling info().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/content/{volume}`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));
        urlPath = urlPath.replace('{volume}', encodeURIComponent(String(requestParameters['volume'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Get volume attributes  Permissions: You need read access for the volume.
     * Get volume attributes
     */
    async infoRaw(requestParameters: NodesStorageApiInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageInfoResponse>> {
        const requestOptions = await this.infoRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageInfoResponseFromJSON(jsonValue));
    }

    /**
     * Get volume attributes  Permissions: You need read access for the volume.
     * Get volume attributes
     */
    async info(requestParameters: NodesStorageApiInfoRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageInfoResponse> {
        const response = await this.infoRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for ociRegistryPull without sending the request
     */
    async ociRegistryPullRequestOpts(requestParameters: NodesStorageApiOciRegistryPullRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling ociRegistryPull().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling ociRegistryPull().'
            );
        }

        if (requestParameters['nodesStorageOciRegistryPullRequest'] == null) {
            throw new runtime.RequiredError(
                'nodesStorageOciRegistryPullRequest',
                'Required parameter "nodesStorageOciRegistryPullRequest" was null or undefined when calling ociRegistryPull().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/oci-registry-pull`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesStorageOciRegistryPullRequestToJSON(requestParameters['nodesStorageOciRegistryPullRequest']),
        };
    }

    /**
     * Pull an OCI image from a registry.
     * Pull an OCI image from a registry
     */
    async ociRegistryPullRaw(requestParameters: NodesStorageApiOciRegistryPullRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageOciRegistryPullResponse>> {
        const requestOptions = await this.ociRegistryPullRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageOciRegistryPullResponseFromJSON(jsonValue));
    }

    /**
     * Pull an OCI image from a registry.
     * Pull an OCI image from a registry
     */
    async ociRegistryPull(requestParameters: NodesStorageApiOciRegistryPullRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageOciRegistryPullResponse> {
        const response = await this.ociRegistryPullRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for readStatus without sending the request
     */
    async readStatusRequestOpts(requestParameters: NodesStorageApiReadStatusRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling readStatus().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling readStatus().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/status`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read storage status.
     * Read storage status
     */
    async readStatusRaw(requestParameters: NodesStorageApiReadStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageReadStatusResponse>> {
        const requestOptions = await this.readStatusRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageReadStatusResponseFromJSON(jsonValue));
    }

    /**
     * Read storage status.
     * Read storage status
     */
    async readStatus(requestParameters: NodesStorageApiReadStatusRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageReadStatusResponse> {
        const response = await this.readStatusRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rrd without sending the request
     */
    async rrdRequestOpts(requestParameters: NodesStorageApiRrdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['ds'] == null) {
            throw new runtime.RequiredError(
                'ds',
                'Required parameter "ds" was null or undefined when calling rrd().'
            );
        }

        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling rrd().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling rrd().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling rrd().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cf'] != null) {
            queryParameters['cf'] = requestParameters['cf'];
        }

        if (requestParameters['ds'] != null) {
            queryParameters['ds'] = requestParameters['ds'];
        }

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/rrd`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read storage RRD statistics (returns PNG).
     * Read storage RRD statistics (returns PNG)
     */
    async rrdRaw(requestParameters: NodesStorageApiRrdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageRrdResponse>> {
        const requestOptions = await this.rrdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageRrdResponseFromJSON(jsonValue));
    }

    /**
     * Read storage RRD statistics (returns PNG).
     * Read storage RRD statistics (returns PNG)
     */
    async rrd(requestParameters: NodesStorageApiRrdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageRrdResponse> {
        const response = await this.rrdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for rrddata without sending the request
     */
    async rrddataRequestOpts(requestParameters: NodesStorageApiRrddataRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling rrddata().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling rrddata().'
            );
        }

        if (requestParameters['timeframe'] == null) {
            throw new runtime.RequiredError(
                'timeframe',
                'Required parameter "timeframe" was null or undefined when calling rrddata().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cf'] != null) {
            queryParameters['cf'] = requestParameters['cf'];
        }

        if (requestParameters['timeframe'] != null) {
            queryParameters['timeframe'] = requestParameters['timeframe'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/rrddata`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Read storage RRD statistics.
     * Read storage RRD statistics
     */
    async rrddataRaw(requestParameters: NodesStorageApiRrddataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageRrddataResponse>> {
        const requestOptions = await this.rrddataRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageRrddataResponseFromJSON(jsonValue));
    }

    /**
     * Read storage RRD statistics.
     * Read storage RRD statistics
     */
    async rrddata(requestParameters: NodesStorageApiRrddataRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageRrddataResponse> {
        const response = await this.rrddataRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateattributes without sending the request
     */
    async updateattributesRequestOpts(requestParameters: NodesStorageApiUpdateattributesRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling updateattributes().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling updateattributes().'
            );
        }

        if (requestParameters['volume'] == null) {
            throw new runtime.RequiredError(
                'volume',
                'Required parameter "volume" was null or undefined when calling updateattributes().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/content/{volume}`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));
        urlPath = urlPath.replace('{volume}', encodeURIComponent(String(requestParameters['volume'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: NodesStorageUpdateattributesRequestToJSON(requestParameters['nodesStorageUpdateattributesRequest']),
        };
    }

    /**
     * Update volume attributes  Permissions: You need read access for the volume.
     * Update volume attributes
     */
    async updateattributesRaw(requestParameters: NodesStorageApiUpdateattributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageUpdateattributesResponse>> {
        const requestOptions = await this.updateattributesRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageUpdateattributesResponseFromJSON(jsonValue));
    }

    /**
     * Update volume attributes  Permissions: You need read access for the volume.
     * Update volume attributes
     */
    async updateattributes(requestParameters: NodesStorageApiUpdateattributesRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageUpdateattributesResponse> {
        const response = await this.updateattributesRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for upload without sending the request
     */
    async uploadRequestOpts(requestParameters: NodesStorageApiUploadRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['node'] == null) {
            throw new runtime.RequiredError(
                'node',
                'Required parameter "node" was null or undefined when calling upload().'
            );
        }

        if (requestParameters['storage'] == null) {
            throw new runtime.RequiredError(
                'storage',
                'Required parameter "storage" was null or undefined when calling upload().'
            );
        }

        if (requestParameters['nodesStorageUploadRequest'] == null) {
            throw new runtime.RequiredError(
                'nodesStorageUploadRequest',
                'Required parameter "nodesStorageUploadRequest" was null or undefined when calling upload().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // PVEApiToken authentication
        }

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["CSRFPreventionToken"] = await this.configuration.apiKey("CSRFPreventionToken"); // CSRFPreventionToken authentication
        }


        let urlPath = `/nodes/{node}/storage/{storage}/upload`;
        urlPath = urlPath.replace('{node}', encodeURIComponent(String(requestParameters['node'])));
        urlPath = urlPath.replace('{storage}', encodeURIComponent(String(requestParameters['storage'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NodesStorageUploadRequestToJSON(requestParameters['nodesStorageUploadRequest']),
        };
    }

    /**
     * Upload templates, ISO images, OVAs and VM images.
     * Upload templates, ISO images, OVAs and VM images
     */
    async uploadRaw(requestParameters: NodesStorageApiUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NodesStorageUploadResponse>> {
        const requestOptions = await this.uploadRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NodesStorageUploadResponseFromJSON(jsonValue));
    }

    /**
     * Upload templates, ISO images, OVAs and VM images.
     * Upload templates, ISO images, OVAs and VM images
     */
    async upload(requestParameters: NodesStorageApiUploadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NodesStorageUploadResponse> {
        const response = await this.uploadRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
