/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessDomainsCreateDomainsResponse
 */
export interface AccessDomainsCreateDomainsResponse {

    /**
     * 
     * @type {any}
     * @memberof AccessDomainsCreateDomainsResponse
     */
    data: any | null;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof AccessDomainsCreateDomainsResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof AccessDomainsCreateDomainsResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the AccessDomainsCreateDomainsResponse interface.
 */
export function instanceOfAccessDomainsCreateDomainsResponse(value: object): value is AccessDomainsCreateDomainsResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function AccessDomainsCreateDomainsResponseFromJSON(json: any): AccessDomainsCreateDomainsResponse {
    return AccessDomainsCreateDomainsResponseFromJSONTyped(json, false);
}

export function AccessDomainsCreateDomainsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessDomainsCreateDomainsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function AccessDomainsCreateDomainsResponseToJSON(json: any): AccessDomainsCreateDomainsResponse {
    return AccessDomainsCreateDomainsResponseToJSONTyped(json, false);
}

export function AccessDomainsCreateDomainsResponseToJSONTyped(value?: AccessDomainsCreateDomainsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

