/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';
import type { PveScopeEnum } from './PveScopeEnum';
import {
    PveScopeEnumFromJSON,
    PveScopeEnumFromJSONTyped,
    PveScopeEnumToJSON,
    PveScopeEnumToJSONTyped,
} from './PveScopeEnum';

/**
 * 
 * @export
 * @interface AccessDomainsSyncRequest
 */
export interface AccessDomainsSyncRequest {

    /**
     * If set, does not write anything.
     * @type {PveBoolean}
     * @memberof AccessDomainsSyncRequest
     */
    dryRun?: PveBoolean;

    /**
     * Enable newly synced users immediately.
     * @type {PveBoolean}
     * @memberof AccessDomainsSyncRequest
     */
    enableNew: PveBoolean;

    /**
     * DEPRECATED: use 'remove-vanished' instead. If set, uses the LDAP Directory as source of truth, deleting users or groups not returned from the sync and removing all locally modified properties of synced users. If not set, only syncs information which is present in the synced data, and does not delete or modify anything else.
     * @type {PveBoolean}
     * @memberof AccessDomainsSyncRequest
     */
    full: PveBoolean;

    /**
     * DEPRECATED: use 'remove-vanished' instead. Remove ACLs for users or groups which were removed from the config during a sync.
     * @type {PveBoolean}
     * @memberof AccessDomainsSyncRequest
     */
    purge: PveBoolean;

    /**
     * A semicolon-separated list of things to remove when they or the user vanishes during a sync. The following values are possible: 'entry' removes the user/group when not returned from the sync. 'properties' removes the set properties on existing user/group that do not appear in the source (even custom ones). 'acl' removes acls when the user/group is not returned from the sync. Instead of a list it also can be 'none' (the default).
     * @type {string}
     * @memberof AccessDomainsSyncRequest
     */
    removeVanished: string;

    /**
     * Select what to sync.
     * @type {PveScopeEnum}
     * @memberof AccessDomainsSyncRequest
     */
    scope: PveScopeEnum;

}



/**
 * Check if a given object implements the AccessDomainsSyncRequest interface.
 */
export function instanceOfAccessDomainsSyncRequest(value: object): value is AccessDomainsSyncRequest {
    
    
    if (!('enableNew' in value) || value['enableNew'] === undefined) return false;
    
    if (!('full' in value) || value['full'] === undefined) return false;
    
    if (!('purge' in value) || value['purge'] === undefined) return false;
    
    if (!('removeVanished' in value) || value['removeVanished'] === undefined) return false;
    
    if (!('scope' in value) || value['scope'] === undefined) return false;
    
    return true;
}

export function AccessDomainsSyncRequestFromJSON(json: any): AccessDomainsSyncRequest {
    return AccessDomainsSyncRequestFromJSONTyped(json, false);
}

export function AccessDomainsSyncRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessDomainsSyncRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'dryRun': json['dry-run'] == null ? undefined : PveBooleanFromJSON(json['dry-run']),
        
        'enableNew': PveBooleanFromJSON(json['enable-new']),
        
        'full': PveBooleanFromJSON(json['full']),
        
        'purge': PveBooleanFromJSON(json['purge']),
        
        'removeVanished': json['remove-vanished'],
        
        'scope': PveScopeEnumFromJSON(json['scope']),
        
    };
}

export function AccessDomainsSyncRequestToJSON(json: any): AccessDomainsSyncRequest {
    return AccessDomainsSyncRequestToJSONTyped(json, false);
}

export function AccessDomainsSyncRequestToJSONTyped(value?: AccessDomainsSyncRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'dry-run': PveBooleanToJSON(value['dryRun']),
        
        'enable-new': PveBooleanToJSON(value['enableNew']),
        
        'full': PveBooleanToJSON(value['full']),
        
        'purge': PveBooleanToJSON(value['purge']),
        
        'remove-vanished': value['removeVanished'],
        
        'scope': PveScopeEnumToJSON(value['scope']),
        
    };
}

