/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessUsersGenerateTokenResponseData } from './AccessUsersGenerateTokenResponseData';
import {
    AccessUsersGenerateTokenResponseDataFromJSON,
    AccessUsersGenerateTokenResponseDataFromJSONTyped,
    AccessUsersGenerateTokenResponseDataToJSON,
    AccessUsersGenerateTokenResponseDataToJSONTyped,
} from './AccessUsersGenerateTokenResponseData';

/**
 * 
 * @export
 * @interface AccessUsersGenerateTokenResponse
 */
export interface AccessUsersGenerateTokenResponse {

    /**
     * 
     * @type {AccessUsersGenerateTokenResponseData}
     * @memberof AccessUsersGenerateTokenResponse
     */
    data: AccessUsersGenerateTokenResponseData;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof AccessUsersGenerateTokenResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof AccessUsersGenerateTokenResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the AccessUsersGenerateTokenResponse interface.
 */
export function instanceOfAccessUsersGenerateTokenResponse(value: object): value is AccessUsersGenerateTokenResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function AccessUsersGenerateTokenResponseFromJSON(json: any): AccessUsersGenerateTokenResponse {
    return AccessUsersGenerateTokenResponseFromJSONTyped(json, false);
}

export function AccessUsersGenerateTokenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessUsersGenerateTokenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': AccessUsersGenerateTokenResponseDataFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function AccessUsersGenerateTokenResponseToJSON(json: any): AccessUsersGenerateTokenResponse {
    return AccessUsersGenerateTokenResponseToJSONTyped(json, false);
}

export function AccessUsersGenerateTokenResponseToJSONTyped(value?: AccessUsersGenerateTokenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': AccessUsersGenerateTokenResponseDataToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

