/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessGroupsReadGroupResponseData } from './AccessGroupsReadGroupResponseData';
import {
    AccessGroupsReadGroupResponseDataFromJSON,
    AccessGroupsReadGroupResponseDataFromJSONTyped,
    AccessGroupsReadGroupResponseDataToJSON,
    AccessGroupsReadGroupResponseDataToJSONTyped,
} from './AccessGroupsReadGroupResponseData';

/**
 * 
 * @export
 * @interface AccessGroupsReadGroupResponse
 */
export interface AccessGroupsReadGroupResponse {

    /**
     * 
     * @type {AccessGroupsReadGroupResponseData}
     * @memberof AccessGroupsReadGroupResponse
     */
    data: AccessGroupsReadGroupResponseData;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof AccessGroupsReadGroupResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof AccessGroupsReadGroupResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the AccessGroupsReadGroupResponse interface.
 */
export function instanceOfAccessGroupsReadGroupResponse(value: object): value is AccessGroupsReadGroupResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function AccessGroupsReadGroupResponseFromJSON(json: any): AccessGroupsReadGroupResponse {
    return AccessGroupsReadGroupResponseFromJSONTyped(json, false);
}

export function AccessGroupsReadGroupResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessGroupsReadGroupResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': AccessGroupsReadGroupResponseDataFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function AccessGroupsReadGroupResponseToJSON(json: any): AccessGroupsReadGroupResponse {
    return AccessGroupsReadGroupResponseToJSONTyped(json, false);
}

export function AccessGroupsReadGroupResponseToJSONTyped(value?: AccessGroupsReadGroupResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': AccessGroupsReadGroupResponseDataToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

