/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AccessGroupsReadGroupResponseData
 */
export interface AccessGroupsReadGroupResponseData {

    /**
     * 
     * @type {string}
     * @memberof AccessGroupsReadGroupResponseData
     */
    comment?: string;

    /**
     * 
     * @type {Array<string>}
     * @memberof AccessGroupsReadGroupResponseData
     */
    members: Array<string>;

}

/**
 * Check if a given object implements the AccessGroupsReadGroupResponseData interface.
 */
export function instanceOfAccessGroupsReadGroupResponseData(value: object): value is AccessGroupsReadGroupResponseData {
    
    
    if (!('members' in value) || value['members'] === undefined) return false;
    
    return true;
}

export function AccessGroupsReadGroupResponseDataFromJSON(json: any): AccessGroupsReadGroupResponseData {
    return AccessGroupsReadGroupResponseDataFromJSONTyped(json, false);
}

export function AccessGroupsReadGroupResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessGroupsReadGroupResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        'members': json['members'],
        
    };
}

export function AccessGroupsReadGroupResponseDataToJSON(json: any): AccessGroupsReadGroupResponseData {
    return AccessGroupsReadGroupResponseDataToJSONTyped(json, false);
}

export function AccessGroupsReadGroupResponseDataToJSONTyped(value?: AccessGroupsReadGroupResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'comment': value['comment'],
        
        'members': value['members'],
        
    };
}

