/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClusterHaRelocateResponseDataBlockingResourcesInner } from './ClusterHaRelocateResponseDataBlockingResourcesInner';
import {
    ClusterHaRelocateResponseDataBlockingResourcesInnerFromJSON,
    ClusterHaRelocateResponseDataBlockingResourcesInnerFromJSONTyped,
    ClusterHaRelocateResponseDataBlockingResourcesInnerToJSON,
    ClusterHaRelocateResponseDataBlockingResourcesInnerToJSONTyped,
} from './ClusterHaRelocateResponseDataBlockingResourcesInner';

/**
 * 
 * @export
 * @interface ClusterHaRelocateResponseData
 */
export interface ClusterHaRelocateResponseData {

    /**
     * HA resources, which are blocking the given HA resource from being relocated to the requested target node.
     * @type {Array<ClusterHaRelocateResponseDataBlockingResourcesInner>}
     * @memberof ClusterHaRelocateResponseData
     */
    blockingResources?: Array<ClusterHaRelocateResponseDataBlockingResourcesInner>;

    /**
     * HA resources, which are relocated to the same requested target node as the given HA resource, because these are in positive affinity with the HA resource.
     * @type {Array<string>}
     * @memberof ClusterHaRelocateResponseData
     */
    comigratedResources?: Array<string>;

    /**
     * Node, which was requested to be relocated to.
     * @type {string}
     * @memberof ClusterHaRelocateResponseData
     */
    requestedNode: string;

    /**
     * HA resource, which is requested to be relocated.
     * @type {string}
     * @memberof ClusterHaRelocateResponseData
     */
    sid: string;

}

/**
 * Check if a given object implements the ClusterHaRelocateResponseData interface.
 */
export function instanceOfClusterHaRelocateResponseData(value: object): value is ClusterHaRelocateResponseData {
    
    
    
    if (!('requestedNode' in value) || value['requestedNode'] === undefined) return false;
    
    if (!('sid' in value) || value['sid'] === undefined) return false;
    
    return true;
}

export function ClusterHaRelocateResponseDataFromJSON(json: any): ClusterHaRelocateResponseData {
    return ClusterHaRelocateResponseDataFromJSONTyped(json, false);
}

export function ClusterHaRelocateResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterHaRelocateResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        
        'blockingResources': json['blocking-resources'] == null ? undefined : ((json['blocking-resources'] as Array<any>).map(ClusterHaRelocateResponseDataBlockingResourcesInnerFromJSON)),
        
        'comigratedResources': json['comigrated-resources'] == null ? undefined : json['comigrated-resources'],
        
        'requestedNode': json['requested-node'],
        
        'sid': json['sid'],
        
    };
}

export function ClusterHaRelocateResponseDataToJSON(json: any): ClusterHaRelocateResponseData {
    return ClusterHaRelocateResponseDataToJSONTyped(json, false);
}

export function ClusterHaRelocateResponseDataToJSONTyped(value?: ClusterHaRelocateResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'blocking-resources': value['blockingResources'] == null ? undefined : ((value['blockingResources'] as Array<any>).map(ClusterHaRelocateResponseDataBlockingResourcesInnerToJSON)),
        
        'comigrated-resources': value['comigratedResources'],
        
        'requested-node': value['requestedNode'],
        
        'sid': value['sid'],
        
    };
}

