/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClusterAcmeGetDirectoriesResponseDataInner } from './ClusterAcmeGetDirectoriesResponseDataInner';
import {
    ClusterAcmeGetDirectoriesResponseDataInnerFromJSON,
    ClusterAcmeGetDirectoriesResponseDataInnerFromJSONTyped,
    ClusterAcmeGetDirectoriesResponseDataInnerToJSON,
    ClusterAcmeGetDirectoriesResponseDataInnerToJSONTyped,
} from './ClusterAcmeGetDirectoriesResponseDataInner';

/**
 * 
 * @export
 * @interface ClusterAcmeGetDirectoriesResponse
 */
export interface ClusterAcmeGetDirectoriesResponse {

    /**
     * 
     * @type {Array<ClusterAcmeGetDirectoriesResponseDataInner>}
     * @memberof ClusterAcmeGetDirectoriesResponse
     */
    data: Array<ClusterAcmeGetDirectoriesResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ClusterAcmeGetDirectoriesResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ClusterAcmeGetDirectoriesResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ClusterAcmeGetDirectoriesResponse interface.
 */
export function instanceOfClusterAcmeGetDirectoriesResponse(value: object): value is ClusterAcmeGetDirectoriesResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ClusterAcmeGetDirectoriesResponseFromJSON(json: any): ClusterAcmeGetDirectoriesResponse {
    return ClusterAcmeGetDirectoriesResponseFromJSONTyped(json, false);
}

export function ClusterAcmeGetDirectoriesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterAcmeGetDirectoriesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ClusterAcmeGetDirectoriesResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ClusterAcmeGetDirectoriesResponseToJSON(json: any): ClusterAcmeGetDirectoriesResponse {
    return ClusterAcmeGetDirectoriesResponseToJSONTyped(json, false);
}

export function ClusterAcmeGetDirectoriesResponseToJSONTyped(value?: ClusterAcmeGetDirectoriesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ClusterAcmeGetDirectoriesResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

