/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PveSdnZoneEvpnConfig } from './PveSdnZoneEvpnConfig';
import {
    instanceOfPveSdnZoneEvpnConfig,
    PveSdnZoneEvpnConfigFromJSON,
    PveSdnZoneEvpnConfigFromJSONTyped,
    PveSdnZoneEvpnConfigToJSON,
} from './PveSdnZoneEvpnConfig';
import type { PveSdnZoneFaucetConfig } from './PveSdnZoneFaucetConfig';
import {
    instanceOfPveSdnZoneFaucetConfig,
    PveSdnZoneFaucetConfigFromJSON,
    PveSdnZoneFaucetConfigFromJSONTyped,
    PveSdnZoneFaucetConfigToJSON,
} from './PveSdnZoneFaucetConfig';
import type { PveSdnZoneQinqConfig } from './PveSdnZoneQinqConfig';
import {
    instanceOfPveSdnZoneQinqConfig,
    PveSdnZoneQinqConfigFromJSON,
    PveSdnZoneQinqConfigFromJSONTyped,
    PveSdnZoneQinqConfigToJSON,
} from './PveSdnZoneQinqConfig';
import type { PveSdnZoneSimpleConfig } from './PveSdnZoneSimpleConfig';
import {
    instanceOfPveSdnZoneSimpleConfig,
    PveSdnZoneSimpleConfigFromJSON,
    PveSdnZoneSimpleConfigFromJSONTyped,
    PveSdnZoneSimpleConfigToJSON,
} from './PveSdnZoneSimpleConfig';
import type { PveSdnZoneVlanConfig } from './PveSdnZoneVlanConfig';
import {
    instanceOfPveSdnZoneVlanConfig,
    PveSdnZoneVlanConfigFromJSON,
    PveSdnZoneVlanConfigFromJSONTyped,
    PveSdnZoneVlanConfigToJSON,
} from './PveSdnZoneVlanConfig';
import type { PveSdnZoneVxlanConfig } from './PveSdnZoneVxlanConfig';
import {
    instanceOfPveSdnZoneVxlanConfig,
    PveSdnZoneVxlanConfigFromJSON,
    PveSdnZoneVxlanConfigFromJSONTyped,
    PveSdnZoneVxlanConfigToJSON,
} from './PveSdnZoneVxlanConfig';

/**
 * @type ClusterSdnCreateZonesRequest
 * 
 * @export
 */
export type ClusterSdnCreateZonesRequest = { type: 'evpn' } & PveSdnZoneEvpnConfig | { type: 'faucet' } & PveSdnZoneFaucetConfig | { type: 'qinq' } & PveSdnZoneQinqConfig | { type: 'simple' } & PveSdnZoneSimpleConfig | { type: 'vlan' } & PveSdnZoneVlanConfig | { type: 'vxlan' } & PveSdnZoneVxlanConfig;

export function ClusterSdnCreateZonesRequestFromJSON(json: any): ClusterSdnCreateZonesRequest {
    return ClusterSdnCreateZonesRequestFromJSONTyped(json, false);
}

export function ClusterSdnCreateZonesRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterSdnCreateZonesRequest {
    if (json == null) {
        return json;
    }
    switch (json['type']) {
        case 'evpn':
            return Object.assign({}, PveSdnZoneEvpnConfigFromJSONTyped(json, true), { type: 'evpn' } as const);
        case 'faucet':
            return Object.assign({}, PveSdnZoneFaucetConfigFromJSONTyped(json, true), { type: 'faucet' } as const);
        case 'qinq':
            return Object.assign({}, PveSdnZoneQinqConfigFromJSONTyped(json, true), { type: 'qinq' } as const);
        case 'simple':
            return Object.assign({}, PveSdnZoneSimpleConfigFromJSONTyped(json, true), { type: 'simple' } as const);
        case 'vlan':
            return Object.assign({}, PveSdnZoneVlanConfigFromJSONTyped(json, true), { type: 'vlan' } as const);
        case 'vxlan':
            return Object.assign({}, PveSdnZoneVxlanConfigFromJSONTyped(json, true), { type: 'vxlan' } as const);
        default:
            return json;
    }
}

export function ClusterSdnCreateZonesRequestToJSON(json: any): any {
    return ClusterSdnCreateZonesRequestToJSONTyped(json, false);
}

export function ClusterSdnCreateZonesRequestToJSONTyped(value?: ClusterSdnCreateZonesRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['type']) {
        case 'evpn':
            return Object.assign({}, PveSdnZoneEvpnConfigToJSON(value), { type: 'evpn' } as const);
        case 'faucet':
            return Object.assign({}, PveSdnZoneFaucetConfigToJSON(value), { type: 'faucet' } as const);
        case 'qinq':
            return Object.assign({}, PveSdnZoneQinqConfigToJSON(value), { type: 'qinq' } as const);
        case 'simple':
            return Object.assign({}, PveSdnZoneSimpleConfigToJSON(value), { type: 'simple' } as const);
        case 'vlan':
            return Object.assign({}, PveSdnZoneVlanConfigToJSON(value), { type: 'vlan' } as const);
        case 'vxlan':
            return Object.assign({}, PveSdnZoneVxlanConfigToJSON(value), { type: 'vxlan' } as const);
        default:
            return value;
    }
}

