/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClusterFirewallGetIpsetResponseDataInner } from './ClusterFirewallGetIpsetResponseDataInner';
import {
    ClusterFirewallGetIpsetResponseDataInnerFromJSON,
    ClusterFirewallGetIpsetResponseDataInnerFromJSONTyped,
    ClusterFirewallGetIpsetResponseDataInnerToJSON,
    ClusterFirewallGetIpsetResponseDataInnerToJSONTyped,
} from './ClusterFirewallGetIpsetResponseDataInner';

/**
 * 
 * @export
 * @interface ClusterFirewallGetIpsetResponse
 */
export interface ClusterFirewallGetIpsetResponse {

    /**
     * 
     * @type {Array<ClusterFirewallGetIpsetResponseDataInner>}
     * @memberof ClusterFirewallGetIpsetResponse
     */
    data: Array<ClusterFirewallGetIpsetResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ClusterFirewallGetIpsetResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ClusterFirewallGetIpsetResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ClusterFirewallGetIpsetResponse interface.
 */
export function instanceOfClusterFirewallGetIpsetResponse(value: object): value is ClusterFirewallGetIpsetResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ClusterFirewallGetIpsetResponseFromJSON(json: any): ClusterFirewallGetIpsetResponse {
    return ClusterFirewallGetIpsetResponseFromJSONTyped(json, false);
}

export function ClusterFirewallGetIpsetResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterFirewallGetIpsetResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ClusterFirewallGetIpsetResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ClusterFirewallGetIpsetResponseToJSON(json: any): ClusterFirewallGetIpsetResponse {
    return ClusterFirewallGetIpsetResponseToJSONTyped(json, false);
}

export function ClusterFirewallGetIpsetResponseToJSONTyped(value?: ClusterFirewallGetIpsetResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ClusterFirewallGetIpsetResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

