/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';

/**
 * Changes that have not yet been applied to the running configuration.
 * @export
 * @interface ClusterSdnGetControllersResponseDataInnerPending
 */
export interface ClusterSdnGetControllersResponseDataInnerPending {

    /**
     * The local ASN of the controller. BGP & EVPN only.
     * @type {number}
     * @memberof ClusterSdnGetControllersResponseDataInnerPending
     */
    asn?: number;

    /**
     * Consider different AS paths of equal length for multipath computation. BGP only.
     * @type {PveBoolean}
     * @memberof ClusterSdnGetControllersResponseDataInnerPending
     */
    bgpMultipathAsRelax?: PveBoolean;

    /**
     * Enable eBGP (remote-as external). BGP only.
     * @type {PveBoolean}
     * @memberof ClusterSdnGetControllersResponseDataInnerPending
     */
    ebgp?: PveBoolean;

    /**
     * Set maximum amount of hops for eBGP peers. Needs ebgp set to 1. BGP only.
     * @type {number}
     * @memberof ClusterSdnGetControllersResponseDataInnerPending
     */
    ebgpMultihop?: number;

    /**
     * Name of the IS-IS domain. IS-IS only.
     * @type {string}
     * @memberof ClusterSdnGetControllersResponseDataInnerPending
     */
    isisDomain?: string;

    /**
     * Comma-separated list of interfaces where IS-IS should be active. IS-IS only.
     * @type {string}
     * @memberof ClusterSdnGetControllersResponseDataInnerPending
     */
    isisIfaces?: string;

    /**
     * Network Entity title for this node in the IS-IS network. IS-IS only.
     * @type {string}
     * @memberof ClusterSdnGetControllersResponseDataInnerPending
     */
    isisNet?: string;

    /**
     * Name of the loopback/dummy interface that provides the Router-IP. BGP only.
     * @type {string}
     * @memberof ClusterSdnGetControllersResponseDataInnerPending
     */
    loopback?: string;

    /**
     * Node(s) where this controller is active.
     * @type {string}
     * @memberof ClusterSdnGetControllersResponseDataInnerPending
     */
    node?: string;

    /**
     * Comma-separated list of the peers IP addresses.
     * @type {string}
     * @memberof ClusterSdnGetControllersResponseDataInnerPending
     */
    peers?: string;

}



/**
 * Check if a given object implements the ClusterSdnGetControllersResponseDataInnerPending interface.
 */
export function instanceOfClusterSdnGetControllersResponseDataInnerPending(value: object): value is ClusterSdnGetControllersResponseDataInnerPending {
    
    
    
    
    
    
    
    
    
    
    
    return true;
}

export function ClusterSdnGetControllersResponseDataInnerPendingFromJSON(json: any): ClusterSdnGetControllersResponseDataInnerPending {
    return ClusterSdnGetControllersResponseDataInnerPendingFromJSONTyped(json, false);
}

export function ClusterSdnGetControllersResponseDataInnerPendingFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterSdnGetControllersResponseDataInnerPending {
    if (json == null) {
        return json;
    }
    return {
        
        
        'asn': json['asn'] == null ? undefined : json['asn'],
        
        'bgpMultipathAsRelax': json['bgp-multipath-as-relax'] == null ? undefined : PveBooleanFromJSON(json['bgp-multipath-as-relax']),
        
        'ebgp': json['ebgp'] == null ? undefined : PveBooleanFromJSON(json['ebgp']),
        
        'ebgpMultihop': json['ebgp-multihop'] == null ? undefined : json['ebgp-multihop'],
        
        'isisDomain': json['isis-domain'] == null ? undefined : json['isis-domain'],
        
        'isisIfaces': json['isis-ifaces'] == null ? undefined : json['isis-ifaces'],
        
        'isisNet': json['isis-net'] == null ? undefined : json['isis-net'],
        
        'loopback': json['loopback'] == null ? undefined : json['loopback'],
        
        'node': json['node'] == null ? undefined : json['node'],
        
        'peers': json['peers'] == null ? undefined : json['peers'],
        
    };
}

export function ClusterSdnGetControllersResponseDataInnerPendingToJSON(json: any): ClusterSdnGetControllersResponseDataInnerPending {
    return ClusterSdnGetControllersResponseDataInnerPendingToJSONTyped(json, false);
}

export function ClusterSdnGetControllersResponseDataInnerPendingToJSONTyped(value?: ClusterSdnGetControllersResponseDataInnerPending | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'asn': value['asn'],
        
        'bgp-multipath-as-relax': PveBooleanToJSON(value['bgpMultipathAsRelax']),
        
        'ebgp': PveBooleanToJSON(value['ebgp']),
        
        'ebgp-multihop': value['ebgpMultihop'],
        
        'isis-domain': value['isisDomain'],
        
        'isis-ifaces': value['isisIfaces'],
        
        'isis-net': value['isisNet'],
        
        'loopback': value['loopback'],
        
        'node': value['node'],
        
        'peers': value['peers'],
        
    };
}

