/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClusterFirewallGetMacrosResponseDataInner } from './ClusterFirewallGetMacrosResponseDataInner';
import {
    ClusterFirewallGetMacrosResponseDataInnerFromJSON,
    ClusterFirewallGetMacrosResponseDataInnerFromJSONTyped,
    ClusterFirewallGetMacrosResponseDataInnerToJSON,
    ClusterFirewallGetMacrosResponseDataInnerToJSONTyped,
} from './ClusterFirewallGetMacrosResponseDataInner';

/**
 * 
 * @export
 * @interface ClusterFirewallGetMacrosResponse
 */
export interface ClusterFirewallGetMacrosResponse {

    /**
     * 
     * @type {Array<ClusterFirewallGetMacrosResponseDataInner>}
     * @memberof ClusterFirewallGetMacrosResponse
     */
    data: Array<ClusterFirewallGetMacrosResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ClusterFirewallGetMacrosResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ClusterFirewallGetMacrosResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ClusterFirewallGetMacrosResponse interface.
 */
export function instanceOfClusterFirewallGetMacrosResponse(value: object): value is ClusterFirewallGetMacrosResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ClusterFirewallGetMacrosResponseFromJSON(json: any): ClusterFirewallGetMacrosResponse {
    return ClusterFirewallGetMacrosResponseFromJSONTyped(json, false);
}

export function ClusterFirewallGetMacrosResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterFirewallGetMacrosResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ClusterFirewallGetMacrosResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ClusterFirewallGetMacrosResponseToJSON(json: any): ClusterFirewallGetMacrosResponse {
    return ClusterFirewallGetMacrosResponseToJSONTyped(json, false);
}

export function ClusterFirewallGetMacrosResponseToJSONTyped(value?: ClusterFirewallGetMacrosResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ClusterFirewallGetMacrosResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

