/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';
import type { PveClusterSdnTypeEnum } from './PveClusterSdnTypeEnum';
import {
    PveClusterSdnTypeEnumFromJSON,
    PveClusterSdnTypeEnumFromJSONTyped,
    PveClusterSdnTypeEnumToJSON,
    PveClusterSdnTypeEnumToJSONTyped,
} from './PveClusterSdnTypeEnum';
import type { PveClusterSdnStateEnum } from './PveClusterSdnStateEnum';
import {
    PveClusterSdnStateEnumFromJSON,
    PveClusterSdnStateEnumFromJSONTyped,
    PveClusterSdnStateEnumToJSON,
    PveClusterSdnStateEnumToJSONTyped,
} from './PveClusterSdnStateEnum';
import type { ClusterSdnGetControllersResponseDataInnerPending } from './ClusterSdnGetControllersResponseDataInnerPending';
import {
    ClusterSdnGetControllersResponseDataInnerPendingFromJSON,
    ClusterSdnGetControllersResponseDataInnerPendingFromJSONTyped,
    ClusterSdnGetControllersResponseDataInnerPendingToJSON,
    ClusterSdnGetControllersResponseDataInnerPendingToJSONTyped,
} from './ClusterSdnGetControllersResponseDataInnerPending';

/**
 * 
 * @export
 * @interface ClusterSdnGetControllersResponseDataInner
 */
export interface ClusterSdnGetControllersResponseDataInner {

    /**
     * The local ASN of the controller. BGP & EVPN only.
     * @type {number}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    asn?: number;

    /**
     * Consider different AS paths of equal length for multipath computation. BGP only.
     * @type {PveBoolean}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    bgpMultipathAsRelax?: PveBoolean;

    /**
     * Name of the controller.
     * @type {string}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    controller: string;

    /**
     * Digest of the controller section.
     * @type {string}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    digest?: string;

    /**
     * Enable eBGP (remote-as external). BGP only.
     * @type {PveBoolean}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    ebgp?: PveBoolean;

    /**
     * Set maximum amount of hops for eBGP peers. Needs ebgp set to 1. BGP only.
     * @type {number}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    ebgpMultihop?: number;

    /**
     * Name of the IS-IS domain. IS-IS only.
     * @type {string}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    isisDomain?: string;

    /**
     * Comma-separated list of interfaces where IS-IS should be active. IS-IS only.
     * @type {string}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    isisIfaces?: string;

    /**
     * Network Entity title for this node in the IS-IS network. IS-IS only.
     * @type {string}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    isisNet?: string;

    /**
     * Name of the loopback/dummy interface that provides the Router-IP. BGP only.
     * @type {string}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    loopback?: string;

    /**
     * Node(s) where this controller is active.
     * @type {string}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    node?: string;

    /**
     * Comma-separated list of the peers IP addresses.
     * @type {string}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    peers?: string;

    /**
     * 
     * @type {ClusterSdnGetControllersResponseDataInnerPending}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    pending?: ClusterSdnGetControllersResponseDataInnerPending;

    /**
     * State of the SDN configuration object.
     * @type {PveClusterSdnStateEnum}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    state?: PveClusterSdnStateEnum;

    /**
     * Type of the controller
     * @type {PveClusterSdnTypeEnum}
     * @memberof ClusterSdnGetControllersResponseDataInner
     */
    type: PveClusterSdnTypeEnum;

}



/**
 * Check if a given object implements the ClusterSdnGetControllersResponseDataInner interface.
 */
export function instanceOfClusterSdnGetControllersResponseDataInner(value: object): value is ClusterSdnGetControllersResponseDataInner {
    
    
    
    if (!('controller' in value) || value['controller'] === undefined) return false;
    
    
    
    
    
    
    
    
    
    
    
    
    if (!('type' in value) || value['type'] === undefined) return false;
    
    return true;
}

export function ClusterSdnGetControllersResponseDataInnerFromJSON(json: any): ClusterSdnGetControllersResponseDataInner {
    return ClusterSdnGetControllersResponseDataInnerFromJSONTyped(json, false);
}

export function ClusterSdnGetControllersResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterSdnGetControllersResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'asn': json['asn'] == null ? undefined : json['asn'],
        
        'bgpMultipathAsRelax': json['bgp-multipath-as-relax'] == null ? undefined : PveBooleanFromJSON(json['bgp-multipath-as-relax']),
        
        'controller': json['controller'],
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
        'ebgp': json['ebgp'] == null ? undefined : PveBooleanFromJSON(json['ebgp']),
        
        'ebgpMultihop': json['ebgp-multihop'] == null ? undefined : json['ebgp-multihop'],
        
        'isisDomain': json['isis-domain'] == null ? undefined : json['isis-domain'],
        
        'isisIfaces': json['isis-ifaces'] == null ? undefined : json['isis-ifaces'],
        
        'isisNet': json['isis-net'] == null ? undefined : json['isis-net'],
        
        'loopback': json['loopback'] == null ? undefined : json['loopback'],
        
        'node': json['node'] == null ? undefined : json['node'],
        
        'peers': json['peers'] == null ? undefined : json['peers'],
        
        'pending': json['pending'] == null ? undefined : ClusterSdnGetControllersResponseDataInnerPendingFromJSON(json['pending']),
        
        'state': json['state'] == null ? undefined : PveClusterSdnStateEnumFromJSON(json['state']),
        
        'type': PveClusterSdnTypeEnumFromJSON(json['type']),
        
    };
}

export function ClusterSdnGetControllersResponseDataInnerToJSON(json: any): ClusterSdnGetControllersResponseDataInner {
    return ClusterSdnGetControllersResponseDataInnerToJSONTyped(json, false);
}

export function ClusterSdnGetControllersResponseDataInnerToJSONTyped(value?: ClusterSdnGetControllersResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'asn': value['asn'],
        
        'bgp-multipath-as-relax': PveBooleanToJSON(value['bgpMultipathAsRelax']),
        
        'controller': value['controller'],
        
        'digest': value['digest'],
        
        'ebgp': PveBooleanToJSON(value['ebgp']),
        
        'ebgp-multihop': value['ebgpMultihop'],
        
        'isis-domain': value['isisDomain'],
        
        'isis-ifaces': value['isisIfaces'],
        
        'isis-net': value['isisNet'],
        
        'loopback': value['loopback'],
        
        'node': value['node'],
        
        'peers': value['peers'],
        
        'pending': ClusterSdnGetControllersResponseDataInnerPendingToJSON(value['pending']),
        
        'state': PveClusterSdnStateEnumToJSON(value['state']),
        
        'type': PveClusterSdnTypeEnumToJSON(value['type']),
        
    };
}

