/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';

/**
 * 
 * @export
 * @interface ClusterBulkActionMigrateRequest
 */
export interface ClusterBulkActionMigrateRequest {

    /**
     * How many parallel tasks at maximum should be started.
     * @type {number}
     * @memberof ClusterBulkActionMigrateRequest
     */
    maxworkers?: number;

    /**
     * Enable live migration for VMs and restart migration for CTs.
     * @type {PveBoolean}
     * @memberof ClusterBulkActionMigrateRequest
     */
    online?: PveBoolean;

    /**
     * Target node.
     * @type {string}
     * @memberof ClusterBulkActionMigrateRequest
     */
    target: string;

    /**
     * Only consider guests from this list of VMIDs.
     * @type {Array<number>}
     * @memberof ClusterBulkActionMigrateRequest
     */
    vms?: Array<number>;

    /**
     * Enable live storage migration for local disk
     * @type {PveBoolean}
     * @memberof ClusterBulkActionMigrateRequest
     */
    withLocalDisks?: PveBoolean;

}



/**
 * Check if a given object implements the ClusterBulkActionMigrateRequest interface.
 */
export function instanceOfClusterBulkActionMigrateRequest(value: object): value is ClusterBulkActionMigrateRequest {
    
    
    
    if (!('target' in value) || value['target'] === undefined) return false;
    
    
    
    return true;
}

export function ClusterBulkActionMigrateRequestFromJSON(json: any): ClusterBulkActionMigrateRequest {
    return ClusterBulkActionMigrateRequestFromJSONTyped(json, false);
}

export function ClusterBulkActionMigrateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterBulkActionMigrateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'maxworkers': json['maxworkers'] == null ? undefined : json['maxworkers'],
        
        'online': json['online'] == null ? undefined : PveBooleanFromJSON(json['online']),
        
        'target': json['target'],
        
        'vms': json['vms'] == null ? undefined : json['vms'],
        
        'withLocalDisks': json['with-local-disks'] == null ? undefined : PveBooleanFromJSON(json['with-local-disks']),
        
    };
}

export function ClusterBulkActionMigrateRequestToJSON(json: any): ClusterBulkActionMigrateRequest {
    return ClusterBulkActionMigrateRequestToJSONTyped(json, false);
}

export function ClusterBulkActionMigrateRequestToJSONTyped(value?: ClusterBulkActionMigrateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'maxworkers': value['maxworkers'],
        
        'online': PveBooleanToJSON(value['online']),
        
        'target': value['target'],
        
        'vms': value['vms'],
        
        'with-local-disks': PveBooleanToJSON(value['withLocalDisks']),
        
    };
}

