/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClusterNotificationsGetGotifyEndpointsResponseDataInner } from './ClusterNotificationsGetGotifyEndpointsResponseDataInner';
import {
    ClusterNotificationsGetGotifyEndpointsResponseDataInnerFromJSON,
    ClusterNotificationsGetGotifyEndpointsResponseDataInnerFromJSONTyped,
    ClusterNotificationsGetGotifyEndpointsResponseDataInnerToJSON,
    ClusterNotificationsGetGotifyEndpointsResponseDataInnerToJSONTyped,
} from './ClusterNotificationsGetGotifyEndpointsResponseDataInner';

/**
 * 
 * @export
 * @interface ClusterNotificationsGetGotifyEndpointsResponse
 */
export interface ClusterNotificationsGetGotifyEndpointsResponse {

    /**
     * 
     * @type {Array<ClusterNotificationsGetGotifyEndpointsResponseDataInner>}
     * @memberof ClusterNotificationsGetGotifyEndpointsResponse
     */
    data: Array<ClusterNotificationsGetGotifyEndpointsResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ClusterNotificationsGetGotifyEndpointsResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ClusterNotificationsGetGotifyEndpointsResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ClusterNotificationsGetGotifyEndpointsResponse interface.
 */
export function instanceOfClusterNotificationsGetGotifyEndpointsResponse(value: object): value is ClusterNotificationsGetGotifyEndpointsResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ClusterNotificationsGetGotifyEndpointsResponseFromJSON(json: any): ClusterNotificationsGetGotifyEndpointsResponse {
    return ClusterNotificationsGetGotifyEndpointsResponseFromJSONTyped(json, false);
}

export function ClusterNotificationsGetGotifyEndpointsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterNotificationsGetGotifyEndpointsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ClusterNotificationsGetGotifyEndpointsResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ClusterNotificationsGetGotifyEndpointsResponseToJSON(json: any): ClusterNotificationsGetGotifyEndpointsResponse {
    return ClusterNotificationsGetGotifyEndpointsResponseToJSONTyped(json, false);
}

export function ClusterNotificationsGetGotifyEndpointsResponseToJSONTyped(value?: ClusterNotificationsGetGotifyEndpointsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ClusterNotificationsGetGotifyEndpointsResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

