/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveClusterFirewallTypeEnum } from './PveClusterFirewallTypeEnum';
import {
    PveClusterFirewallTypeEnumFromJSON,
    PveClusterFirewallTypeEnumFromJSONTyped,
    PveClusterFirewallTypeEnumToJSON,
    PveClusterFirewallTypeEnumToJSONTyped,
} from './PveClusterFirewallTypeEnum';
import type { PveLogEnum } from './PveLogEnum';
import {
    PveLogEnumFromJSON,
    PveLogEnumFromJSONTyped,
    PveLogEnumToJSON,
    PveLogEnumToJSONTyped,
} from './PveLogEnum';

/**
 * 
 * @export
 * @interface ClusterFirewallUpdateRuleRequest
 */
export interface ClusterFirewallUpdateRuleRequest {

    /**
     * Rule action ('ACCEPT', 'DROP', 'REJECT') or security group name.
     * @type {string}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    action?: string;

    /**
     * Descriptive comment.
     * @type {string}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    comment?: string;

    /**
     * A list of settings you want to delete.
     * @type {string}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    _delete?: string;

    /**
     * Restrict packet destination address. This can refer to a single IP address, an IP set ('+ipsetname') or an IP alias definition. You can also specify an address range like '20.34.101.207-201.3.9.99', or a list of IP addresses and networks (entries are separated by comma). Please do not mix IPv4 and IPv6 addresses inside such lists.
     * @type {string}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    dest?: string;

    /**
     * Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
     * @type {string}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    digest?: string;

    /**
     * Restrict TCP/UDP destination port. You can use service names or simple numbers (0-65535), as defined in '/etc/services'. Port ranges can be specified with '\d+:\d+', for example '80:85', and you can use comma separated list to match several ports or ranges.
     * @type {string}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    dport?: string;

    /**
     * Flag to enable/disable a rule.
     * @type {number}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    enable?: number;

    /**
     * Specify icmp-type. Only valid if proto equals 'icmp' or 'icmpv6'/'ipv6-icmp'.
     * @type {string}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    icmpType?: string;

    /**
     * Network interface name. You have to use network configuration key names for VMs and containers ('net\d+'). Host related rules can use arbitrary strings.
     * @type {string}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    iface?: string;

    /**
     * Log level for firewall rule.
     * @type {PveLogEnum}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    log?: PveLogEnum;

    /**
     * Use predefined standard macro.
     * @type {string}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    macro?: string;

    /**
     * Move rule to new position <moveto>. Other arguments are ignored.
     * @type {number}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    moveto?: number;

    /**
     * IP protocol. You can use protocol names ('tcp'/'udp') or simple numbers, as defined in '/etc/protocols'.
     * @type {string}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    proto?: string;

    /**
     * Restrict packet source address. This can refer to a single IP address, an IP set ('+ipsetname') or an IP alias definition. You can also specify an address range like '20.34.101.207-201.3.9.99', or a list of IP addresses and networks (entries are separated by comma). Please do not mix IPv4 and IPv6 addresses inside such lists.
     * @type {string}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    source?: string;

    /**
     * Restrict TCP/UDP source port. You can use service names or simple numbers (0-65535), as defined in '/etc/services'. Port ranges can be specified with '\d+:\d+', for example '80:85', and you can use comma separated list to match several ports or ranges.
     * @type {string}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    sport?: string;

    /**
     * Rule type.
     * @type {PveClusterFirewallTypeEnum}
     * @memberof ClusterFirewallUpdateRuleRequest
     */
    type?: PveClusterFirewallTypeEnum;

}



/**
 * Check if a given object implements the ClusterFirewallUpdateRuleRequest interface.
 */
export function instanceOfClusterFirewallUpdateRuleRequest(value: object): value is ClusterFirewallUpdateRuleRequest {
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    return true;
}

export function ClusterFirewallUpdateRuleRequestFromJSON(json: any): ClusterFirewallUpdateRuleRequest {
    return ClusterFirewallUpdateRuleRequestFromJSONTyped(json, false);
}

export function ClusterFirewallUpdateRuleRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterFirewallUpdateRuleRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'action': json['action'] == null ? undefined : json['action'],
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        '_delete': json['delete'] == null ? undefined : json['delete'],
        
        'dest': json['dest'] == null ? undefined : json['dest'],
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
        'dport': json['dport'] == null ? undefined : json['dport'],
        
        'enable': json['enable'] == null ? undefined : json['enable'],
        
        'icmpType': json['icmp-type'] == null ? undefined : json['icmp-type'],
        
        'iface': json['iface'] == null ? undefined : json['iface'],
        
        'log': json['log'] == null ? undefined : PveLogEnumFromJSON(json['log']),
        
        'macro': json['macro'] == null ? undefined : json['macro'],
        
        'moveto': json['moveto'] == null ? undefined : json['moveto'],
        
        'proto': json['proto'] == null ? undefined : json['proto'],
        
        'source': json['source'] == null ? undefined : json['source'],
        
        'sport': json['sport'] == null ? undefined : json['sport'],
        
        'type': json['type'] == null ? undefined : PveClusterFirewallTypeEnumFromJSON(json['type']),
        
    };
}

export function ClusterFirewallUpdateRuleRequestToJSON(json: any): ClusterFirewallUpdateRuleRequest {
    return ClusterFirewallUpdateRuleRequestToJSONTyped(json, false);
}

export function ClusterFirewallUpdateRuleRequestToJSONTyped(value?: ClusterFirewallUpdateRuleRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'action': value['action'],
        
        'comment': value['comment'],
        
        'delete': value['_delete'],
        
        'dest': value['dest'],
        
        'digest': value['digest'],
        
        'dport': value['dport'],
        
        'enable': value['enable'],
        
        'icmp-type': value['icmpType'],
        
        'iface': value['iface'],
        
        'log': PveLogEnumToJSON(value['log']),
        
        'macro': value['macro'],
        
        'moveto': value['moveto'],
        
        'proto': value['proto'],
        
        'source': value['source'],
        
        'sport': value['sport'],
        
        'type': PveClusterFirewallTypeEnumToJSON(value['type']),
        
    };
}

