/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';
import type { PveMethodEnum } from './PveMethodEnum';
import {
    PveMethodEnumFromJSON,
    PveMethodEnumFromJSONTyped,
    PveMethodEnumToJSON,
    PveMethodEnumToJSONTyped,
} from './PveMethodEnum';

/**
 * 
 * @export
 * @interface ClusterNotificationsUpdateWebhookEndpointRequest
 */
export interface ClusterNotificationsUpdateWebhookEndpointRequest {

    /**
     * HTTP body, base64 encoded
     * @type {string}
     * @memberof ClusterNotificationsUpdateWebhookEndpointRequest
     */
    body?: string;

    /**
     * Comment
     * @type {string}
     * @memberof ClusterNotificationsUpdateWebhookEndpointRequest
     */
    comment?: string;

    /**
     * A list of settings you want to delete.
     * @type {Array<string>}
     * @memberof ClusterNotificationsUpdateWebhookEndpointRequest
     */
    _delete?: Array<string>;

    /**
     * Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
     * @type {string}
     * @memberof ClusterNotificationsUpdateWebhookEndpointRequest
     */
    digest?: string;

    /**
     * Disable this target
     * @type {PveBoolean}
     * @memberof ClusterNotificationsUpdateWebhookEndpointRequest
     */
    disable?: PveBoolean;

    /**
     * HTTP headers to set. These have to be formatted as a property string in the format name=<name>,value=<base64 of value>
     * @type {Array<string>}
     * @memberof ClusterNotificationsUpdateWebhookEndpointRequest
     */
    header?: Array<string>;

    /**
     * HTTP method
     * @type {PveMethodEnum}
     * @memberof ClusterNotificationsUpdateWebhookEndpointRequest
     */
    method?: PveMethodEnum;

    /**
     * Secrets to set. These have to be formatted as a property string in the format name=<name>,value=<base64 of value>
     * @type {Array<string>}
     * @memberof ClusterNotificationsUpdateWebhookEndpointRequest
     */
    secret?: Array<string>;

    /**
     * Server URL
     * @type {string}
     * @memberof ClusterNotificationsUpdateWebhookEndpointRequest
     */
    url?: string;

}



/**
 * Check if a given object implements the ClusterNotificationsUpdateWebhookEndpointRequest interface.
 */
export function instanceOfClusterNotificationsUpdateWebhookEndpointRequest(value: object): value is ClusterNotificationsUpdateWebhookEndpointRequest {
    
    
    
    
    
    
    
    
    
    
    return true;
}

export function ClusterNotificationsUpdateWebhookEndpointRequestFromJSON(json: any): ClusterNotificationsUpdateWebhookEndpointRequest {
    return ClusterNotificationsUpdateWebhookEndpointRequestFromJSONTyped(json, false);
}

export function ClusterNotificationsUpdateWebhookEndpointRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterNotificationsUpdateWebhookEndpointRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'body': json['body'] == null ? undefined : json['body'],
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        '_delete': json['delete'] == null ? undefined : json['delete'],
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
        'disable': json['disable'] == null ? undefined : PveBooleanFromJSON(json['disable']),
        
        'header': json['header'] == null ? undefined : json['header'],
        
        'method': json['method'] == null ? undefined : PveMethodEnumFromJSON(json['method']),
        
        'secret': json['secret'] == null ? undefined : json['secret'],
        
        'url': json['url'] == null ? undefined : json['url'],
        
    };
}

export function ClusterNotificationsUpdateWebhookEndpointRequestToJSON(json: any): ClusterNotificationsUpdateWebhookEndpointRequest {
    return ClusterNotificationsUpdateWebhookEndpointRequestToJSONTyped(json, false);
}

export function ClusterNotificationsUpdateWebhookEndpointRequestToJSONTyped(value?: ClusterNotificationsUpdateWebhookEndpointRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'body': value['body'],
        
        'comment': value['comment'],
        
        'delete': value['_delete'],
        
        'digest': value['digest'],
        
        'disable': PveBooleanToJSON(value['disable']),
        
        'header': value['header'],
        
        'method': PveMethodEnumToJSON(value['method']),
        
        'secret': value['secret'],
        
        'url': value['url'],
        
    };
}

