/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';
import type { PveMethodEnum } from './PveMethodEnum';
import {
    PveMethodEnumFromJSON,
    PveMethodEnumFromJSONTyped,
    PveMethodEnumToJSON,
    PveMethodEnumToJSONTyped,
} from './PveMethodEnum';

/**
 * 
 * @export
 * @interface ClusterNotificationsCreateWebhookEndpointRequest
 */
export interface ClusterNotificationsCreateWebhookEndpointRequest {

    /**
     * HTTP body, base64 encoded
     * @type {string}
     * @memberof ClusterNotificationsCreateWebhookEndpointRequest
     */
    body?: string;

    /**
     * Comment
     * @type {string}
     * @memberof ClusterNotificationsCreateWebhookEndpointRequest
     */
    comment?: string;

    /**
     * Disable this target
     * @type {PveBoolean}
     * @memberof ClusterNotificationsCreateWebhookEndpointRequest
     */
    disable?: PveBoolean;

    /**
     * HTTP headers to set. These have to be formatted as a property string in the format name=<name>,value=<base64 of value>
     * @type {Array<string>}
     * @memberof ClusterNotificationsCreateWebhookEndpointRequest
     */
    header?: Array<string>;

    /**
     * HTTP method
     * @type {PveMethodEnum}
     * @memberof ClusterNotificationsCreateWebhookEndpointRequest
     */
    method: PveMethodEnum;

    /**
     * The name of the endpoint.
     * @type {string}
     * @memberof ClusterNotificationsCreateWebhookEndpointRequest
     */
    name: string;

    /**
     * Secrets to set. These have to be formatted as a property string in the format name=<name>,value=<base64 of value>
     * @type {Array<string>}
     * @memberof ClusterNotificationsCreateWebhookEndpointRequest
     */
    secret?: Array<string>;

    /**
     * Server URL
     * @type {string}
     * @memberof ClusterNotificationsCreateWebhookEndpointRequest
     */
    url: string;

}



/**
 * Check if a given object implements the ClusterNotificationsCreateWebhookEndpointRequest interface.
 */
export function instanceOfClusterNotificationsCreateWebhookEndpointRequest(value: object): value is ClusterNotificationsCreateWebhookEndpointRequest {
    
    
    
    
    
    if (!('method' in value) || value['method'] === undefined) return false;
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    
    if (!('url' in value) || value['url'] === undefined) return false;
    
    return true;
}

export function ClusterNotificationsCreateWebhookEndpointRequestFromJSON(json: any): ClusterNotificationsCreateWebhookEndpointRequest {
    return ClusterNotificationsCreateWebhookEndpointRequestFromJSONTyped(json, false);
}

export function ClusterNotificationsCreateWebhookEndpointRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterNotificationsCreateWebhookEndpointRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'body': json['body'] == null ? undefined : json['body'],
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        'disable': json['disable'] == null ? undefined : PveBooleanFromJSON(json['disable']),
        
        'header': json['header'] == null ? undefined : json['header'],
        
        'method': PveMethodEnumFromJSON(json['method']),
        
        'name': json['name'],
        
        'secret': json['secret'] == null ? undefined : json['secret'],
        
        'url': json['url'],
        
    };
}

export function ClusterNotificationsCreateWebhookEndpointRequestToJSON(json: any): ClusterNotificationsCreateWebhookEndpointRequest {
    return ClusterNotificationsCreateWebhookEndpointRequestToJSONTyped(json, false);
}

export function ClusterNotificationsCreateWebhookEndpointRequestToJSONTyped(value?: ClusterNotificationsCreateWebhookEndpointRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'body': value['body'],
        
        'comment': value['comment'],
        
        'disable': PveBooleanToJSON(value['disable']),
        
        'header': value['header'],
        
        'method': PveMethodEnumToJSON(value['method']),
        
        'name': value['name'],
        
        'secret': value['secret'],
        
        'url': value['url'],
        
    };
}

