/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClusterNotificationsGetMatcherFieldValuesResponseDataInner
 */
export interface ClusterNotificationsGetMatcherFieldValuesResponseDataInner {

    /**
     * Additional comment for this value.
     * @type {string}
     * @memberof ClusterNotificationsGetMatcherFieldValuesResponseDataInner
     */
    comment?: string;

    /**
     * Field this value belongs to.
     * @type {string}
     * @memberof ClusterNotificationsGetMatcherFieldValuesResponseDataInner
     */
    field: string;

    /**
     * Notification metadata value known by the system.
     * @type {string}
     * @memberof ClusterNotificationsGetMatcherFieldValuesResponseDataInner
     */
    value: string;

}

/**
 * Check if a given object implements the ClusterNotificationsGetMatcherFieldValuesResponseDataInner interface.
 */
export function instanceOfClusterNotificationsGetMatcherFieldValuesResponseDataInner(value: object): value is ClusterNotificationsGetMatcherFieldValuesResponseDataInner {
    
    
    if (!('field' in value) || value['field'] === undefined) return false;
    
    if (!('value' in value) || value['value'] === undefined) return false;
    
    return true;
}

export function ClusterNotificationsGetMatcherFieldValuesResponseDataInnerFromJSON(json: any): ClusterNotificationsGetMatcherFieldValuesResponseDataInner {
    return ClusterNotificationsGetMatcherFieldValuesResponseDataInnerFromJSONTyped(json, false);
}

export function ClusterNotificationsGetMatcherFieldValuesResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterNotificationsGetMatcherFieldValuesResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        'field': json['field'],
        
        'value': json['value'],
        
    };
}

export function ClusterNotificationsGetMatcherFieldValuesResponseDataInnerToJSON(json: any): ClusterNotificationsGetMatcherFieldValuesResponseDataInner {
    return ClusterNotificationsGetMatcherFieldValuesResponseDataInnerToJSONTyped(json, false);
}

export function ClusterNotificationsGetMatcherFieldValuesResponseDataInnerToJSONTyped(value?: ClusterNotificationsGetMatcherFieldValuesResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'comment': value['comment'],
        
        'field': value['field'],
        
        'value': value['value'],
        
    };
}

