/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClusterBulkActionMigrateResponse
 */
export interface ClusterBulkActionMigrateResponse {

    /**
     * 
     * @type {string}
     * @memberof ClusterBulkActionMigrateResponse
     */
    data: string;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ClusterBulkActionMigrateResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ClusterBulkActionMigrateResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ClusterBulkActionMigrateResponse interface.
 */
export function instanceOfClusterBulkActionMigrateResponse(value: object): value is ClusterBulkActionMigrateResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ClusterBulkActionMigrateResponseFromJSON(json: any): ClusterBulkActionMigrateResponse {
    return ClusterBulkActionMigrateResponseFromJSONTyped(json, false);
}

export function ClusterBulkActionMigrateResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterBulkActionMigrateResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ClusterBulkActionMigrateResponseToJSON(json: any): ClusterBulkActionMigrateResponse {
    return ClusterBulkActionMigrateResponseToJSONTyped(json, false);
}

export function ClusterBulkActionMigrateResponseToJSONTyped(value?: ClusterBulkActionMigrateResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

