/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClusterAcmeChallengeschemaResponseDataInner
 */
export interface ClusterAcmeChallengeschemaResponseDataInner {

    /**
     * 
     * @type {string}
     * @memberof ClusterAcmeChallengeschemaResponseDataInner
     */
    id: string;

    /**
     * Human readable name, falls back to id
     * @type {string}
     * @memberof ClusterAcmeChallengeschemaResponseDataInner
     */
    name: string;

    /**
     * 
     * @type {object}
     * @memberof ClusterAcmeChallengeschemaResponseDataInner
     */
    schema: object;

    /**
     * 
     * @type {string}
     * @memberof ClusterAcmeChallengeschemaResponseDataInner
     */
    type: string;

}

/**
 * Check if a given object implements the ClusterAcmeChallengeschemaResponseDataInner interface.
 */
export function instanceOfClusterAcmeChallengeschemaResponseDataInner(value: object): value is ClusterAcmeChallengeschemaResponseDataInner {
    
    if (!('id' in value) || value['id'] === undefined) return false;
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    if (!('schema' in value) || value['schema'] === undefined) return false;
    
    if (!('type' in value) || value['type'] === undefined) return false;
    
    return true;
}

export function ClusterAcmeChallengeschemaResponseDataInnerFromJSON(json: any): ClusterAcmeChallengeschemaResponseDataInner {
    return ClusterAcmeChallengeschemaResponseDataInnerFromJSONTyped(json, false);
}

export function ClusterAcmeChallengeschemaResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterAcmeChallengeschemaResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'id': json['id'],
        
        'name': json['name'],
        
        'schema': json['schema'],
        
        'type': json['type'],
        
    };
}

export function ClusterAcmeChallengeschemaResponseDataInnerToJSON(json: any): ClusterAcmeChallengeschemaResponseDataInner {
    return ClusterAcmeChallengeschemaResponseDataInnerToJSONTyped(json, false);
}

export function ClusterAcmeChallengeschemaResponseDataInnerToJSONTyped(value?: ClusterAcmeChallengeschemaResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'id': value['id'],
        
        'name': value['name'],
        
        'schema': value['schema'],
        
        'type': value['type'],
        
    };
}

