/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClusterAcmeGetMetaResponseData } from './ClusterAcmeGetMetaResponseData';
import {
    ClusterAcmeGetMetaResponseDataFromJSON,
    ClusterAcmeGetMetaResponseDataFromJSONTyped,
    ClusterAcmeGetMetaResponseDataToJSON,
    ClusterAcmeGetMetaResponseDataToJSONTyped,
} from './ClusterAcmeGetMetaResponseData';

/**
 * 
 * @export
 * @interface ClusterAcmeGetMetaResponse
 */
export interface ClusterAcmeGetMetaResponse {

    /**
     * 
     * @type {ClusterAcmeGetMetaResponseData}
     * @memberof ClusterAcmeGetMetaResponse
     */
    data: ClusterAcmeGetMetaResponseData;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ClusterAcmeGetMetaResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ClusterAcmeGetMetaResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ClusterAcmeGetMetaResponse interface.
 */
export function instanceOfClusterAcmeGetMetaResponse(value: object): value is ClusterAcmeGetMetaResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ClusterAcmeGetMetaResponseFromJSON(json: any): ClusterAcmeGetMetaResponse {
    return ClusterAcmeGetMetaResponseFromJSONTyped(json, false);
}

export function ClusterAcmeGetMetaResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterAcmeGetMetaResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ClusterAcmeGetMetaResponseDataFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ClusterAcmeGetMetaResponseToJSON(json: any): ClusterAcmeGetMetaResponse {
    return ClusterAcmeGetMetaResponseToJSONTyped(json, false);
}

export function ClusterAcmeGetMetaResponseToJSONTyped(value?: ClusterAcmeGetMetaResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ClusterAcmeGetMetaResponseDataToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

