/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClusterMappingCreatePciRequestMapInnerOneOf
 */
export interface ClusterMappingCreatePciRequestMapInnerOneOf {

    /**
     * Description of the node specific device.
     * @type {string}
     * @memberof ClusterMappingCreatePciRequestMapInnerOneOf
     */
    description?: string;

    /**
     * The vendor and device ID that is expected. Used for detecting hardware changes
     * @type {string}
     * @memberof ClusterMappingCreatePciRequestMapInnerOneOf
     */
    id: string;

    /**
     * The IOMMU group in which the device is to be expected in. Used for detecting hardware changes.
     * @type {number}
     * @memberof ClusterMappingCreatePciRequestMapInnerOneOf
     */
    iommugroup?: number;

    /**
     * The cluster node name.
     * @type {string}
     * @memberof ClusterMappingCreatePciRequestMapInnerOneOf
     */
    node: string;

    /**
     * The path to the device. If the function is omitted, the whole device is mapped. In that case use the attributes of the first device. You can give multiple paths as a semicolon seperated list, the first available will then be chosen on guest start.
     * @type {string}
     * @memberof ClusterMappingCreatePciRequestMapInnerOneOf
     */
    path: string;

    /**
     * The subsystem vendor and device ID that is expected. Used for detecting hardware changes.
     * @type {string}
     * @memberof ClusterMappingCreatePciRequestMapInnerOneOf
     */
    subsystemId?: string;

}

/**
 * Check if a given object implements the ClusterMappingCreatePciRequestMapInnerOneOf interface.
 */
export function instanceOfClusterMappingCreatePciRequestMapInnerOneOf(value: object): value is ClusterMappingCreatePciRequestMapInnerOneOf {
    
    
    if (!('id' in value) || value['id'] === undefined) return false;
    
    
    if (!('node' in value) || value['node'] === undefined) return false;
    
    if (!('path' in value) || value['path'] === undefined) return false;
    
    
    return true;
}

export function ClusterMappingCreatePciRequestMapInnerOneOfFromJSON(json: any): ClusterMappingCreatePciRequestMapInnerOneOf {
    return ClusterMappingCreatePciRequestMapInnerOneOfFromJSONTyped(json, false);
}

export function ClusterMappingCreatePciRequestMapInnerOneOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterMappingCreatePciRequestMapInnerOneOf {
    if (json == null) {
        return json;
    }
    return {
        
        
        'description': json['description'] == null ? undefined : json['description'],
        
        'id': json['id'],
        
        'iommugroup': json['iommugroup'] == null ? undefined : json['iommugroup'],
        
        'node': json['node'],
        
        'path': json['path'],
        
        'subsystemId': json['subsystem-id'] == null ? undefined : json['subsystem-id'],
        
    };
}

export function ClusterMappingCreatePciRequestMapInnerOneOfToJSON(json: any): ClusterMappingCreatePciRequestMapInnerOneOf {
    return ClusterMappingCreatePciRequestMapInnerOneOfToJSONTyped(json, false);
}

export function ClusterMappingCreatePciRequestMapInnerOneOfToJSONTyped(value?: ClusterMappingCreatePciRequestMapInnerOneOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'description': value['description'],
        
        'id': value['id'],
        
        'iommugroup': value['iommugroup'],
        
        'node': value['node'],
        
        'path': value['path'],
        
        'subsystem-id': value['subsystemId'],
        
    };
}

/**
 * Serialise a ClusterMappingCreatePciRequestMapInnerOneOf into Proxmox's CLI-style shorthand string
 * (`key=value,…`). The property marked `x-pve-default-key` is emitted
 * positionally without a `key=` prefix; aliases collapse multiple
 * property names to the same wire key.
 *
 * Example: `{ model: 'virtio', bridge: 'vmbr0', firewall: 1 }`
 *      → `'virtio,bridge=vmbr0,firewall=1'`
 */
export function ClusterMappingCreatePciRequestMapInnerOneOfToShorthand(value?: ClusterMappingCreatePciRequestMapInnerOneOf | null): string | undefined {
    if (value == null) return undefined;
    const parts: string[] = [];
    
    
    if (value['description'] != null) {
        parts.push(`description=${String(value['description'])}`);
    }
    
    if (value['id'] != null) {
        parts.push(`id=${String(value['id'])}`);
    }
    
    if (value['iommugroup'] != null) {
        parts.push(`iommugroup=${String(value['iommugroup'])}`);
    }
    
    if (value['node'] != null) {
        parts.push(`node=${String(value['node'])}`);
    }
    
    if (value['path'] != null) {
        parts.push(`path=${String(value['path'])}`);
    }
    
    if (value['subsystemId'] != null) {
        parts.push(`subsystem-id=${String(value['subsystemId'])}`);
    }
    
    return parts.join(',');
}

/**
 * Parse a Proxmox shorthand string into a ClusterMappingCreatePciRequestMapInnerOneOf. Mirror of
 * ClusterMappingCreatePciRequestMapInnerOneOfToShorthand. The first comma-separated segment without
 * `=` is interpreted as the default-key value.
 */
export function ClusterMappingCreatePciRequestMapInnerOneOfFromShorthand(input?: string | null): ClusterMappingCreatePciRequestMapInnerOneOf | undefined {
    if (input == null) return undefined;
    const out: any = {};
    let defaultKeyConsumed = false;
    for (const part of input.split(',')) {
        if (!part) continue;
        const eq = part.indexOf('=');
        if (eq < 0) {
            
            continue;
        }
        const k = part.slice(0, eq);
        const v = part.slice(eq + 1);
        out[k] = v;
    }
    return out as ClusterMappingCreatePciRequestMapInnerOneOf;
}

