/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClusterAcmeGetAccountResponseData } from './ClusterAcmeGetAccountResponseData';
import {
    ClusterAcmeGetAccountResponseDataFromJSON,
    ClusterAcmeGetAccountResponseDataFromJSONTyped,
    ClusterAcmeGetAccountResponseDataToJSON,
    ClusterAcmeGetAccountResponseDataToJSONTyped,
} from './ClusterAcmeGetAccountResponseData';

/**
 * 
 * @export
 * @interface ClusterAcmeGetAccountResponse
 */
export interface ClusterAcmeGetAccountResponse {

    /**
     * 
     * @type {ClusterAcmeGetAccountResponseData}
     * @memberof ClusterAcmeGetAccountResponse
     */
    data: ClusterAcmeGetAccountResponseData;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ClusterAcmeGetAccountResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ClusterAcmeGetAccountResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ClusterAcmeGetAccountResponse interface.
 */
export function instanceOfClusterAcmeGetAccountResponse(value: object): value is ClusterAcmeGetAccountResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ClusterAcmeGetAccountResponseFromJSON(json: any): ClusterAcmeGetAccountResponse {
    return ClusterAcmeGetAccountResponseFromJSONTyped(json, false);
}

export function ClusterAcmeGetAccountResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterAcmeGetAccountResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ClusterAcmeGetAccountResponseDataFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ClusterAcmeGetAccountResponseToJSON(json: any): ClusterAcmeGetAccountResponse {
    return ClusterAcmeGetAccountResponseToJSONTyped(json, false);
}

export function ClusterAcmeGetAccountResponseToJSONTyped(value?: ClusterAcmeGetAccountResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ClusterAcmeGetAccountResponseDataToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

