/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';
import type { PveModeModeEnum } from './PveModeModeEnum';
import {
    PveModeModeEnumFromJSON,
    PveModeModeEnumFromJSONTyped,
    PveModeModeEnumToJSON,
    PveModeModeEnumToJSONTyped,
} from './PveModeModeEnum';

/**
 * 
 * @export
 * @interface ClusterNotificationsUpdateMatcherRequest
 */
export interface ClusterNotificationsUpdateMatcherRequest {

    /**
     * Comment
     * @type {string}
     * @memberof ClusterNotificationsUpdateMatcherRequest
     */
    comment?: string;

    /**
     * A list of settings you want to delete.
     * @type {Array<string>}
     * @memberof ClusterNotificationsUpdateMatcherRequest
     */
    _delete?: Array<string>;

    /**
     * Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
     * @type {string}
     * @memberof ClusterNotificationsUpdateMatcherRequest
     */
    digest?: string;

    /**
     * Disable this matcher
     * @type {PveBoolean}
     * @memberof ClusterNotificationsUpdateMatcherRequest
     */
    disable?: PveBoolean;

    /**
     * Invert match of the whole matcher
     * @type {PveBoolean}
     * @memberof ClusterNotificationsUpdateMatcherRequest
     */
    invertMatch?: PveBoolean;

    /**
     * Match notification timestamp
     * @type {Array<string>}
     * @memberof ClusterNotificationsUpdateMatcherRequest
     */
    matchCalendar?: Array<string>;

    /**
     * Metadata fields to match (regex or exact match). Must be in the form (regex|exact):<field>=<value>
     * @type {Array<string>}
     * @memberof ClusterNotificationsUpdateMatcherRequest
     */
    matchField?: Array<string>;

    /**
     * Notification severities to match
     * @type {Array<string>}
     * @memberof ClusterNotificationsUpdateMatcherRequest
     */
    matchSeverity?: Array<string>;

    /**
     * Choose between 'all' and 'any' for when multiple properties are specified
     * @type {PveModeModeEnum}
     * @memberof ClusterNotificationsUpdateMatcherRequest
     */
    mode?: PveModeModeEnum;

    /**
     * Targets to notify on match
     * @type {Array<string>}
     * @memberof ClusterNotificationsUpdateMatcherRequest
     */
    target?: Array<string>;

}



/**
 * Check if a given object implements the ClusterNotificationsUpdateMatcherRequest interface.
 */
export function instanceOfClusterNotificationsUpdateMatcherRequest(value: object): value is ClusterNotificationsUpdateMatcherRequest {
    
    
    
    
    
    
    
    
    
    
    
    return true;
}

export function ClusterNotificationsUpdateMatcherRequestFromJSON(json: any): ClusterNotificationsUpdateMatcherRequest {
    return ClusterNotificationsUpdateMatcherRequestFromJSONTyped(json, false);
}

export function ClusterNotificationsUpdateMatcherRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterNotificationsUpdateMatcherRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'comment': json['comment'] == null ? undefined : json['comment'],
        
        '_delete': json['delete'] == null ? undefined : json['delete'],
        
        'digest': json['digest'] == null ? undefined : json['digest'],
        
        'disable': json['disable'] == null ? undefined : PveBooleanFromJSON(json['disable']),
        
        'invertMatch': json['invert-match'] == null ? undefined : PveBooleanFromJSON(json['invert-match']),
        
        'matchCalendar': json['match-calendar'] == null ? undefined : json['match-calendar'],
        
        'matchField': json['match-field'] == null ? undefined : json['match-field'],
        
        'matchSeverity': json['match-severity'] == null ? undefined : json['match-severity'],
        
        'mode': json['mode'] == null ? undefined : PveModeModeEnumFromJSON(json['mode']),
        
        'target': json['target'] == null ? undefined : json['target'],
        
    };
}

export function ClusterNotificationsUpdateMatcherRequestToJSON(json: any): ClusterNotificationsUpdateMatcherRequest {
    return ClusterNotificationsUpdateMatcherRequestToJSONTyped(json, false);
}

export function ClusterNotificationsUpdateMatcherRequestToJSONTyped(value?: ClusterNotificationsUpdateMatcherRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'comment': value['comment'],
        
        'delete': value['_delete'],
        
        'digest': value['digest'],
        
        'disable': PveBooleanToJSON(value['disable']),
        
        'invert-match': PveBooleanToJSON(value['invertMatch']),
        
        'match-calendar': value['matchCalendar'],
        
        'match-field': value['matchField'],
        
        'match-severity': value['matchSeverity'],
        
        'mode': PveModeModeEnumToJSON(value['mode']),
        
        'target': value['target'],
        
    };
}

