/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClusterSdnGetIpamsResponseDataInner } from './ClusterSdnGetIpamsResponseDataInner';
import {
    ClusterSdnGetIpamsResponseDataInnerFromJSON,
    ClusterSdnGetIpamsResponseDataInnerFromJSONTyped,
    ClusterSdnGetIpamsResponseDataInnerToJSON,
    ClusterSdnGetIpamsResponseDataInnerToJSONTyped,
} from './ClusterSdnGetIpamsResponseDataInner';

/**
 * 
 * @export
 * @interface ClusterSdnGetIpamsResponse
 */
export interface ClusterSdnGetIpamsResponse {

    /**
     * 
     * @type {Array<ClusterSdnGetIpamsResponseDataInner>}
     * @memberof ClusterSdnGetIpamsResponse
     */
    data: Array<ClusterSdnGetIpamsResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof ClusterSdnGetIpamsResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof ClusterSdnGetIpamsResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the ClusterSdnGetIpamsResponse interface.
 */
export function instanceOfClusterSdnGetIpamsResponse(value: object): value is ClusterSdnGetIpamsResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function ClusterSdnGetIpamsResponseFromJSON(json: any): ClusterSdnGetIpamsResponse {
    return ClusterSdnGetIpamsResponseFromJSONTyped(json, false);
}

export function ClusterSdnGetIpamsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClusterSdnGetIpamsResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ClusterSdnGetIpamsResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function ClusterSdnGetIpamsResponseToJSON(json: any): ClusterSdnGetIpamsResponse {
    return ClusterSdnGetIpamsResponseToJSONTyped(json, false);
}

export function ClusterSdnGetIpamsResponseToJSONTyped(value?: ClusterSdnGetIpamsResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ClusterSdnGetIpamsResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

