/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LxcCloneVmResponse
 */
export interface LxcCloneVmResponse {

    /**
     * 
     * @type {string}
     * @memberof LxcCloneVmResponse
     */
    data: string;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof LxcCloneVmResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof LxcCloneVmResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the LxcCloneVmResponse interface.
 */
export function instanceOfLxcCloneVmResponse(value: object): value is LxcCloneVmResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function LxcCloneVmResponseFromJSON(json: any): LxcCloneVmResponse {
    return LxcCloneVmResponseFromJSONTyped(json, false);
}

export function LxcCloneVmResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LxcCloneVmResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function LxcCloneVmResponseToJSON(json: any): LxcCloneVmResponse {
    return LxcCloneVmResponseToJSONTyped(json, false);
}

export function LxcCloneVmResponseToJSONTyped(value?: LxcCloneVmResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

