/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LxcIpResponseDataInnerIpAddressesInner } from './LxcIpResponseDataInnerIpAddressesInner';
import {
    LxcIpResponseDataInnerIpAddressesInnerFromJSON,
    LxcIpResponseDataInnerIpAddressesInnerFromJSONTyped,
    LxcIpResponseDataInnerIpAddressesInnerToJSON,
    LxcIpResponseDataInnerIpAddressesInnerToJSONTyped,
} from './LxcIpResponseDataInnerIpAddressesInner';

/**
 * 
 * @export
 * @interface LxcIpResponseDataInner
 */
export interface LxcIpResponseDataInner {

    /**
     * The MAC address of the interface
     * @type {string}
     * @memberof LxcIpResponseDataInner
     */
    hardwareAddress: string;

    /**
     * The MAC address of the interface
     * @type {string}
     * @memberof LxcIpResponseDataInner
     */
    hwaddr: string;

    /**
     * The IPv4 address of the interface
     * @type {string}
     * @memberof LxcIpResponseDataInner
     */
    inet?: string;

    /**
     * The IPv6 address of the interface
     * @type {string}
     * @memberof LxcIpResponseDataInner
     */
    inet6?: string;

    /**
     * The addresses of the interface
     * @type {Array<LxcIpResponseDataInnerIpAddressesInner>}
     * @memberof LxcIpResponseDataInner
     */
    ipAddresses: Array<LxcIpResponseDataInnerIpAddressesInner>;

    /**
     * The name of the interface
     * @type {string}
     * @memberof LxcIpResponseDataInner
     */
    name: string;

}

/**
 * Check if a given object implements the LxcIpResponseDataInner interface.
 */
export function instanceOfLxcIpResponseDataInner(value: object): value is LxcIpResponseDataInner {
    
    if (!('hardwareAddress' in value) || value['hardwareAddress'] === undefined) return false;
    
    if (!('hwaddr' in value) || value['hwaddr'] === undefined) return false;
    
    
    
    if (!('ipAddresses' in value) || value['ipAddresses'] === undefined) return false;
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    return true;
}

export function LxcIpResponseDataInnerFromJSON(json: any): LxcIpResponseDataInner {
    return LxcIpResponseDataInnerFromJSONTyped(json, false);
}

export function LxcIpResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): LxcIpResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'hardwareAddress': json['hardware-address'],
        
        'hwaddr': json['hwaddr'],
        
        'inet': json['inet'] == null ? undefined : json['inet'],
        
        'inet6': json['inet6'] == null ? undefined : json['inet6'],
        
        'ipAddresses': ((json['ip-addresses'] as Array<any>).map(LxcIpResponseDataInnerIpAddressesInnerFromJSON)),
        
        'name': json['name'],
        
    };
}

export function LxcIpResponseDataInnerToJSON(json: any): LxcIpResponseDataInner {
    return LxcIpResponseDataInnerToJSONTyped(json, false);
}

export function LxcIpResponseDataInnerToJSONTyped(value?: LxcIpResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'hardware-address': value['hardwareAddress'],
        
        'hwaddr': value['hwaddr'],
        
        'inet': value['inet'],
        
        'inet6': value['inet6'],
        
        'ip-addresses': ((value['ipAddresses'] as Array<any>).map(LxcIpResponseDataInnerIpAddressesInnerToJSON)),
        
        'name': value['name'],
        
    };
}

