/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LxcMigrateVmPreconditionResponseData } from './LxcMigrateVmPreconditionResponseData';
import {
    LxcMigrateVmPreconditionResponseDataFromJSON,
    LxcMigrateVmPreconditionResponseDataFromJSONTyped,
    LxcMigrateVmPreconditionResponseDataToJSON,
    LxcMigrateVmPreconditionResponseDataToJSONTyped,
} from './LxcMigrateVmPreconditionResponseData';

/**
 * 
 * @export
 * @interface LxcMigrateVmPreconditionResponse
 */
export interface LxcMigrateVmPreconditionResponse {

    /**
     * 
     * @type {LxcMigrateVmPreconditionResponseData}
     * @memberof LxcMigrateVmPreconditionResponse
     */
    data: LxcMigrateVmPreconditionResponseData;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof LxcMigrateVmPreconditionResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof LxcMigrateVmPreconditionResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the LxcMigrateVmPreconditionResponse interface.
 */
export function instanceOfLxcMigrateVmPreconditionResponse(value: object): value is LxcMigrateVmPreconditionResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function LxcMigrateVmPreconditionResponseFromJSON(json: any): LxcMigrateVmPreconditionResponse {
    return LxcMigrateVmPreconditionResponseFromJSONTyped(json, false);
}

export function LxcMigrateVmPreconditionResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): LxcMigrateVmPreconditionResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': LxcMigrateVmPreconditionResponseDataFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function LxcMigrateVmPreconditionResponseToJSON(json: any): LxcMigrateVmPreconditionResponse {
    return LxcMigrateVmPreconditionResponseToJSONTyped(json, false);
}

export function LxcMigrateVmPreconditionResponseToJSONTyped(value?: LxcMigrateVmPreconditionResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': LxcMigrateVmPreconditionResponseDataToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

