/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';
import type { LxcMigrateVmPreconditionResponseDataNotAllowedNodes } from './LxcMigrateVmPreconditionResponseDataNotAllowedNodes';
import {
    LxcMigrateVmPreconditionResponseDataNotAllowedNodesFromJSON,
    LxcMigrateVmPreconditionResponseDataNotAllowedNodesFromJSONTyped,
    LxcMigrateVmPreconditionResponseDataNotAllowedNodesToJSON,
    LxcMigrateVmPreconditionResponseDataNotAllowedNodesToJSONTyped,
} from './LxcMigrateVmPreconditionResponseDataNotAllowedNodes';

/**
 * 
 * @export
 * @interface LxcMigrateVmPreconditionResponseData
 */
export interface LxcMigrateVmPreconditionResponseData {

    /**
     * List of nodes allowed for migration.
     * @type {Array<string>}
     * @memberof LxcMigrateVmPreconditionResponseData
     */
    allowedNodes?: Array<string>;

    /**
     * HA resources, which will be migrated to the same target node as the VM, because these are in positive affinity with the VM.
     * @type {Array<string>}
     * @memberof LxcMigrateVmPreconditionResponseData
     */
    dependentHaResources?: Array<string>;

    /**
     * 
     * @type {LxcMigrateVmPreconditionResponseDataNotAllowedNodes}
     * @memberof LxcMigrateVmPreconditionResponseData
     */
    notAllowedNodes?: LxcMigrateVmPreconditionResponseDataNotAllowedNodes;

    /**
     * Determines if the container is running.
     * @type {PveBoolean}
     * @memberof LxcMigrateVmPreconditionResponseData
     */
    running: PveBoolean;

}



/**
 * Check if a given object implements the LxcMigrateVmPreconditionResponseData interface.
 */
export function instanceOfLxcMigrateVmPreconditionResponseData(value: object): value is LxcMigrateVmPreconditionResponseData {
    
    
    
    
    if (!('running' in value) || value['running'] === undefined) return false;
    
    return true;
}

export function LxcMigrateVmPreconditionResponseDataFromJSON(json: any): LxcMigrateVmPreconditionResponseData {
    return LxcMigrateVmPreconditionResponseDataFromJSONTyped(json, false);
}

export function LxcMigrateVmPreconditionResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LxcMigrateVmPreconditionResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        
        'allowedNodes': json['allowed-nodes'] == null ? undefined : json['allowed-nodes'],
        
        'dependentHaResources': json['dependent-ha-resources'] == null ? undefined : json['dependent-ha-resources'],
        
        'notAllowedNodes': json['not-allowed-nodes'] == null ? undefined : LxcMigrateVmPreconditionResponseDataNotAllowedNodesFromJSON(json['not-allowed-nodes']),
        
        'running': PveBooleanFromJSON(json['running']),
        
    };
}

export function LxcMigrateVmPreconditionResponseDataToJSON(json: any): LxcMigrateVmPreconditionResponseData {
    return LxcMigrateVmPreconditionResponseDataToJSONTyped(json, false);
}

export function LxcMigrateVmPreconditionResponseDataToJSONTyped(value?: LxcMigrateVmPreconditionResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'allowed-nodes': value['allowedNodes'],
        
        'dependent-ha-resources': value['dependentHaResources'],
        
        'not-allowed-nodes': LxcMigrateVmPreconditionResponseDataNotAllowedNodesToJSON(value['notAllowedNodes']),
        
        'running': PveBooleanToJSON(value['running']),
        
    };
}

