/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LxcVncwebsocketResponseData
 */
export interface LxcVncwebsocketResponseData {

    /**
     * 
     * @type {string}
     * @memberof LxcVncwebsocketResponseData
     */
    port: string;

}

/**
 * Check if a given object implements the LxcVncwebsocketResponseData interface.
 */
export function instanceOfLxcVncwebsocketResponseData(value: object): value is LxcVncwebsocketResponseData {
    
    if (!('port' in value) || value['port'] === undefined) return false;
    
    return true;
}

export function LxcVncwebsocketResponseDataFromJSON(json: any): LxcVncwebsocketResponseData {
    return LxcVncwebsocketResponseDataFromJSONTyped(json, false);
}

export function LxcVncwebsocketResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): LxcVncwebsocketResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        
        'port': json['port'],
        
    };
}

export function LxcVncwebsocketResponseDataToJSON(json: any): LxcVncwebsocketResponseData {
    return LxcVncwebsocketResponseDataToJSONTyped(json, false);
}

export function LxcVncwebsocketResponseDataToJSONTyped(value?: LxcVncwebsocketResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'port': value['port'],
        
    };
}

