/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveFormatFormatEnum } from './PveFormatFormatEnum';
import {
    PveFormatFormatEnumFromJSON,
    PveFormatFormatEnumFromJSONTyped,
    PveFormatFormatEnumToJSON,
    PveFormatFormatEnumToJSONTyped,
} from './PveFormatFormatEnum';

/**
 * 
 * @export
 * @interface NodesStorageCreateContentRequest
 */
export interface NodesStorageCreateContentRequest {

    /**
     * The name of the file to create.
     * @type {string}
     * @memberof NodesStorageCreateContentRequest
     */
    filename: string;

    /**
     * Format of the image.
     * @type {PveFormatFormatEnum}
     * @memberof NodesStorageCreateContentRequest
     */
    format?: PveFormatFormatEnum;

    /**
     * Size in kilobyte (1024 bytes). Optional suffixes 'M' (megabyte, 1024K) and 'G' (gigabyte, 1024M)
     * @type {string}
     * @memberof NodesStorageCreateContentRequest
     */
    size: string;

    /**
     * Specify owner VM
     * @type {number}
     * @memberof NodesStorageCreateContentRequest
     */
    vmid: number;

}



/**
 * Check if a given object implements the NodesStorageCreateContentRequest interface.
 */
export function instanceOfNodesStorageCreateContentRequest(value: object): value is NodesStorageCreateContentRequest {
    
    if (!('filename' in value) || value['filename'] === undefined) return false;
    
    
    if (!('size' in value) || value['size'] === undefined) return false;
    
    if (!('vmid' in value) || value['vmid'] === undefined) return false;
    
    return true;
}

export function NodesStorageCreateContentRequestFromJSON(json: any): NodesStorageCreateContentRequest {
    return NodesStorageCreateContentRequestFromJSONTyped(json, false);
}

export function NodesStorageCreateContentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesStorageCreateContentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'filename': json['filename'],
        
        'format': json['format'] == null ? undefined : PveFormatFormatEnumFromJSON(json['format']),
        
        'size': json['size'],
        
        'vmid': json['vmid'],
        
    };
}

export function NodesStorageCreateContentRequestToJSON(json: any): NodesStorageCreateContentRequest {
    return NodesStorageCreateContentRequestToJSONTyped(json, false);
}

export function NodesStorageCreateContentRequestToJSONTyped(value?: NodesStorageCreateContentRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'filename': value['filename'],
        
        'format': PveFormatFormatEnumToJSON(value['format']),
        
        'size': value['size'],
        
        'vmid': value['vmid'],
        
    };
}

