/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesSuspendallRequest
 */
export interface NodesSuspendallRequest {

    /**
     * Only consider Guests with these IDs.
     * @type {string}
     * @memberof NodesSuspendallRequest
     */
    vms?: string;

}

/**
 * Check if a given object implements the NodesSuspendallRequest interface.
 */
export function instanceOfNodesSuspendallRequest(value: object): value is NodesSuspendallRequest {
    
    
    return true;
}

export function NodesSuspendallRequestFromJSON(json: any): NodesSuspendallRequest {
    return NodesSuspendallRequestFromJSONTyped(json, false);
}

export function NodesSuspendallRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesSuspendallRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'vms': json['vms'] == null ? undefined : json['vms'],
        
    };
}

export function NodesSuspendallRequestToJSON(json: any): NodesSuspendallRequest {
    return NodesSuspendallRequestToJSONTyped(json, false);
}

export function NodesSuspendallRequestToJSONTyped(value?: NodesSuspendallRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'vms': value['vms'],
        
    };
}

