/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodesTasksNodeTasksResponseDataInner } from './NodesTasksNodeTasksResponseDataInner';
import {
    NodesTasksNodeTasksResponseDataInnerFromJSON,
    NodesTasksNodeTasksResponseDataInnerFromJSONTyped,
    NodesTasksNodeTasksResponseDataInnerToJSON,
    NodesTasksNodeTasksResponseDataInnerToJSONTyped,
} from './NodesTasksNodeTasksResponseDataInner';

/**
 * 
 * @export
 * @interface NodesTasksNodeTasksResponse
 */
export interface NodesTasksNodeTasksResponse {

    /**
     * 
     * @type {Array<NodesTasksNodeTasksResponseDataInner>}
     * @memberof NodesTasksNodeTasksResponse
     */
    data: Array<NodesTasksNodeTasksResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesTasksNodeTasksResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesTasksNodeTasksResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesTasksNodeTasksResponse interface.
 */
export function instanceOfNodesTasksNodeTasksResponse(value: object): value is NodesTasksNodeTasksResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesTasksNodeTasksResponseFromJSON(json: any): NodesTasksNodeTasksResponse {
    return NodesTasksNodeTasksResponseFromJSONTyped(json, false);
}

export function NodesTasksNodeTasksResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesTasksNodeTasksResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(NodesTasksNodeTasksResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesTasksNodeTasksResponseToJSON(json: any): NodesTasksNodeTasksResponse {
    return NodesTasksNodeTasksResponseToJSONTyped(json, false);
}

export function NodesTasksNodeTasksResponseToJSONTyped(value?: NodesTasksNodeTasksResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(NodesTasksNodeTasksResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

