/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';
import type { PveBondXmitHashPolicyEnum } from './PveBondXmitHashPolicyEnum';
import {
    PveBondXmitHashPolicyEnumFromJSON,
    PveBondXmitHashPolicyEnumFromJSONTyped,
    PveBondXmitHashPolicyEnumToJSON,
    PveBondXmitHashPolicyEnumToJSONTyped,
} from './PveBondXmitHashPolicyEnum';
import type { PveNodesNetworkTypeTypeEnum } from './PveNodesNetworkTypeTypeEnum';
import {
    PveNodesNetworkTypeTypeEnumFromJSON,
    PveNodesNetworkTypeTypeEnumFromJSONTyped,
    PveNodesNetworkTypeTypeEnumToJSON,
    PveNodesNetworkTypeTypeEnumToJSONTyped,
} from './PveNodesNetworkTypeTypeEnum';
import type { PveNodesNetworkVlanProtocolEnum } from './PveNodesNetworkVlanProtocolEnum';
import {
    PveNodesNetworkVlanProtocolEnumFromJSON,
    PveNodesNetworkVlanProtocolEnumFromJSONTyped,
    PveNodesNetworkVlanProtocolEnumToJSON,
    PveNodesNetworkVlanProtocolEnumToJSONTyped,
} from './PveNodesNetworkVlanProtocolEnum';
import type { PveBondModeEnum } from './PveBondModeEnum';
import {
    PveBondModeEnumFromJSON,
    PveBondModeEnumFromJSONTyped,
    PveBondModeEnumToJSON,
    PveBondModeEnumToJSONTyped,
} from './PveBondModeEnum';
import type { PveNodesNetworkInlineEnum } from './PveNodesNetworkInlineEnum';
import {
    PveNodesNetworkInlineEnumFromJSON,
    PveNodesNetworkInlineEnumFromJSONTyped,
    PveNodesNetworkInlineEnumToJSON,
    PveNodesNetworkInlineEnumToJSONTyped,
} from './PveNodesNetworkInlineEnum';
import type { PveNodesNetworkMethodEnum } from './PveNodesNetworkMethodEnum';
import {
    PveNodesNetworkMethodEnumFromJSON,
    PveNodesNetworkMethodEnumFromJSONTyped,
    PveNodesNetworkMethodEnumToJSON,
    PveNodesNetworkMethodEnumToJSONTyped,
} from './PveNodesNetworkMethodEnum';

/**
 * 
 * @export
 * @interface NodesNetworkGetNetworkResponseDataInner
 */
export interface NodesNetworkGetNetworkResponseDataInner {

    /**
     * Set to true if the interface is active.
     * @type {PveBoolean}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    active?: PveBoolean;

    /**
     * IP address.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    address?: string;

    /**
     * IP address.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    address6?: string;

    /**
     * Automatically start interface on boot.
     * @type {PveBoolean}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    autostart?: PveBoolean;

    /**
     * Specify the primary interface for active-backup bond.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    bondPrimary?: string;

    /**
     * Bonding mode.
     * @type {PveBondModeEnum}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    bondMode?: PveBondModeEnum;

    /**
     * Selects the transmit hash policy to use for slave selection in balance-xor and 802.3ad modes.
     * @type {PveBondXmitHashPolicyEnum}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    bondXmitHashPolicy?: PveBondXmitHashPolicyEnum;

    /**
     * The bridge port access VLAN.
     * @type {number}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    bridgeAccess?: number;

    /**
     * Bridge port ARP/ND suppress flag.
     * @type {PveBoolean}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    bridgeArpNdSuppress?: PveBoolean;

    /**
     * Bridge port learning flag.
     * @type {PveBoolean}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    bridgeLearning?: PveBoolean;

    /**
     * Bridge port multicast flood flag.
     * @type {PveBoolean}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    bridgeMulticastFlood?: PveBoolean;

    /**
     * Bridge port unicast flood flag.
     * @type {PveBoolean}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    bridgeUnicastFlood?: PveBoolean;

    /**
     * Specify the interfaces you want to add to your bridge.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    bridgePorts?: string;

    /**
     * Specify the allowed VLANs. For example: '2 4 100-200'. Only used if the bridge is VLAN aware.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    bridgeVids?: string;

    /**
     * Enable bridge vlan support.
     * @type {PveBoolean}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    bridgeVlanAware?: PveBoolean;

    /**
     * IPv4 CIDR.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    cidr?: string;

    /**
     * IPv6 CIDR.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    cidr6?: string;

    /**
     * Comments
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    comments?: string;

    /**
     * Comments
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    comments6?: string;

    /**
     * Set to true if the interface physically exists.
     * @type {PveBoolean}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    _exists?: PveBoolean;

    /**
     * The network families.
     * @type {Array<PveNodesNetworkInlineEnum>}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    families?: Array<PveNodesNetworkInlineEnum>;

    /**
     * Default gateway address.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    gateway?: string;

    /**
     * Default ipv6 gateway address.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    gateway6?: string;

    /**
     * Network interface name.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    iface: string;

    /**
     * The link type.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    linkType?: string;

    /**
     * The network configuration method for IPv4.
     * @type {PveNodesNetworkMethodEnum}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    method?: PveNodesNetworkMethodEnum;

    /**
     * The network configuration method for IPv6.
     * @type {PveNodesNetworkMethodEnum}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    method6?: PveNodesNetworkMethodEnum;

    /**
     * MTU.
     * @type {number}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    mtu?: number;

    /**
     * Network mask.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    netmask?: string;

    /**
     * Network mask.
     * @type {number}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    netmask6?: number;

    /**
     * A list of additional interface options for IPv4.
     * @type {Array<string>}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    options?: Array<string>;

    /**
     * A list of additional interface options for IPv6.
     * @type {Array<string>}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    options6?: Array<string>;

    /**
     * Specify the interfaces used by the bonding device.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    ovsBonds?: string;

    /**
     * The OVS bridge associated with a OVS port. This is required when you create an OVS port.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    ovsBridge?: string;

    /**
     * OVS interface options.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    ovsOptions?: string;

    /**
     * Specify the interfaces you want to add to your bridge.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    ovsPorts?: string;

    /**
     * Specify a VLan tag (used by OVSPort, OVSIntPort, OVSBond)
     * @type {number}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    ovsTag?: number;

    /**
     * The order of the interface.
     * @type {number}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    priority?: number;

    /**
     * Specify the interfaces used by the bonding device.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    slaves?: string;

    /**
     * Network interface type
     * @type {PveNodesNetworkTypeTypeEnum}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    type: PveNodesNetworkTypeTypeEnum;

    /**
     * The uplink ID.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    uplinkId?: string;

    /**
     * vlan-id for a custom named vlan interface (ifupdown2 only).
     * @type {number}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    vlanId?: number;

    /**
     * The VLAN protocol.
     * @type {PveNodesNetworkVlanProtocolEnum}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    vlanProtocol?: PveNodesNetworkVlanProtocolEnum;

    /**
     * Specify the raw interface for the vlan interface.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    vlanRawDevice?: string;

    /**
     * The VXLAN ID.
     * @type {number}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    vxlanId?: number;

    /**
     * The VXLAN local tunnel IP.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    vxlanLocalTunnelip?: string;

    /**
     * The physical device for the VXLAN tunnel.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    vxlanPhysdev?: string;

    /**
     * The VXLAN SVC node IP.
     * @type {string}
     * @memberof NodesNetworkGetNetworkResponseDataInner
     */
    vxlanSvcnodeip?: string;

}



/**
 * Check if a given object implements the NodesNetworkGetNetworkResponseDataInner interface.
 */
export function instanceOfNodesNetworkGetNetworkResponseDataInner(value: object): value is NodesNetworkGetNetworkResponseDataInner {
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    if (!('iface' in value) || value['iface'] === undefined) return false;
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    if (!('type' in value) || value['type'] === undefined) return false;
    
    
    
    
    
    
    
    
    
    return true;
}

export function NodesNetworkGetNetworkResponseDataInnerFromJSON(json: any): NodesNetworkGetNetworkResponseDataInner {
    return NodesNetworkGetNetworkResponseDataInnerFromJSONTyped(json, false);
}

export function NodesNetworkGetNetworkResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesNetworkGetNetworkResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'active': json['active'] == null ? undefined : PveBooleanFromJSON(json['active']),
        
        'address': json['address'] == null ? undefined : json['address'],
        
        'address6': json['address6'] == null ? undefined : json['address6'],
        
        'autostart': json['autostart'] == null ? undefined : PveBooleanFromJSON(json['autostart']),
        
        'bondPrimary': json['bond-primary'] == null ? undefined : json['bond-primary'],
        
        'bondMode': json['bond_mode'] == null ? undefined : PveBondModeEnumFromJSON(json['bond_mode']),
        
        'bondXmitHashPolicy': json['bond_xmit_hash_policy'] == null ? undefined : PveBondXmitHashPolicyEnumFromJSON(json['bond_xmit_hash_policy']),
        
        'bridgeAccess': json['bridge-access'] == null ? undefined : json['bridge-access'],
        
        'bridgeArpNdSuppress': json['bridge-arp-nd-suppress'] == null ? undefined : PveBooleanFromJSON(json['bridge-arp-nd-suppress']),
        
        'bridgeLearning': json['bridge-learning'] == null ? undefined : PveBooleanFromJSON(json['bridge-learning']),
        
        'bridgeMulticastFlood': json['bridge-multicast-flood'] == null ? undefined : PveBooleanFromJSON(json['bridge-multicast-flood']),
        
        'bridgeUnicastFlood': json['bridge-unicast-flood'] == null ? undefined : PveBooleanFromJSON(json['bridge-unicast-flood']),
        
        'bridgePorts': json['bridge_ports'] == null ? undefined : json['bridge_ports'],
        
        'bridgeVids': json['bridge_vids'] == null ? undefined : json['bridge_vids'],
        
        'bridgeVlanAware': json['bridge_vlan_aware'] == null ? undefined : PveBooleanFromJSON(json['bridge_vlan_aware']),
        
        'cidr': json['cidr'] == null ? undefined : json['cidr'],
        
        'cidr6': json['cidr6'] == null ? undefined : json['cidr6'],
        
        'comments': json['comments'] == null ? undefined : json['comments'],
        
        'comments6': json['comments6'] == null ? undefined : json['comments6'],
        
        '_exists': json['exists'] == null ? undefined : PveBooleanFromJSON(json['exists']),
        
        'families': json['families'] == null ? undefined : ((json['families'] as Array<any>).map(PveNodesNetworkInlineEnumFromJSON)),
        
        'gateway': json['gateway'] == null ? undefined : json['gateway'],
        
        'gateway6': json['gateway6'] == null ? undefined : json['gateway6'],
        
        'iface': json['iface'],
        
        'linkType': json['link-type'] == null ? undefined : json['link-type'],
        
        'method': json['method'] == null ? undefined : PveNodesNetworkMethodEnumFromJSON(json['method']),
        
        'method6': json['method6'] == null ? undefined : PveNodesNetworkMethodEnumFromJSON(json['method6']),
        
        'mtu': json['mtu'] == null ? undefined : json['mtu'],
        
        'netmask': json['netmask'] == null ? undefined : json['netmask'],
        
        'netmask6': json['netmask6'] == null ? undefined : json['netmask6'],
        
        'options': json['options'] == null ? undefined : json['options'],
        
        'options6': json['options6'] == null ? undefined : json['options6'],
        
        'ovsBonds': json['ovs_bonds'] == null ? undefined : json['ovs_bonds'],
        
        'ovsBridge': json['ovs_bridge'] == null ? undefined : json['ovs_bridge'],
        
        'ovsOptions': json['ovs_options'] == null ? undefined : json['ovs_options'],
        
        'ovsPorts': json['ovs_ports'] == null ? undefined : json['ovs_ports'],
        
        'ovsTag': json['ovs_tag'] == null ? undefined : json['ovs_tag'],
        
        'priority': json['priority'] == null ? undefined : json['priority'],
        
        'slaves': json['slaves'] == null ? undefined : json['slaves'],
        
        'type': PveNodesNetworkTypeTypeEnumFromJSON(json['type']),
        
        'uplinkId': json['uplink-id'] == null ? undefined : json['uplink-id'],
        
        'vlanId': json['vlan-id'] == null ? undefined : json['vlan-id'],
        
        'vlanProtocol': json['vlan-protocol'] == null ? undefined : PveNodesNetworkVlanProtocolEnumFromJSON(json['vlan-protocol']),
        
        'vlanRawDevice': json['vlan-raw-device'] == null ? undefined : json['vlan-raw-device'],
        
        'vxlanId': json['vxlan-id'] == null ? undefined : json['vxlan-id'],
        
        'vxlanLocalTunnelip': json['vxlan-local-tunnelip'] == null ? undefined : json['vxlan-local-tunnelip'],
        
        'vxlanPhysdev': json['vxlan-physdev'] == null ? undefined : json['vxlan-physdev'],
        
        'vxlanSvcnodeip': json['vxlan-svcnodeip'] == null ? undefined : json['vxlan-svcnodeip'],
        
    };
}

export function NodesNetworkGetNetworkResponseDataInnerToJSON(json: any): NodesNetworkGetNetworkResponseDataInner {
    return NodesNetworkGetNetworkResponseDataInnerToJSONTyped(json, false);
}

export function NodesNetworkGetNetworkResponseDataInnerToJSONTyped(value?: NodesNetworkGetNetworkResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'active': PveBooleanToJSON(value['active']),
        
        'address': value['address'],
        
        'address6': value['address6'],
        
        'autostart': PveBooleanToJSON(value['autostart']),
        
        'bond-primary': value['bondPrimary'],
        
        'bond_mode': PveBondModeEnumToJSON(value['bondMode']),
        
        'bond_xmit_hash_policy': PveBondXmitHashPolicyEnumToJSON(value['bondXmitHashPolicy']),
        
        'bridge-access': value['bridgeAccess'],
        
        'bridge-arp-nd-suppress': PveBooleanToJSON(value['bridgeArpNdSuppress']),
        
        'bridge-learning': PveBooleanToJSON(value['bridgeLearning']),
        
        'bridge-multicast-flood': PveBooleanToJSON(value['bridgeMulticastFlood']),
        
        'bridge-unicast-flood': PveBooleanToJSON(value['bridgeUnicastFlood']),
        
        'bridge_ports': value['bridgePorts'],
        
        'bridge_vids': value['bridgeVids'],
        
        'bridge_vlan_aware': PveBooleanToJSON(value['bridgeVlanAware']),
        
        'cidr': value['cidr'],
        
        'cidr6': value['cidr6'],
        
        'comments': value['comments'],
        
        'comments6': value['comments6'],
        
        'exists': PveBooleanToJSON(value['_exists']),
        
        'families': value['families'] == null ? undefined : ((value['families'] as Array<any>).map(PveNodesNetworkInlineEnumToJSON)),
        
        'gateway': value['gateway'],
        
        'gateway6': value['gateway6'],
        
        'iface': value['iface'],
        
        'link-type': value['linkType'],
        
        'method': PveNodesNetworkMethodEnumToJSON(value['method']),
        
        'method6': PveNodesNetworkMethodEnumToJSON(value['method6']),
        
        'mtu': value['mtu'],
        
        'netmask': value['netmask'],
        
        'netmask6': value['netmask6'],
        
        'options': value['options'],
        
        'options6': value['options6'],
        
        'ovs_bonds': value['ovsBonds'],
        
        'ovs_bridge': value['ovsBridge'],
        
        'ovs_options': value['ovsOptions'],
        
        'ovs_ports': value['ovsPorts'],
        
        'ovs_tag': value['ovsTag'],
        
        'priority': value['priority'],
        
        'slaves': value['slaves'],
        
        'type': PveNodesNetworkTypeTypeEnumToJSON(value['type']),
        
        'uplink-id': value['uplinkId'],
        
        'vlan-id': value['vlanId'],
        
        'vlan-protocol': PveNodesNetworkVlanProtocolEnumToJSON(value['vlanProtocol']),
        
        'vlan-raw-device': value['vlanRawDevice'],
        
        'vxlan-id': value['vxlanId'],
        
        'vxlan-local-tunnelip': value['vxlanLocalTunnelip'],
        
        'vxlan-physdev': value['vxlanPhysdev'],
        
        'vxlan-svcnodeip': value['vxlanSvcnodeip'],
        
    };
}

