/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesCephOutResponse
 */
export interface NodesCephOutResponse {

    /**
     * 
     * @type {any}
     * @memberof NodesCephOutResponse
     */
    data: any | null;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesCephOutResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesCephOutResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesCephOutResponse interface.
 */
export function instanceOfNodesCephOutResponse(value: object): value is NodesCephOutResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesCephOutResponseFromJSON(json: any): NodesCephOutResponse {
    return NodesCephOutResponseFromJSONTyped(json, false);
}

export function NodesCephOutResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesCephOutResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesCephOutResponseToJSON(json: any): NodesCephOutResponse {
    return NodesCephOutResponseToJSONTyped(json, false);
}

export function NodesCephOutResponseToJSONTyped(value?: NodesCephOutResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

