/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';

/**
 * 
 * @export
 * @interface NodesCertificatesNewCertificateRequest
 */
export interface NodesCertificatesNewCertificateRequest {

    /**
     * Overwrite existing custom certificate.
     * @type {PveBoolean}
     * @memberof NodesCertificatesNewCertificateRequest
     */
    force?: PveBoolean;

}



/**
 * Check if a given object implements the NodesCertificatesNewCertificateRequest interface.
 */
export function instanceOfNodesCertificatesNewCertificateRequest(value: object): value is NodesCertificatesNewCertificateRequest {
    
    
    return true;
}

export function NodesCertificatesNewCertificateRequestFromJSON(json: any): NodesCertificatesNewCertificateRequest {
    return NodesCertificatesNewCertificateRequestFromJSONTyped(json, false);
}

export function NodesCertificatesNewCertificateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesCertificatesNewCertificateRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'force': json['force'] == null ? undefined : PveBooleanFromJSON(json['force']),
        
    };
}

export function NodesCertificatesNewCertificateRequestToJSON(json: any): NodesCertificatesNewCertificateRequest {
    return NodesCertificatesNewCertificateRequestToJSONTyped(json, false);
}

export function NodesCertificatesNewCertificateRequestToJSONTyped(value?: NodesCertificatesNewCertificateRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'force': PveBooleanToJSON(value['force']),
        
    };
}

