/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ClusterGetClusterResponseDataInner } from './ClusterGetClusterResponseDataInner';
import {
    ClusterGetClusterResponseDataInnerFromJSON,
    ClusterGetClusterResponseDataInnerFromJSONTyped,
    ClusterGetClusterResponseDataInnerToJSON,
    ClusterGetClusterResponseDataInnerToJSONTyped,
} from './ClusterGetClusterResponseDataInner';

/**
 * 
 * @export
 * @interface NodesCapabilitiesGetCapabilitiesResponse
 */
export interface NodesCapabilitiesGetCapabilitiesResponse {

    /**
     * 
     * @type {Array<ClusterGetClusterResponseDataInner>}
     * @memberof NodesCapabilitiesGetCapabilitiesResponse
     */
    data: Array<ClusterGetClusterResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesCapabilitiesGetCapabilitiesResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesCapabilitiesGetCapabilitiesResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesCapabilitiesGetCapabilitiesResponse interface.
 */
export function instanceOfNodesCapabilitiesGetCapabilitiesResponse(value: object): value is NodesCapabilitiesGetCapabilitiesResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesCapabilitiesGetCapabilitiesResponseFromJSON(json: any): NodesCapabilitiesGetCapabilitiesResponse {
    return NodesCapabilitiesGetCapabilitiesResponseFromJSONTyped(json, false);
}

export function NodesCapabilitiesGetCapabilitiesResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesCapabilitiesGetCapabilitiesResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(ClusterGetClusterResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesCapabilitiesGetCapabilitiesResponseToJSON(json: any): NodesCapabilitiesGetCapabilitiesResponse {
    return NodesCapabilitiesGetCapabilitiesResponseToJSONTyped(json, false);
}

export function NodesCapabilitiesGetCapabilitiesResponseToJSONTyped(value?: NodesCapabilitiesGetCapabilitiesResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(ClusterGetClusterResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

