/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesScanCifsscanResponseDataInner
 */
export interface NodesScanCifsscanResponseDataInner {

    /**
     * Descriptive text from server.
     * @type {string}
     * @memberof NodesScanCifsscanResponseDataInner
     */
    description: string;

    /**
     * The cifs share name.
     * @type {string}
     * @memberof NodesScanCifsscanResponseDataInner
     */
    share: string;

}

/**
 * Check if a given object implements the NodesScanCifsscanResponseDataInner interface.
 */
export function instanceOfNodesScanCifsscanResponseDataInner(value: object): value is NodesScanCifsscanResponseDataInner {
    
    if (!('description' in value) || value['description'] === undefined) return false;
    
    if (!('share' in value) || value['share'] === undefined) return false;
    
    return true;
}

export function NodesScanCifsscanResponseDataInnerFromJSON(json: any): NodesScanCifsscanResponseDataInner {
    return NodesScanCifsscanResponseDataInnerFromJSONTyped(json, false);
}

export function NodesScanCifsscanResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesScanCifsscanResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'description': json['description'],
        
        'share': json['share'],
        
    };
}

export function NodesScanCifsscanResponseDataInnerToJSON(json: any): NodesScanCifsscanResponseDataInner {
    return NodesScanCifsscanResponseDataInnerToJSONTyped(json, false);
}

export function NodesScanCifsscanResponseDataInnerToJSONTyped(value?: NodesScanCifsscanResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'description': value['description'],
        
        'share': value['share'],
        
    };
}

