/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesScanZfsscanResponseDataInner
 */
export interface NodesScanZfsscanResponseDataInner {

    /**
     * ZFS pool name.
     * @type {string}
     * @memberof NodesScanZfsscanResponseDataInner
     */
    pool: string;

}

/**
 * Check if a given object implements the NodesScanZfsscanResponseDataInner interface.
 */
export function instanceOfNodesScanZfsscanResponseDataInner(value: object): value is NodesScanZfsscanResponseDataInner {
    
    if (!('pool' in value) || value['pool'] === undefined) return false;
    
    return true;
}

export function NodesScanZfsscanResponseDataInnerFromJSON(json: any): NodesScanZfsscanResponseDataInner {
    return NodesScanZfsscanResponseDataInnerFromJSONTyped(json, false);
}

export function NodesScanZfsscanResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesScanZfsscanResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'pool': json['pool'],
        
    };
}

export function NodesScanZfsscanResponseDataInnerToJSON(json: any): NodesScanZfsscanResponseDataInner {
    return NodesScanZfsscanResponseDataInnerToJSONTyped(json, false);
}

export function NodesScanZfsscanResponseDataInnerToJSONTyped(value?: NodesScanZfsscanResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'pool': value['pool'],
        
    };
}

