/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';
import type { PveNodesAptInlineEnum } from './PveNodesAptInlineEnum';
import {
    PveNodesAptInlineEnumFromJSON,
    PveNodesAptInlineEnumFromJSONTyped,
    PveNodesAptInlineEnumToJSON,
    PveNodesAptInlineEnumToJSONTyped,
} from './PveNodesAptInlineEnum';
import type { PveFileTypeEnum } from './PveFileTypeEnum';
import {
    PveFileTypeEnumFromJSON,
    PveFileTypeEnumFromJSONTyped,
    PveFileTypeEnumToJSON,
    PveFileTypeEnumToJSONTyped,
} from './PveFileTypeEnum';
import type { NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner } from './NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner';
import {
    NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInnerFromJSON,
    NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInnerFromJSONTyped,
    NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInnerToJSON,
    NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInnerToJSONTyped,
} from './NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner';

/**
 * 
 * @export
 * @interface NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner
 */
export interface NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner {

    /**
     * Associated comment
     * @type {string}
     * @memberof NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner
     */
    comment?: string;

    /**
     * List of repository components
     * @type {Array<string>}
     * @memberof NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner
     */
    components?: Array<string>;

    /**
     * Whether the repository is enabled or not
     * @type {PveBoolean}
     * @memberof NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner
     */
    enabled: PveBoolean;

    /**
     * Format of the defining file.
     * @type {PveFileTypeEnum}
     * @memberof NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner
     */
    fileType: PveFileTypeEnum;

    /**
     * Additional options
     * @type {Array<NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner>}
     * @memberof NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner
     */
    options?: Array<NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner>;

    /**
     * List of package distribuitions
     * @type {Array<string>}
     * @memberof NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner
     */
    suites: Array<string>;

    /**
     * List of package types.
     * @type {Array<PveNodesAptInlineEnum>}
     * @memberof NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner
     */
    types: Array<PveNodesAptInlineEnum>;

    /**
     * List of repository URIs.
     * @type {Array<string>}
     * @memberof NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner
     */
    uRIs: Array<string>;

}



/**
 * Check if a given object implements the NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner interface.
 */
export function instanceOfNodesAptRepositoriesResponseDataFilesInnerRepositoriesInner(value: object): value is NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner {
    
    
    
    if (!('enabled' in value) || value['enabled'] === undefined) return false;
    
    if (!('fileType' in value) || value['fileType'] === undefined) return false;
    
    
    if (!('suites' in value) || value['suites'] === undefined) return false;
    
    if (!('types' in value) || value['types'] === undefined) return false;
    
    if (!('uRIs' in value) || value['uRIs'] === undefined) return false;
    
    return true;
}

export function NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerFromJSON(json: any): NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner {
    return NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerFromJSONTyped(json, false);
}

export function NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'comment': json['Comment'] == null ? undefined : json['Comment'],
        
        'components': json['Components'] == null ? undefined : json['Components'],
        
        'enabled': PveBooleanFromJSON(json['Enabled']),
        
        'fileType': PveFileTypeEnumFromJSON(json['FileType']),
        
        'options': json['Options'] == null ? undefined : ((json['Options'] as Array<any>).map(NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInnerFromJSON)),
        
        'suites': json['Suites'],
        
        'types': ((json['Types'] as Array<any>).map(PveNodesAptInlineEnumFromJSON)),
        
        'uRIs': json['URIs'],
        
    };
}

export function NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerToJSON(json: any): NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner {
    return NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerToJSONTyped(json, false);
}

export function NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerToJSONTyped(value?: NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'Comment': value['comment'],
        
        'Components': value['components'],
        
        'Enabled': PveBooleanToJSON(value['enabled']),
        
        'FileType': PveFileTypeEnumToJSON(value['fileType']),
        
        'Options': value['options'] == null ? undefined : ((value['options'] as Array<any>).map(NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInnerToJSON)),
        
        'Suites': value['suites'],
        
        'Types': ((value['types'] as Array<any>).map(PveNodesAptInlineEnumToJSON)),
        
        'URIs': value['uRIs'],
        
    };
}

