/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodesHardwareGetHardwareResponseDataInner } from './NodesHardwareGetHardwareResponseDataInner';
import {
    NodesHardwareGetHardwareResponseDataInnerFromJSON,
    NodesHardwareGetHardwareResponseDataInnerFromJSONTyped,
    NodesHardwareGetHardwareResponseDataInnerToJSON,
    NodesHardwareGetHardwareResponseDataInnerToJSONTyped,
} from './NodesHardwareGetHardwareResponseDataInner';

/**
 * 
 * @export
 * @interface NodesHardwareGetHardwareResponse
 */
export interface NodesHardwareGetHardwareResponse {

    /**
     * 
     * @type {Array<NodesHardwareGetHardwareResponseDataInner>}
     * @memberof NodesHardwareGetHardwareResponse
     */
    data: Array<NodesHardwareGetHardwareResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesHardwareGetHardwareResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesHardwareGetHardwareResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesHardwareGetHardwareResponse interface.
 */
export function instanceOfNodesHardwareGetHardwareResponse(value: object): value is NodesHardwareGetHardwareResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesHardwareGetHardwareResponseFromJSON(json: any): NodesHardwareGetHardwareResponse {
    return NodesHardwareGetHardwareResponseFromJSONTyped(json, false);
}

export function NodesHardwareGetHardwareResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesHardwareGetHardwareResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(NodesHardwareGetHardwareResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesHardwareGetHardwareResponseToJSON(json: any): NodesHardwareGetHardwareResponse {
    return NodesHardwareGetHardwareResponseToJSONTyped(json, false);
}

export function NodesHardwareGetHardwareResponseToJSONTyped(value?: NodesHardwareGetHardwareResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(NodesHardwareGetHardwareResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

