/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';

/**
 * 
 * @export
 * @interface NodesDisksCreateLvmthinRequest
 */
export interface NodesDisksCreateLvmthinRequest {

    /**
     * Configure storage using the thinpool.
     * @type {PveBoolean}
     * @memberof NodesDisksCreateLvmthinRequest
     */
    addStorage?: PveBoolean;

    /**
     * The block device you want to create the thinpool on.
     * @type {string}
     * @memberof NodesDisksCreateLvmthinRequest
     */
    device: string;

    /**
     * The storage identifier.
     * @type {string}
     * @memberof NodesDisksCreateLvmthinRequest
     */
    name: string;

}



/**
 * Check if a given object implements the NodesDisksCreateLvmthinRequest interface.
 */
export function instanceOfNodesDisksCreateLvmthinRequest(value: object): value is NodesDisksCreateLvmthinRequest {
    
    
    if (!('device' in value) || value['device'] === undefined) return false;
    
    if (!('name' in value) || value['name'] === undefined) return false;
    
    return true;
}

export function NodesDisksCreateLvmthinRequestFromJSON(json: any): NodesDisksCreateLvmthinRequest {
    return NodesDisksCreateLvmthinRequestFromJSONTyped(json, false);
}

export function NodesDisksCreateLvmthinRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesDisksCreateLvmthinRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'addStorage': json['add_storage'] == null ? undefined : PveBooleanFromJSON(json['add_storage']),
        
        'device': json['device'],
        
        'name': json['name'],
        
    };
}

export function NodesDisksCreateLvmthinRequestToJSON(json: any): NodesDisksCreateLvmthinRequest {
    return NodesDisksCreateLvmthinRequestToJSONTyped(json, false);
}

export function NodesDisksCreateLvmthinRequestToJSONTyped(value?: NodesDisksCreateLvmthinRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'add_storage': PveBooleanToJSON(value['addStorage']),
        
        'device': value['device'],
        
        'name': value['name'],
        
    };
}

