/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesSubscriptionUpdateSubscriptionRequest
 */
export interface NodesSubscriptionUpdateSubscriptionRequest {

    /**
     * Proxmox VE subscription key
     * @type {string}
     * @memberof NodesSubscriptionUpdateSubscriptionRequest
     */
    key: string;

}

/**
 * Check if a given object implements the NodesSubscriptionUpdateSubscriptionRequest interface.
 */
export function instanceOfNodesSubscriptionUpdateSubscriptionRequest(value: object): value is NodesSubscriptionUpdateSubscriptionRequest {
    
    if (!('key' in value) || value['key'] === undefined) return false;
    
    return true;
}

export function NodesSubscriptionUpdateSubscriptionRequestFromJSON(json: any): NodesSubscriptionUpdateSubscriptionRequest {
    return NodesSubscriptionUpdateSubscriptionRequestFromJSONTyped(json, false);
}

export function NodesSubscriptionUpdateSubscriptionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesSubscriptionUpdateSubscriptionRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'key': json['key'],
        
    };
}

export function NodesSubscriptionUpdateSubscriptionRequestToJSON(json: any): NodesSubscriptionUpdateSubscriptionRequest {
    return NodesSubscriptionUpdateSubscriptionRequestToJSONTyped(json, false);
}

export function NodesSubscriptionUpdateSubscriptionRequestToJSONTyped(value?: NodesSubscriptionUpdateSubscriptionRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'key': value['key'],
        
    };
}

