/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesAplinfoAplDownloadRequest
 */
export interface NodesAplinfoAplDownloadRequest {

    /**
     * The storage where the template will be stored
     * @type {string}
     * @memberof NodesAplinfoAplDownloadRequest
     */
    storage: string;

    /**
     * The template which will downloaded
     * @type {string}
     * @memberof NodesAplinfoAplDownloadRequest
     */
    template: string;

}

/**
 * Check if a given object implements the NodesAplinfoAplDownloadRequest interface.
 */
export function instanceOfNodesAplinfoAplDownloadRequest(value: object): value is NodesAplinfoAplDownloadRequest {
    
    if (!('storage' in value) || value['storage'] === undefined) return false;
    
    if (!('template' in value) || value['template'] === undefined) return false;
    
    return true;
}

export function NodesAplinfoAplDownloadRequestFromJSON(json: any): NodesAplinfoAplDownloadRequest {
    return NodesAplinfoAplDownloadRequestFromJSONTyped(json, false);
}

export function NodesAplinfoAplDownloadRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesAplinfoAplDownloadRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'storage': json['storage'],
        
        'template': json['template'],
        
    };
}

export function NodesAplinfoAplDownloadRequestToJSON(json: any): NodesAplinfoAplDownloadRequest {
    return NodesAplinfoAplDownloadRequestToJSONTyped(json, false);
}

export function NodesAplinfoAplDownloadRequestToJSONTyped(value?: NodesAplinfoAplDownloadRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'storage': value['storage'],
        
        'template': value['template'],
        
    };
}

