/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NodesCertificatesRemoveCustomCertResponse
 */
export interface NodesCertificatesRemoveCustomCertResponse {

    /**
     * 
     * @type {any}
     * @memberof NodesCertificatesRemoveCustomCertResponse
     */
    data: any | null;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesCertificatesRemoveCustomCertResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesCertificatesRemoveCustomCertResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesCertificatesRemoveCustomCertResponse interface.
 */
export function instanceOfNodesCertificatesRemoveCustomCertResponse(value: object): value is NodesCertificatesRemoveCustomCertResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesCertificatesRemoveCustomCertResponseFromJSON(json: any): NodesCertificatesRemoveCustomCertResponse {
    return NodesCertificatesRemoveCustomCertResponseFromJSONTyped(json, false);
}

export function NodesCertificatesRemoveCustomCertResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesCertificatesRemoveCustomCertResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': json['data'],
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesCertificatesRemoveCustomCertResponseToJSON(json: any): NodesCertificatesRemoveCustomCertResponse {
    return NodesCertificatesRemoveCustomCertResponseToJSONTyped(json, false);
}

export function NodesCertificatesRemoveCustomCertResponseToJSONTyped(value?: NodesCertificatesRemoveCustomCertResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': value['data'],
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

