/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessGetAccessResponseDataInner } from './AccessGetAccessResponseDataInner';
import {
    AccessGetAccessResponseDataInnerFromJSON,
    AccessGetAccessResponseDataInnerFromJSONTyped,
    AccessGetAccessResponseDataInnerToJSON,
    AccessGetAccessResponseDataInnerToJSONTyped,
} from './AccessGetAccessResponseDataInner';

/**
 * 
 * @export
 * @interface NodesStorageDiridxResponse
 */
export interface NodesStorageDiridxResponse {

    /**
     * 
     * @type {Array<AccessGetAccessResponseDataInner>}
     * @memberof NodesStorageDiridxResponse
     */
    data: Array<AccessGetAccessResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesStorageDiridxResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesStorageDiridxResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesStorageDiridxResponse interface.
 */
export function instanceOfNodesStorageDiridxResponse(value: object): value is NodesStorageDiridxResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesStorageDiridxResponseFromJSON(json: any): NodesStorageDiridxResponse {
    return NodesStorageDiridxResponseFromJSONTyped(json, false);
}

export function NodesStorageDiridxResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesStorageDiridxResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(AccessGetAccessResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesStorageDiridxResponseToJSON(json: any): NodesStorageDiridxResponse {
    return NodesStorageDiridxResponseToJSONTyped(json, false);
}

export function NodesStorageDiridxResponseToJSONTyped(value?: NodesStorageDiridxResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(AccessGetAccessResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

