/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodesHardwareMdevscanResponseDataInner } from './NodesHardwareMdevscanResponseDataInner';
import {
    NodesHardwareMdevscanResponseDataInnerFromJSON,
    NodesHardwareMdevscanResponseDataInnerFromJSONTyped,
    NodesHardwareMdevscanResponseDataInnerToJSON,
    NodesHardwareMdevscanResponseDataInnerToJSONTyped,
} from './NodesHardwareMdevscanResponseDataInner';

/**
 * 
 * @export
 * @interface NodesHardwareMdevscanResponse
 */
export interface NodesHardwareMdevscanResponse {

    /**
     * 
     * @type {Array<NodesHardwareMdevscanResponseDataInner>}
     * @memberof NodesHardwareMdevscanResponse
     */
    data: Array<NodesHardwareMdevscanResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesHardwareMdevscanResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesHardwareMdevscanResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesHardwareMdevscanResponse interface.
 */
export function instanceOfNodesHardwareMdevscanResponse(value: object): value is NodesHardwareMdevscanResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesHardwareMdevscanResponseFromJSON(json: any): NodesHardwareMdevscanResponse {
    return NodesHardwareMdevscanResponseFromJSONTyped(json, false);
}

export function NodesHardwareMdevscanResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesHardwareMdevscanResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(NodesHardwareMdevscanResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesHardwareMdevscanResponseToJSON(json: any): NodesHardwareMdevscanResponse {
    return NodesHardwareMdevscanResponseToJSONTyped(json, false);
}

export function NodesHardwareMdevscanResponseToJSONTyped(value?: NodesHardwareMdevscanResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(NodesHardwareMdevscanResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

