/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { NodesStorageGetStorageResponseDataInner } from './NodesStorageGetStorageResponseDataInner';
import {
    NodesStorageGetStorageResponseDataInnerFromJSON,
    NodesStorageGetStorageResponseDataInnerFromJSONTyped,
    NodesStorageGetStorageResponseDataInnerToJSON,
    NodesStorageGetStorageResponseDataInnerToJSONTyped,
} from './NodesStorageGetStorageResponseDataInner';

/**
 * 
 * @export
 * @interface NodesStorageGetStorageResponse
 */
export interface NodesStorageGetStorageResponse {

    /**
     * 
     * @type {Array<NodesStorageGetStorageResponseDataInner>}
     * @memberof NodesStorageGetStorageResponse
     */
    data: Array<NodesStorageGetStorageResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof NodesStorageGetStorageResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof NodesStorageGetStorageResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the NodesStorageGetStorageResponse interface.
 */
export function instanceOfNodesStorageGetStorageResponse(value: object): value is NodesStorageGetStorageResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function NodesStorageGetStorageResponseFromJSON(json: any): NodesStorageGetStorageResponse {
    return NodesStorageGetStorageResponseFromJSONTyped(json, false);
}

export function NodesStorageGetStorageResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesStorageGetStorageResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(NodesStorageGetStorageResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function NodesStorageGetStorageResponseToJSON(json: any): NodesStorageGetStorageResponse {
    return NodesStorageGetStorageResponseToJSONTyped(json, false);
}

export function NodesStorageGetStorageResponseToJSONTyped(value?: NodesStorageGetStorageResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(NodesStorageGetStorageResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

