/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveNodesSdnStatusEnum } from './PveNodesSdnStatusEnum';
import {
    PveNodesSdnStatusEnumFromJSON,
    PveNodesSdnStatusEnumFromJSONTyped,
    PveNodesSdnStatusEnumToJSON,
    PveNodesSdnStatusEnumToJSONTyped,
} from './PveNodesSdnStatusEnum';

/**
 * 
 * @export
 * @interface NodesSdnGetZonesResponseDataInner
 */
export interface NodesSdnGetZonesResponseDataInner {

    /**
     * Status of zone
     * @type {PveNodesSdnStatusEnum}
     * @memberof NodesSdnGetZonesResponseDataInner
     */
    status: PveNodesSdnStatusEnum;

    /**
     * The SDN zone object identifier.
     * @type {string}
     * @memberof NodesSdnGetZonesResponseDataInner
     */
    zone: string;

}



/**
 * Check if a given object implements the NodesSdnGetZonesResponseDataInner interface.
 */
export function instanceOfNodesSdnGetZonesResponseDataInner(value: object): value is NodesSdnGetZonesResponseDataInner {
    
    if (!('status' in value) || value['status'] === undefined) return false;
    
    if (!('zone' in value) || value['zone'] === undefined) return false;
    
    return true;
}

export function NodesSdnGetZonesResponseDataInnerFromJSON(json: any): NodesSdnGetZonesResponseDataInner {
    return NodesSdnGetZonesResponseDataInnerFromJSONTyped(json, false);
}

export function NodesSdnGetZonesResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodesSdnGetZonesResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'status': PveNodesSdnStatusEnumFromJSON(json['status']),
        
        'zone': json['zone'],
        
    };
}

export function NodesSdnGetZonesResponseDataInnerToJSON(json: any): NodesSdnGetZonesResponseDataInner {
    return NodesSdnGetZonesResponseDataInnerToJSONTyped(json, false);
}

export function NodesSdnGetZonesResponseDataInnerToJSONTyped(value?: NodesSdnGetZonesResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'status': PveNodesSdnStatusEnumToJSON(value['status']),
        
        'zone': value['zone'],
        
    };
}

