/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PvePoolsTypeTypeEnum } from './PvePoolsTypeTypeEnum';
import {
    PvePoolsTypeTypeEnumFromJSON,
    PvePoolsTypeTypeEnumFromJSONTyped,
    PvePoolsTypeTypeEnumToJSON,
    PvePoolsTypeTypeEnumToJSONTyped,
} from './PvePoolsTypeTypeEnum';

/**
 * 
 * @export
 * @interface PoolsGetPoolsResponseDataInnerMembersInner
 */
export interface PoolsGetPoolsResponseDataInnerMembersInner {

    /**
     * 
     * @type {string}
     * @memberof PoolsGetPoolsResponseDataInnerMembersInner
     */
    id: string;

    /**
     * 
     * @type {string}
     * @memberof PoolsGetPoolsResponseDataInnerMembersInner
     */
    node: string;

    /**
     * 
     * @type {string}
     * @memberof PoolsGetPoolsResponseDataInnerMembersInner
     */
    storage?: string;

    /**
     * 
     * @type {PvePoolsTypeTypeEnum}
     * @memberof PoolsGetPoolsResponseDataInnerMembersInner
     */
    type: PvePoolsTypeTypeEnum;

    /**
     * 
     * @type {number}
     * @memberof PoolsGetPoolsResponseDataInnerMembersInner
     */
    vmid?: number;

}



/**
 * Check if a given object implements the PoolsGetPoolsResponseDataInnerMembersInner interface.
 */
export function instanceOfPoolsGetPoolsResponseDataInnerMembersInner(value: object): value is PoolsGetPoolsResponseDataInnerMembersInner {
    
    if (!('id' in value) || value['id'] === undefined) return false;
    
    if (!('node' in value) || value['node'] === undefined) return false;
    
    
    if (!('type' in value) || value['type'] === undefined) return false;
    
    
    return true;
}

export function PoolsGetPoolsResponseDataInnerMembersInnerFromJSON(json: any): PoolsGetPoolsResponseDataInnerMembersInner {
    return PoolsGetPoolsResponseDataInnerMembersInnerFromJSONTyped(json, false);
}

export function PoolsGetPoolsResponseDataInnerMembersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PoolsGetPoolsResponseDataInnerMembersInner {
    if (json == null) {
        return json;
    }
    return {
        
        
        'id': json['id'],
        
        'node': json['node'],
        
        'storage': json['storage'] == null ? undefined : json['storage'],
        
        'type': PvePoolsTypeTypeEnumFromJSON(json['type']),
        
        'vmid': json['vmid'] == null ? undefined : json['vmid'],
        
    };
}

export function PoolsGetPoolsResponseDataInnerMembersInnerToJSON(json: any): PoolsGetPoolsResponseDataInnerMembersInner {
    return PoolsGetPoolsResponseDataInnerMembersInnerToJSONTyped(json, false);
}

export function PoolsGetPoolsResponseDataInnerMembersInnerToJSONTyped(value?: PoolsGetPoolsResponseDataInnerMembersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'id': value['id'],
        
        'node': value['node'],
        
        'storage': value['storage'],
        
        'type': PvePoolsTypeTypeEnumToJSON(value['type']),
        
        'vmid': value['vmid'],
        
    };
}

