/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PveClusterHaTypeEnum = {
    Group: 'group'
} as const;
export type PveClusterHaTypeEnum = typeof PveClusterHaTypeEnum[keyof typeof PveClusterHaTypeEnum];


export function instanceOfPveClusterHaTypeEnum(value: any): boolean {
    for (const key in PveClusterHaTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(PveClusterHaTypeEnum, key)) {
            if (PveClusterHaTypeEnum[key as keyof typeof PveClusterHaTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PveClusterHaTypeEnumFromJSON(json: any): PveClusterHaTypeEnum {
    return PveClusterHaTypeEnumFromJSONTyped(json, false);
}

export function PveClusterHaTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveClusterHaTypeEnum {
    return json as PveClusterHaTypeEnum;
}

export function PveClusterHaTypeEnumToJSON(value?: PveClusterHaTypeEnum | null): any {
    return value as any;
}

export function PveClusterHaTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PveClusterHaTypeEnum {
    return value as PveClusterHaTypeEnum;
}

