/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PveClusterTypeEnum = {
    Vm: 'vm',
    Storage: 'storage',
    Node: 'node',
    Sdn: 'sdn'
} as const;
export type PveClusterTypeEnum = typeof PveClusterTypeEnum[keyof typeof PveClusterTypeEnum];


export function instanceOfPveClusterTypeEnum(value: any): boolean {
    for (const key in PveClusterTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(PveClusterTypeEnum, key)) {
            if (PveClusterTypeEnum[key as keyof typeof PveClusterTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PveClusterTypeEnumFromJSON(json: any): PveClusterTypeEnum {
    return PveClusterTypeEnumFromJSONTyped(json, false);
}

export function PveClusterTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveClusterTypeEnum {
    return json as PveClusterTypeEnum;
}

export function PveClusterTypeEnumToJSON(value?: PveClusterTypeEnum | null): any {
    return value as any;
}

export function PveClusterTypeEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PveClusterTypeEnum {
    return value as PveClusterTypeEnum;
}

