/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PveClusterTypeEnum3 = {
    Cluster: 'cluster',
    Node: 'node'
} as const;
export type PveClusterTypeEnum3 = typeof PveClusterTypeEnum3[keyof typeof PveClusterTypeEnum3];


export function instanceOfPveClusterTypeEnum3(value: any): boolean {
    for (const key in PveClusterTypeEnum3) {
        if (Object.prototype.hasOwnProperty.call(PveClusterTypeEnum3, key)) {
            if (PveClusterTypeEnum3[key as keyof typeof PveClusterTypeEnum3] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PveClusterTypeEnum3FromJSON(json: any): PveClusterTypeEnum3 {
    return PveClusterTypeEnum3FromJSONTyped(json, false);
}

export function PveClusterTypeEnum3FromJSONTyped(json: any, ignoreDiscriminator: boolean): PveClusterTypeEnum3 {
    return json as PveClusterTypeEnum3;
}

export function PveClusterTypeEnum3ToJSON(value?: PveClusterTypeEnum3 | null): any {
    return value as any;
}

export function PveClusterTypeEnum3ToJSONTyped(value: any, ignoreDiscriminator: boolean): PveClusterTypeEnum3 {
    return value as PveClusterTypeEnum3;
}

