/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';

/**
 * 
 * @export
 * @interface PveFeaturesConfig
 */
export interface PveFeaturesConfig {

    /**
     * Mount /sys in unprivileged containers as `rw` instead of `mixed`. This can break networking under newer (>= v245) systemd-network use.
     * @type {PveBoolean}
     * @memberof PveFeaturesConfig
     */
    forceRwSys?: PveBoolean;

    /**
     * Allow using 'fuse' file systems in a container. Note that interactions between fuse and the freezer cgroup can potentially cause I/O deadlocks.
     * @type {PveBoolean}
     * @memberof PveFeaturesConfig
     */
    fuse?: PveBoolean;

    /**
     * For unprivileged containers only: Allow the use of the keyctl() system call. This is required to use docker inside a container. By default unprivileged containers will see this system call as non-existent. This is mostly a workaround for systemd-networkd, as it will treat it as a fatal error when some keyctl() operations are denied by the kernel due to lacking permissions. Essentially, you can choose between running systemd-networkd or docker.
     * @type {PveBoolean}
     * @memberof PveFeaturesConfig
     */
    keyctl?: PveBoolean;

    /**
     * Allow unprivileged containers to use mknod() to add certain device nodes. This requires a kernel with seccomp trap to user space support (5.3 or newer). This is experimental.
     * @type {PveBoolean}
     * @memberof PveFeaturesConfig
     */
    mknod?: PveBoolean;

    /**
     * Allow mounting file systems of specific types. This should be a list of file system types as used with the mount command. Note that this can have negative effects on the container's security. With access to a loop device, mounting a file can circumvent the mknod permission of the devices cgroup, mounting an NFS file system can block the host's I/O completely and prevent it from rebooting, etc.
     * @type {string}
     * @memberof PveFeaturesConfig
     */
    mount?: string;

    /**
     * Allow nesting. Best used with unprivileged containers with additional id mapping. Note that this will expose procfs and sysfs contents of the host to the guest. This is also required by systemd to isolate services.
     * @type {PveBoolean}
     * @memberof PveFeaturesConfig
     */
    nesting?: PveBoolean;

}



/**
 * Check if a given object implements the PveFeaturesConfig interface.
 */
export function instanceOfPveFeaturesConfig(value: object): value is PveFeaturesConfig {
    
    
    
    
    
    
    
    return true;
}

export function PveFeaturesConfigFromJSON(json: any): PveFeaturesConfig {
    return PveFeaturesConfigFromJSONTyped(json, false);
}

export function PveFeaturesConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveFeaturesConfig {
    if (json == null) {
        return json;
    }
    return {
        
        
        'forceRwSys': json['force_rw_sys'] == null ? undefined : PveBooleanFromJSON(json['force_rw_sys']),
        
        'fuse': json['fuse'] == null ? undefined : PveBooleanFromJSON(json['fuse']),
        
        'keyctl': json['keyctl'] == null ? undefined : PveBooleanFromJSON(json['keyctl']),
        
        'mknod': json['mknod'] == null ? undefined : PveBooleanFromJSON(json['mknod']),
        
        'mount': json['mount'] == null ? undefined : json['mount'],
        
        'nesting': json['nesting'] == null ? undefined : PveBooleanFromJSON(json['nesting']),
        
    };
}

export function PveFeaturesConfigToJSON(json: any): PveFeaturesConfig {
    return PveFeaturesConfigToJSONTyped(json, false);
}

export function PveFeaturesConfigToJSONTyped(value?: PveFeaturesConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'force_rw_sys': PveBooleanToJSON(value['forceRwSys']),
        
        'fuse': PveBooleanToJSON(value['fuse']),
        
        'keyctl': PveBooleanToJSON(value['keyctl']),
        
        'mknod': PveBooleanToJSON(value['mknod']),
        
        'mount': value['mount'],
        
        'nesting': PveBooleanToJSON(value['nesting']),
        
    };
}

/**
 * Serialise a PveFeaturesConfig into Proxmox's CLI-style shorthand string
 * (`key=value,…`). The property marked `x-pve-default-key` is emitted
 * positionally without a `key=` prefix; aliases collapse multiple
 * property names to the same wire key.
 *
 * Example: `{ model: 'virtio', bridge: 'vmbr0', firewall: 1 }`
 *      → `'virtio,bridge=vmbr0,firewall=1'`
 */
export function PveFeaturesConfigToShorthand(value?: PveFeaturesConfig | null): string | undefined {
    if (value == null) return undefined;
    const parts: string[] = [];
    
    
    if (value['forceRwSys'] != null) {
        parts.push(`force_rw_sys=${String(value['forceRwSys'])}`);
    }
    
    if (value['fuse'] != null) {
        parts.push(`fuse=${String(value['fuse'])}`);
    }
    
    if (value['keyctl'] != null) {
        parts.push(`keyctl=${String(value['keyctl'])}`);
    }
    
    if (value['mknod'] != null) {
        parts.push(`mknod=${String(value['mknod'])}`);
    }
    
    if (value['mount'] != null) {
        parts.push(`mount=${String(value['mount'])}`);
    }
    
    if (value['nesting'] != null) {
        parts.push(`nesting=${String(value['nesting'])}`);
    }
    
    return parts.join(',');
}

/**
 * Parse a Proxmox shorthand string into a PveFeaturesConfig. Mirror of
 * PveFeaturesConfigToShorthand. The first comma-separated segment without
 * `=` is interpreted as the default-key value.
 */
export function PveFeaturesConfigFromShorthand(input?: string | null): PveFeaturesConfig | undefined {
    if (input == null) return undefined;
    const out: any = {};
    let defaultKeyConsumed = false;
    for (const part of input.split(',')) {
        if (!part) continue;
        const eq = part.indexOf('=');
        if (eq < 0) {
            
            continue;
        }
        const k = part.slice(0, eq);
        const v = part.slice(eq + 1);
        out[k] = v;
    }
    return out as PveFeaturesConfig;
}

