/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PveIvshmemConfig } from './PveIvshmemConfig';
import {
    instanceOfPveIvshmemConfig,
    PveIvshmemConfigFromJSON,
    PveIvshmemConfigFromJSONTyped,
    PveIvshmemConfigToJSON,
} from './PveIvshmemConfig';

/**
 * @type PveIvshmemField
 * 
 * @export
 */
export type PveIvshmemField = PveIvshmemConfig | string;

export function PveIvshmemFieldFromJSON(json: any): PveIvshmemField {
    return PveIvshmemFieldFromJSONTyped(json, false);
}

export function PveIvshmemFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveIvshmemField {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfPveIvshmemConfig(json)) {
        return PveIvshmemConfigFromJSONTyped(json, true);
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function PveIvshmemFieldToJSON(json: any): any {
    return PveIvshmemFieldToJSONTyped(json, false);
}

export function PveIvshmemFieldToJSONTyped(value?: PveIvshmemField | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfPveIvshmemConfig(value)) {
        return PveIvshmemConfigToJSON(value as PveIvshmemConfig);
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

