/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PveLogRatelimitConfig } from './PveLogRatelimitConfig';
import {
    instanceOfPveLogRatelimitConfig,
    PveLogRatelimitConfigFromJSON,
    PveLogRatelimitConfigFromJSONTyped,
    PveLogRatelimitConfigToJSON,
} from './PveLogRatelimitConfig';

/**
 * @type PveLogRatelimitField
 * 
 * @export
 */
export type PveLogRatelimitField = PveLogRatelimitConfig | string;

export function PveLogRatelimitFieldFromJSON(json: any): PveLogRatelimitField {
    return PveLogRatelimitFieldFromJSONTyped(json, false);
}

export function PveLogRatelimitFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveLogRatelimitField {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfPveLogRatelimitConfig(json)) {
        return PveLogRatelimitConfigFromJSONTyped(json, true);
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function PveLogRatelimitFieldToJSON(json: any): any {
    return PveLogRatelimitFieldToJSONTyped(json, false);
}

export function PveLogRatelimitFieldToJSONTyped(value?: PveLogRatelimitField | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfPveLogRatelimitConfig(value)) {
        return PveLogRatelimitConfigToJSON(value as PveLogRatelimitConfig);
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

