/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PveMailnotificationEnum = {
    Always: 'always',
    Failure: 'failure'
} as const;
export type PveMailnotificationEnum = typeof PveMailnotificationEnum[keyof typeof PveMailnotificationEnum];


export function instanceOfPveMailnotificationEnum(value: any): boolean {
    for (const key in PveMailnotificationEnum) {
        if (Object.prototype.hasOwnProperty.call(PveMailnotificationEnum, key)) {
            if (PveMailnotificationEnum[key as keyof typeof PveMailnotificationEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PveMailnotificationEnumFromJSON(json: any): PveMailnotificationEnum {
    return PveMailnotificationEnumFromJSONTyped(json, false);
}

export function PveMailnotificationEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveMailnotificationEnum {
    return json as PveMailnotificationEnum;
}

export function PveMailnotificationEnumToJSON(value?: PveMailnotificationEnum | null): any {
    return value as any;
}

export function PveMailnotificationEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PveMailnotificationEnum {
    return value as PveMailnotificationEnum;
}

