/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PveNodesCephActionEnum = {
    Stop: 'stop',
    Destroy: 'destroy'
} as const;
export type PveNodesCephActionEnum = typeof PveNodesCephActionEnum[keyof typeof PveNodesCephActionEnum];


export function instanceOfPveNodesCephActionEnum(value: any): boolean {
    for (const key in PveNodesCephActionEnum) {
        if (Object.prototype.hasOwnProperty.call(PveNodesCephActionEnum, key)) {
            if (PveNodesCephActionEnum[key as keyof typeof PveNodesCephActionEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PveNodesCephActionEnumFromJSON(json: any): PveNodesCephActionEnum {
    return PveNodesCephActionEnumFromJSONTyped(json, false);
}

export function PveNodesCephActionEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveNodesCephActionEnum {
    return json as PveNodesCephActionEnum;
}

export function PveNodesCephActionEnumToJSON(value?: PveNodesCephActionEnum | null): any {
    return value as any;
}

export function PveNodesCephActionEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PveNodesCephActionEnum {
    return value as PveNodesCephActionEnum;
}

