/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PveNumaConfig } from './PveNumaConfig';
import {
    instanceOfPveNumaConfig,
    PveNumaConfigFromJSON,
    PveNumaConfigFromJSONTyped,
    PveNumaConfigToJSON,
} from './PveNumaConfig';

/**
 * @type PveNumaField
 * 
 * @export
 */
export type PveNumaField = PveNumaConfig | string;

export function PveNumaFieldFromJSON(json: any): PveNumaField {
    return PveNumaFieldFromJSONTyped(json, false);
}

export function PveNumaFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveNumaField {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfPveNumaConfig(json)) {
        return PveNumaConfigFromJSONTyped(json, true);
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function PveNumaFieldToJSON(json: any): any {
    return PveNumaFieldToJSONTyped(json, false);
}

export function PveNumaFieldToJSONTyped(value?: PveNumaField | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfPveNumaConfig(value)) {
        return PveNumaConfigToJSON(value as PveNumaConfig);
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

