/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { PveAcmeConfig } from './PveAcmeConfig';
import {
    instanceOfPveAcmeConfig,
    PveAcmeConfigFromJSON,
    PveAcmeConfigFromJSONTyped,
    PveAcmeConfigToJSON,
} from './PveAcmeConfig';

/**
 * @type PveNodesConfigAcmeField
 * 
 * @export
 */
export type PveNodesConfigAcmeField = PveAcmeConfig | string;

export function PveNodesConfigAcmeFieldFromJSON(json: any): PveNodesConfigAcmeField {
    return PveNodesConfigAcmeFieldFromJSONTyped(json, false);
}

export function PveNodesConfigAcmeFieldFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveNodesConfigAcmeField {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfPveAcmeConfig(json)) {
        return PveAcmeConfigFromJSONTyped(json, true);
    }
    if (typeof json === 'string') {
        return json;
    }
    return {} as any;
}

export function PveNodesConfigAcmeFieldToJSON(json: any): any {
    return PveNodesConfigAcmeFieldToJSONTyped(json, false);
}

export function PveNodesConfigAcmeFieldToJSONTyped(value?: PveNodesConfigAcmeField | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfPveAcmeConfig(value)) {
        return PveAcmeConfigToJSON(value as PveAcmeConfig);
    }
    if (typeof value === 'string') {
        return value;
    }
    return {};
}

