/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveFencingEnum } from './PveFencingEnum';
import {
    PveFencingEnumFromJSON,
    PveFencingEnumFromJSONTyped,
    PveFencingEnumToJSON,
    PveFencingEnumToJSONTyped,
} from './PveFencingEnum';
import type { PveClusterOptionsPackageUpdatesEnum } from './PveClusterOptionsPackageUpdatesEnum';
import {
    PveClusterOptionsPackageUpdatesEnumFromJSON,
    PveClusterOptionsPackageUpdatesEnumFromJSONTyped,
    PveClusterOptionsPackageUpdatesEnumToJSON,
    PveClusterOptionsPackageUpdatesEnumToJSONTyped,
} from './PveClusterOptionsPackageUpdatesEnum';

/**
 * 
 * @export
 * @interface PveNotifyConfig
 */
export interface PveNotifyConfig {

    /**
     * UNUSED - Use datacenter notification settings instead.
     * @type {PveFencingEnum}
     * @memberof PveNotifyConfig
     */
    fencing?: PveFencingEnum;

    /**
     * DEPRECATED: Use datacenter notification settings instead.
     * Control how often the daily update job should send out notifications:
     * * 'auto' daily for systems with a valid subscription, as those are assumed to be  production-ready and thus should know about pending updates.
     * * 'always' every update, if there are new pending updates.
     * * 'never' never send a notification for new pending updates.
     * 
     * @type {PveClusterOptionsPackageUpdatesEnum}
     * @memberof PveNotifyConfig
     */
    packageUpdates?: PveClusterOptionsPackageUpdatesEnum;

    /**
     * UNUSED - Use datacenter notification settings instead.
     * @type {PveFencingEnum}
     * @memberof PveNotifyConfig
     */
    replication?: PveFencingEnum;

    /**
     * UNUSED - Use datacenter notification settings instead.
     * @type {string}
     * @memberof PveNotifyConfig
     */
    targetFencing?: string;

    /**
     * UNUSED - Use datacenter notification settings instead.
     * @type {string}
     * @memberof PveNotifyConfig
     */
    targetPackageUpdates?: string;

    /**
     * UNUSED - Use datacenter notification settings instead.
     * @type {string}
     * @memberof PveNotifyConfig
     */
    targetReplication?: string;

}



/**
 * Check if a given object implements the PveNotifyConfig interface.
 */
export function instanceOfPveNotifyConfig(value: object): value is PveNotifyConfig {
    
    
    
    
    
    
    
    return true;
}

export function PveNotifyConfigFromJSON(json: any): PveNotifyConfig {
    return PveNotifyConfigFromJSONTyped(json, false);
}

export function PveNotifyConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveNotifyConfig {
    if (json == null) {
        return json;
    }
    return {
        
        
        'fencing': json['fencing'] == null ? undefined : PveFencingEnumFromJSON(json['fencing']),
        
        'packageUpdates': json['package-updates'] == null ? undefined : PveClusterOptionsPackageUpdatesEnumFromJSON(json['package-updates']),
        
        'replication': json['replication'] == null ? undefined : PveFencingEnumFromJSON(json['replication']),
        
        'targetFencing': json['target-fencing'] == null ? undefined : json['target-fencing'],
        
        'targetPackageUpdates': json['target-package-updates'] == null ? undefined : json['target-package-updates'],
        
        'targetReplication': json['target-replication'] == null ? undefined : json['target-replication'],
        
    };
}

export function PveNotifyConfigToJSON(json: any): PveNotifyConfig {
    return PveNotifyConfigToJSONTyped(json, false);
}

export function PveNotifyConfigToJSONTyped(value?: PveNotifyConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'fencing': PveFencingEnumToJSON(value['fencing']),
        
        'package-updates': PveClusterOptionsPackageUpdatesEnumToJSON(value['packageUpdates']),
        
        'replication': PveFencingEnumToJSON(value['replication']),
        
        'target-fencing': value['targetFencing'],
        
        'target-package-updates': value['targetPackageUpdates'],
        
        'target-replication': value['targetReplication'],
        
    };
}

/**
 * Serialise a PveNotifyConfig into Proxmox's CLI-style shorthand string
 * (`key=value,…`). The property marked `x-pve-default-key` is emitted
 * positionally without a `key=` prefix; aliases collapse multiple
 * property names to the same wire key.
 *
 * Example: `{ model: 'virtio', bridge: 'vmbr0', firewall: 1 }`
 *      → `'virtio,bridge=vmbr0,firewall=1'`
 */
export function PveNotifyConfigToShorthand(value?: PveNotifyConfig | null): string | undefined {
    if (value == null) return undefined;
    const parts: string[] = [];
    
    
    if (value['fencing'] != null) {
        parts.push(`fencing=${String(value['fencing'])}`);
    }
    
    if (value['packageUpdates'] != null) {
        parts.push(`package-updates=${String(value['packageUpdates'])}`);
    }
    
    if (value['replication'] != null) {
        parts.push(`replication=${String(value['replication'])}`);
    }
    
    if (value['targetFencing'] != null) {
        parts.push(`target-fencing=${String(value['targetFencing'])}`);
    }
    
    if (value['targetPackageUpdates'] != null) {
        parts.push(`target-package-updates=${String(value['targetPackageUpdates'])}`);
    }
    
    if (value['targetReplication'] != null) {
        parts.push(`target-replication=${String(value['targetReplication'])}`);
    }
    
    return parts.join(',');
}

/**
 * Parse a Proxmox shorthand string into a PveNotifyConfig. Mirror of
 * PveNotifyConfigToShorthand. The first comma-separated segment without
 * `=` is interpreted as the default-key value.
 */
export function PveNotifyConfigFromShorthand(input?: string | null): PveNotifyConfig | undefined {
    if (input == null) return undefined;
    const out: any = {};
    let defaultKeyConsumed = false;
    for (const part of input.split(',')) {
        if (!part) continue;
        const eq = part.indexOf('=');
        if (eq < 0) {
            
            continue;
        }
        const k = part.slice(0, eq);
        const v = part.slice(eq + 1);
        out[k] = v;
    }
    return out as PveNotifyConfig;
}

