/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PvePolicyForwardEnum = {
    Accept: 'ACCEPT',
    Drop: 'DROP'
} as const;
export type PvePolicyForwardEnum = typeof PvePolicyForwardEnum[keyof typeof PvePolicyForwardEnum];


export function instanceOfPvePolicyForwardEnum(value: any): boolean {
    for (const key in PvePolicyForwardEnum) {
        if (Object.prototype.hasOwnProperty.call(PvePolicyForwardEnum, key)) {
            if (PvePolicyForwardEnum[key as keyof typeof PvePolicyForwardEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PvePolicyForwardEnumFromJSON(json: any): PvePolicyForwardEnum {
    return PvePolicyForwardEnumFromJSONTyped(json, false);
}

export function PvePolicyForwardEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PvePolicyForwardEnum {
    return json as PvePolicyForwardEnum;
}

export function PvePolicyForwardEnumToJSON(value?: PvePolicyForwardEnum | null): any {
    return value as any;
}

export function PvePolicyForwardEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PvePolicyForwardEnum {
    return value as PvePolicyForwardEnum;
}

