/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PveQemuDiskEnum = {
    Ide0: 'ide0',
    Ide1: 'ide1',
    Ide2: 'ide2',
    Ide3: 'ide3',
    Scsi0: 'scsi0',
    Scsi1: 'scsi1',
    Scsi2: 'scsi2',
    Scsi3: 'scsi3',
    Scsi4: 'scsi4',
    Scsi5: 'scsi5',
    Scsi6: 'scsi6',
    Scsi7: 'scsi7',
    Scsi8: 'scsi8',
    Scsi9: 'scsi9',
    Scsi10: 'scsi10',
    Scsi11: 'scsi11',
    Scsi12: 'scsi12',
    Scsi13: 'scsi13',
    Scsi14: 'scsi14',
    Scsi15: 'scsi15',
    Scsi16: 'scsi16',
    Scsi17: 'scsi17',
    Scsi18: 'scsi18',
    Scsi19: 'scsi19',
    Scsi20: 'scsi20',
    Scsi21: 'scsi21',
    Scsi22: 'scsi22',
    Scsi23: 'scsi23',
    Scsi24: 'scsi24',
    Scsi25: 'scsi25',
    Scsi26: 'scsi26',
    Scsi27: 'scsi27',
    Scsi28: 'scsi28',
    Scsi29: 'scsi29',
    Scsi30: 'scsi30',
    Virtio0: 'virtio0',
    Virtio1: 'virtio1',
    Virtio2: 'virtio2',
    Virtio3: 'virtio3',
    Virtio4: 'virtio4',
    Virtio5: 'virtio5',
    Virtio6: 'virtio6',
    Virtio7: 'virtio7',
    Virtio8: 'virtio8',
    Virtio9: 'virtio9',
    Virtio10: 'virtio10',
    Virtio11: 'virtio11',
    Virtio12: 'virtio12',
    Virtio13: 'virtio13',
    Virtio14: 'virtio14',
    Virtio15: 'virtio15',
    Sata0: 'sata0',
    Sata1: 'sata1',
    Sata2: 'sata2',
    Sata3: 'sata3',
    Sata4: 'sata4',
    Sata5: 'sata5',
    Efidisk0: 'efidisk0',
    Tpmstate0: 'tpmstate0'
} as const;
export type PveQemuDiskEnum = typeof PveQemuDiskEnum[keyof typeof PveQemuDiskEnum];


export function instanceOfPveQemuDiskEnum(value: any): boolean {
    for (const key in PveQemuDiskEnum) {
        if (Object.prototype.hasOwnProperty.call(PveQemuDiskEnum, key)) {
            if (PveQemuDiskEnum[key as keyof typeof PveQemuDiskEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PveQemuDiskEnumFromJSON(json: any): PveQemuDiskEnum {
    return PveQemuDiskEnumFromJSONTyped(json, false);
}

export function PveQemuDiskEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveQemuDiskEnum {
    return json as PveQemuDiskEnum;
}

export function PveQemuDiskEnumToJSON(value?: PveQemuDiskEnum | null): any {
    return value as any;
}

export function PveQemuDiskEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PveQemuDiskEnum {
    return value as PveQemuDiskEnum;
}

