/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PveQemuArchEnum = {
    X8664: 'x86_64',
    Aarch64: 'aarch64'
} as const;
export type PveQemuArchEnum = typeof PveQemuArchEnum[keyof typeof PveQemuArchEnum];


export function instanceOfPveQemuArchEnum(value: any): boolean {
    for (const key in PveQemuArchEnum) {
        if (Object.prototype.hasOwnProperty.call(PveQemuArchEnum, key)) {
            if (PveQemuArchEnum[key as keyof typeof PveQemuArchEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PveQemuArchEnumFromJSON(json: any): PveQemuArchEnum {
    return PveQemuArchEnumFromJSONTyped(json, false);
}

export function PveQemuArchEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveQemuArchEnum {
    return json as PveQemuArchEnum;
}

export function PveQemuArchEnumToJSON(value?: PveQemuArchEnum | null): any {
    return value as any;
}

export function PveQemuArchEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PveQemuArchEnum {
    return value as PveQemuArchEnum;
}

