/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PveQemuDeviceEnum = {
    Ich9IntelHda: 'ich9-intel-hda',
    IntelHda: 'intel-hda',
    Ac97: 'AC97'
} as const;
export type PveQemuDeviceEnum = typeof PveQemuDeviceEnum[keyof typeof PveQemuDeviceEnum];


export function instanceOfPveQemuDeviceEnum(value: any): boolean {
    for (const key in PveQemuDeviceEnum) {
        if (Object.prototype.hasOwnProperty.call(PveQemuDeviceEnum, key)) {
            if (PveQemuDeviceEnum[key as keyof typeof PveQemuDeviceEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PveQemuDeviceEnumFromJSON(json: any): PveQemuDeviceEnum {
    return PveQemuDeviceEnumFromJSONTyped(json, false);
}

export function PveQemuDeviceEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveQemuDeviceEnum {
    return json as PveQemuDeviceEnum;
}

export function PveQemuDeviceEnumToJSON(value?: PveQemuDeviceEnum | null): any {
    return value as any;
}

export function PveQemuDeviceEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PveQemuDeviceEnum {
    return value as PveQemuDeviceEnum;
}

