/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveMigrationTypeEnum } from './PveMigrationTypeEnum';
import {
    PveMigrationTypeEnumFromJSON,
    PveMigrationTypeEnumFromJSONTyped,
    PveMigrationTypeEnumToJSON,
    PveMigrationTypeEnumToJSONTyped,
} from './PveMigrationTypeEnum';

/**
 * 
 * @export
 * @interface PveReplicationConfig
 */
export interface PveReplicationConfig {

    /**
     * CIDR of the (sub) network that is used for replication jobs.
     * @type {string}
     * @memberof PveReplicationConfig
     */
    network?: string;

    /**
     * Replication traffic is encrypted using an SSH tunnel by default. On secure, completely private networks this can be disabled to increase performance.
     * @type {PveMigrationTypeEnum}
     * @memberof PveReplicationConfig
     */
    type: PveMigrationTypeEnum;

}



/**
 * Check if a given object implements the PveReplicationConfig interface.
 */
export function instanceOfPveReplicationConfig(value: object): value is PveReplicationConfig {
    
    
    if (!('type' in value) || value['type'] === undefined) return false;
    
    return true;
}

export function PveReplicationConfigFromJSON(json: any): PveReplicationConfig {
    return PveReplicationConfigFromJSONTyped(json, false);
}

export function PveReplicationConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveReplicationConfig {
    if (json == null) {
        return json;
    }
    return {
        
        
        'network': json['network'] == null ? undefined : json['network'],
        
        'type': PveMigrationTypeEnumFromJSON(json['type']),
        
    };
}

export function PveReplicationConfigToJSON(json: any): PveReplicationConfig {
    return PveReplicationConfigToJSONTyped(json, false);
}

export function PveReplicationConfigToJSONTyped(value?: PveReplicationConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'network': value['network'],
        
        'type': PveMigrationTypeEnumToJSON(value['type']),
        
    };
}

/**
 * Serialise a PveReplicationConfig into Proxmox's CLI-style shorthand string
 * (`key=value,…`). The property marked `x-pve-default-key` is emitted
 * positionally without a `key=` prefix; aliases collapse multiple
 * property names to the same wire key.
 *
 * Example: `{ model: 'virtio', bridge: 'vmbr0', firewall: 1 }`
 *      → `'virtio,bridge=vmbr0,firewall=1'`
 */
export function PveReplicationConfigToShorthand(value?: PveReplicationConfig | null): string | undefined {
    if (value == null) return undefined;
    const parts: string[] = [];
    
    if (value['type'] != null) {
        parts.push(String(value['type']));
    }
    
    
    if (value['network'] != null) {
        parts.push(`network=${String(value['network'])}`);
    }
    
    return parts.join(',');
}

/**
 * Parse a Proxmox shorthand string into a PveReplicationConfig. Mirror of
 * PveReplicationConfigToShorthand. The first comma-separated segment without
 * `=` is interpreted as the default-key value.
 */
export function PveReplicationConfigFromShorthand(input?: string | null): PveReplicationConfig | undefined {
    if (input == null) return undefined;
    const out: any = {};
    let defaultKeyConsumed = false;
    for (const part of input.split(',')) {
        if (!part) continue;
        const eq = part.indexOf('=');
        if (eq < 0) {
            
            if (!defaultKeyConsumed) {
                out['type'] = part;
                defaultKeyConsumed = true;
                continue;
            }
            
            continue;
        }
        const k = part.slice(0, eq);
        const v = part.slice(eq + 1);
        out[k] = v;
    }
    return out as PveReplicationConfig;
}

