/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const PveSeverityEnum = {
    Warning: 'warning',
    Error: 'error'
} as const;
export type PveSeverityEnum = typeof PveSeverityEnum[keyof typeof PveSeverityEnum];


export function instanceOfPveSeverityEnum(value: any): boolean {
    for (const key in PveSeverityEnum) {
        if (Object.prototype.hasOwnProperty.call(PveSeverityEnum, key)) {
            if (PveSeverityEnum[key as keyof typeof PveSeverityEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function PveSeverityEnumFromJSON(json: any): PveSeverityEnum {
    return PveSeverityEnumFromJSONTyped(json, false);
}

export function PveSeverityEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveSeverityEnum {
    return json as PveSeverityEnum;
}

export function PveSeverityEnumToJSON(value?: PveSeverityEnum | null): any {
    return value as any;
}

export function PveSeverityEnumToJSONTyped(value: any, ignoreDiscriminator: boolean): PveSeverityEnum {
    return value as PveSeverityEnum;
}

