/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveQemuTypeTypeEnum } from './PveQemuTypeTypeEnum';
import {
    PveQemuTypeTypeEnumFromJSON,
    PveQemuTypeTypeEnumFromJSONTyped,
    PveQemuTypeTypeEnumToJSON,
    PveQemuTypeTypeEnumToJSONTyped,
} from './PveQemuTypeTypeEnum';
import type { PveClipboardEnum } from './PveClipboardEnum';
import {
    PveClipboardEnumFromJSON,
    PveClipboardEnumFromJSONTyped,
    PveClipboardEnumToJSON,
    PveClipboardEnumToJSONTyped,
} from './PveClipboardEnum';

/**
 * 
 * @export
 * @interface PveVgaConfig
 */
export interface PveVgaConfig {

    /**
     * Enable a specific clipboard. If not set, depending on the display type the SPICE one will be added. Migration with VNC clipboard is not yet supported!
     * @type {PveClipboardEnum}
     * @memberof PveVgaConfig
     */
    clipboard?: PveClipboardEnum;

    /**
     * Sets the VGA memory (in MiB). Has no effect with serial display.
     * @type {number}
     * @memberof PveVgaConfig
     */
    memory?: number;

    /**
     * Select the VGA type. Using type 'cirrus' is not recommended.
     * @type {PveQemuTypeTypeEnum}
     * @memberof PveVgaConfig
     */
    type?: PveQemuTypeTypeEnum;

}



/**
 * Check if a given object implements the PveVgaConfig interface.
 */
export function instanceOfPveVgaConfig(value: object): value is PveVgaConfig {
    
    
    
    
    return true;
}

export function PveVgaConfigFromJSON(json: any): PveVgaConfig {
    return PveVgaConfigFromJSONTyped(json, false);
}

export function PveVgaConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): PveVgaConfig {
    if (json == null) {
        return json;
    }
    return {
        
        
        'clipboard': json['clipboard'] == null ? undefined : PveClipboardEnumFromJSON(json['clipboard']),
        
        'memory': json['memory'] == null ? undefined : json['memory'],
        
        'type': json['type'] == null ? undefined : PveQemuTypeTypeEnumFromJSON(json['type']),
        
    };
}

export function PveVgaConfigToJSON(json: any): PveVgaConfig {
    return PveVgaConfigToJSONTyped(json, false);
}

export function PveVgaConfigToJSONTyped(value?: PveVgaConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'clipboard': PveClipboardEnumToJSON(value['clipboard']),
        
        'memory': value['memory'],
        
        'type': PveQemuTypeTypeEnumToJSON(value['type']),
        
    };
}

/**
 * Serialise a PveVgaConfig into Proxmox's CLI-style shorthand string
 * (`key=value,…`). The property marked `x-pve-default-key` is emitted
 * positionally without a `key=` prefix; aliases collapse multiple
 * property names to the same wire key.
 *
 * Example: `{ model: 'virtio', bridge: 'vmbr0', firewall: 1 }`
 *      → `'virtio,bridge=vmbr0,firewall=1'`
 */
export function PveVgaConfigToShorthand(value?: PveVgaConfig | null): string | undefined {
    if (value == null) return undefined;
    const parts: string[] = [];
    
    if (value['type'] != null) {
        parts.push(String(value['type']));
    }
    
    
    if (value['clipboard'] != null) {
        parts.push(`clipboard=${String(value['clipboard'])}`);
    }
    
    if (value['memory'] != null) {
        parts.push(`memory=${String(value['memory'])}`);
    }
    
    return parts.join(',');
}

/**
 * Parse a Proxmox shorthand string into a PveVgaConfig. Mirror of
 * PveVgaConfigToShorthand. The first comma-separated segment without
 * `=` is interpreted as the default-key value.
 */
export function PveVgaConfigFromShorthand(input?: string | null): PveVgaConfig | undefined {
    if (input == null) return undefined;
    const out: any = {};
    let defaultKeyConsumed = false;
    for (const part of input.split(',')) {
        if (!part) continue;
        const eq = part.indexOf('=');
        if (eq < 0) {
            
            if (!defaultKeyConsumed) {
                out['type'] = part;
                defaultKeyConsumed = true;
                continue;
            }
            
            continue;
        }
        const k = part.slice(0, eq);
        const v = part.slice(eq + 1);
        out[k] = v;
    }
    return out as PveVgaConfig;
}

