/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QemuVmConfigResponseData } from './QemuVmConfigResponseData';
import {
    QemuVmConfigResponseDataFromJSON,
    QemuVmConfigResponseDataFromJSONTyped,
    QemuVmConfigResponseDataToJSON,
    QemuVmConfigResponseDataToJSONTyped,
} from './QemuVmConfigResponseData';

/**
 * 
 * @export
 * @interface QemuVmConfigResponse
 */
export interface QemuVmConfigResponse {

    /**
     * 
     * @type {QemuVmConfigResponseData}
     * @memberof QemuVmConfigResponse
     */
    data: QemuVmConfigResponseData;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof QemuVmConfigResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof QemuVmConfigResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the QemuVmConfigResponse interface.
 */
export function instanceOfQemuVmConfigResponse(value: object): value is QemuVmConfigResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function QemuVmConfigResponseFromJSON(json: any): QemuVmConfigResponse {
    return QemuVmConfigResponseFromJSONTyped(json, false);
}

export function QemuVmConfigResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QemuVmConfigResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': QemuVmConfigResponseDataFromJSON(json['data']),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function QemuVmConfigResponseToJSON(json: any): QemuVmConfigResponse {
    return QemuVmConfigResponseToJSONTyped(json, false);
}

export function QemuVmConfigResponseToJSONTyped(value?: QemuVmConfigResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': QemuVmConfigResponseDataToJSON(value['data']),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

