/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QemuVmlistResponseDataInner } from './QemuVmlistResponseDataInner';
import {
    QemuVmlistResponseDataInnerFromJSON,
    QemuVmlistResponseDataInnerFromJSONTyped,
    QemuVmlistResponseDataInnerToJSON,
    QemuVmlistResponseDataInnerToJSONTyped,
} from './QemuVmlistResponseDataInner';

/**
 * 
 * @export
 * @interface QemuVmlistResponse
 */
export interface QemuVmlistResponse {

    /**
     * 
     * @type {Array<QemuVmlistResponseDataInner>}
     * @memberof QemuVmlistResponse
     */
    data: Array<QemuVmlistResponseDataInner>;

    /**
     * Optional total count, present for paginated list responses.
     * @type {number}
     * @memberof QemuVmlistResponse
     */
    total?: number;

    /**
     * Optional change summary returned by some PUT operations (one entry per modified field).
     * @type {object}
     * @memberof QemuVmlistResponse
     */
    changes?: object;

}

/**
 * Check if a given object implements the QemuVmlistResponse interface.
 */
export function instanceOfQemuVmlistResponse(value: object): value is QemuVmlistResponse {
    
    if (!('data' in value) || value['data'] === undefined) return false;
    
    
    
    return true;
}

export function QemuVmlistResponseFromJSON(json: any): QemuVmlistResponse {
    return QemuVmlistResponseFromJSONTyped(json, false);
}

export function QemuVmlistResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): QemuVmlistResponse {
    if (json == null) {
        return json;
    }
    return {
        
        
        'data': ((json['data'] as Array<any>).map(QemuVmlistResponseDataInnerFromJSON)),
        
        'total': json['total'] == null ? undefined : json['total'],
        
        'changes': json['changes'] == null ? undefined : json['changes'],
        
    };
}

export function QemuVmlistResponseToJSON(json: any): QemuVmlistResponse {
    return QemuVmlistResponseToJSONTyped(json, false);
}

export function QemuVmlistResponseToJSONTyped(value?: QemuVmlistResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'data': ((value['data'] as Array<any>).map(QemuVmlistResponseDataInnerToJSON)),
        
        'total': value['total'],
        
        'changes': value['changes'],
        
    };
}

