/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';

/**
 * 
 * @export
 * @interface QemuUnlinkRequest
 */
export interface QemuUnlinkRequest {

    /**
     * Force physical removal. Without this, we simple remove the disk from the config file and create an additional configuration entry called 'unused[n]', which contains the volume ID. Unlink of unused[n] always cause physical removal.
     * @type {PveBoolean}
     * @memberof QemuUnlinkRequest
     */
    force?: PveBoolean;

    /**
     * A list of disk IDs you want to delete.
     * @type {string}
     * @memberof QemuUnlinkRequest
     */
    idlist: string;

}



/**
 * Check if a given object implements the QemuUnlinkRequest interface.
 */
export function instanceOfQemuUnlinkRequest(value: object): value is QemuUnlinkRequest {
    
    
    if (!('idlist' in value) || value['idlist'] === undefined) return false;
    
    return true;
}

export function QemuUnlinkRequestFromJSON(json: any): QemuUnlinkRequest {
    return QemuUnlinkRequestFromJSONTyped(json, false);
}

export function QemuUnlinkRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): QemuUnlinkRequest {
    if (json == null) {
        return json;
    }
    return {
        
        
        'force': json['force'] == null ? undefined : PveBooleanFromJSON(json['force']),
        
        'idlist': json['idlist'],
        
    };
}

export function QemuUnlinkRequestToJSON(json: any): QemuUnlinkRequest {
    return QemuUnlinkRequestToJSONTyped(json, false);
}

export function QemuUnlinkRequestToJSONTyped(value?: QemuUnlinkRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'force': PveBooleanToJSON(value['force']),
        
        'idlist': value['idlist'],
        
    };
}

