/* tslint:disable */
/* eslint-disable */
/**
 * Proxmox Virtual Environment API
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PveBoolean } from './PveBoolean';
import {
    PveBooleanFromJSON,
    PveBooleanFromJSONTyped,
    PveBooleanToJSON,
    PveBooleanToJSONTyped,
} from './PveBoolean';

/**
 * 
 * @export
 * @interface QemuFileReadResponseData
 */
export interface QemuFileReadResponseData {

    /**
     * The content of the file, maximum 16777216
     * @type {string}
     * @memberof QemuFileReadResponseData
     */
    content: string;

    /**
     * If set to 1, the output is truncated and not complete
     * @type {PveBoolean}
     * @memberof QemuFileReadResponseData
     */
    truncated?: PveBoolean;

}



/**
 * Check if a given object implements the QemuFileReadResponseData interface.
 */
export function instanceOfQemuFileReadResponseData(value: object): value is QemuFileReadResponseData {
    
    if (!('content' in value) || value['content'] === undefined) return false;
    
    
    return true;
}

export function QemuFileReadResponseDataFromJSON(json: any): QemuFileReadResponseData {
    return QemuFileReadResponseDataFromJSONTyped(json, false);
}

export function QemuFileReadResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): QemuFileReadResponseData {
    if (json == null) {
        return json;
    }
    return {
        
        
        'content': json['content'],
        
        'truncated': json['truncated'] == null ? undefined : PveBooleanFromJSON(json['truncated']),
        
    };
}

export function QemuFileReadResponseDataToJSON(json: any): QemuFileReadResponseData {
    return QemuFileReadResponseDataToJSONTyped(json, false);
}

export function QemuFileReadResponseDataToJSONTyped(value?: QemuFileReadResponseData | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        
        'content': value['content'],
        
        'truncated': PveBooleanToJSON(value['truncated']),
        
    };
}

